// MODEL: Claude Opus (historical content and descriptions)
// MODEL: Claude Sonnet (data structure)
// Boston, MA - Places seed data (35 historic sites)

import { Prisma } from '@prisma/client';

/**
 * Places in Boston, Massachusetts
 *
 * Boston was the epicenter of colonial resistance and home to many of the
 * Revolution's pivotal events: the Massacre, the Tea Party, the siege.
 * The Freedom Trail connects many sites, though numerous others lie beyond it.
 */

export const bostonPlaces: Prisma.PlaceCreateInput[] = [
  // FREEDOM TRAIL SITES
  {
    id: 'boston-common',
    name: 'Boston Common',
    placeType: 'LANDMARK',
    description:
      'America\'s oldest public park (1634). British troops camped here before marching to Lexington and Concord. The Common served as a military staging ground throughout the siege of Boston.',
    lat: 42.3550,
    lng: -71.0656,
    address: '139 Tremont Street, Boston, MA 02111',
    hours: 'Open daily',
    admission: 'Free',
    website: 'https://www.boston.gov/parks/boston-common',
    phone: null,
    accessibilityNotes: 'Mostly flat; paved paths throughout.',
    parkingNotes: 'Boston Common Garage underneath.',
    amenities: ['restrooms', 'visitor center', 'walking paths'],
    historicalNote:
      'On the night of April 18, 1775, British regulars assembled here before rowing across to Cambridge and beginning their march to Concord. After the war, public celebrations marked key anniversaries.',
    displayOrder: 1,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'massachusetts-state-house',
    name: 'Massachusetts State House',
    placeType: 'GOVERNMENT',
    description:
      'The "new" State House (1798) designed by Charles Bulfinch. Its golden dome is a Boston landmark. The building houses the Massachusetts legislature and historical artifacts.',
    lat: 42.3587,
    lng: -71.0637,
    address: '24 Beacon Street, Boston, MA 02133',
    hours: 'Mon-Fri 9am-5pm; guided tours available',
    admission: 'Free',
    website: 'https://www.sec.state.ma.us/trs/trsidx.htm',
    phone: '(617) 727-3676',
    accessibilityNotes: 'Accessible entrance on Bowdoin Street.',
    parkingNotes: 'No dedicated parking; use nearby garages.',
    amenities: ['restrooms', 'guided tours', 'exhibits'],
    historicalNote:
      'While post-Revolutionary, the State House symbolizes the independent government Massachusetts fought for. Earlier colonial and state legislatures met at the Old State House.',
    displayOrder: 2,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'park-street-church',
    name: 'Park Street Church',
    placeType: 'CHURCH',
    description:
      'Prominent Congregational church (1809) on the corner of Park and Tremont streets. While post-Revolutionary, the site connects to Boston\'s religious and reform traditions.',
    lat: 42.3569,
    lng: -71.0619,
    address: '1 Park Street, Boston, MA 02108',
    hours: 'Tours mid-June to August, Tue-Sat 9:30am-3:30pm',
    admission: 'Free',
    website: 'https://www.parkstreet.org',
    phone: '(617) 523-3383',
    accessibilityNotes: 'Limited accessibility; historic structure.',
    parkingNotes: 'Boston Common Garage nearby.',
    amenities: ['tours'],
    historicalNote:
      'The church\'s 217-foot steeple was a landmark for ships entering Boston Harbor. William Lloyd Garrison delivered his first major anti-slavery speech here in 1829.',
    displayOrder: 3,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'granary-burying-ground',
    name: 'Granary Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Final resting place of Paul Revere, Samuel Adams, John Hancock, and victims of the Boston Massacre. One of the most historically significant cemeteries in America.',
    lat: 42.3573,
    lng: -71.0615,
    address: '83 Tremont Street, Boston, MA 02108',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground; narrow paths.',
    parkingNotes: 'Boston Common Garage.',
    amenities: [],
    historicalNote:
      'Founded in 1660, the cemetery contains approximately 2,300 marked graves. The victims of the Boston Massacre share a monument here. Paul Revere\'s grave is marked with a prominent sign.',
    displayOrder: 4,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'kings-chapel',
    name: 'King\'s Chapel',
    placeType: 'CHURCH',
    description:
      'The first Anglican church in Boston (original 1686; current building 1754). After the Revolution, it became the first Unitarian church in America.',
    lat: 42.3579,
    lng: -71.0595,
    address: '64 Beacon Street, Boston, MA 02108',
    hours: 'Sat 10am-4pm; services and concerts vary',
    admission: 'Free; donations appreciated',
    website: 'https://www.kings-chapel.org',
    phone: '(617) 227-2155',
    accessibilityNotes: 'Ground floor accessible.',
    parkingNotes: 'Nearby garages.',
    amenities: ['tours', 'concerts'],
    historicalNote:
      'British officials and Loyalists worshipped here. After independence, the congregation rejected both Episcopal hierarchy and Trinitarian doctrine, becoming Unitarian—a theological revolution matching the political one.',
    displayOrder: 5,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'kings-chapel-burying-ground',
    name: 'King\'s Chapel Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Boston\'s oldest cemetery (1630). Contains graves of Governor John Winthrop, Mary Chilton (first woman to step off the Mayflower), and other colonial figures.',
    lat: 42.3580,
    lng: -71.0593,
    address: 'Tremont Street, Boston, MA 02108',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground; limited accessibility.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'Many gravestones predate the Revolution by a century. The cemetery provides context for the long colonial history that shaped Revolutionary Boston.',
    displayOrder: 6,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'old-south-meeting-house',
    name: 'Old South Meeting House',
    placeType: 'CHURCH',
    description:
      'Puritan meeting house (1729) where colonists gathered before the Boston Tea Party. Samuel Adams reportedly gave the signal that launched the action against the tea ships.',
    lat: 42.3567,
    lng: -71.0586,
    address: '310 Washington Street, Boston, MA 02108',
    hours: 'Daily 10am-4pm (extended summer hours)',
    admission: '$8 adults, $7 seniors/students',
    website: 'https://www.revolutionaryspaces.org',
    phone: '(617) 482-6439',
    accessibilityNotes: 'Accessible entrance; ground floor exhibits.',
    parkingNotes: 'Nearby garages.',
    amenities: ['restrooms', 'gift shop', 'exhibits'],
    historicalNote:
      'On December 16, 1773, some 5,000 colonists packed the meeting house to debate the tea crisis. When Adams declared "This meeting can do nothing more to save the country," men disguised as Mohawks headed for the harbor.',
    displayOrder: 7,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'old-state-house',
    name: 'Old State House',
    placeType: 'GOVERNMENT',
    description:
      'The seat of British colonial government and later the Massachusetts legislature. The Declaration of Independence was read from its balcony on July 18, 1776.',
    lat: 42.3588,
    lng: -71.0577,
    address: '206 Washington Street, Boston, MA 02109',
    hours: 'Daily 10am-5pm',
    admission: '$12 adults, $10 seniors/students',
    website: 'https://www.revolutionaryspaces.org',
    phone: '(617) 720-1713',
    accessibilityNotes: 'Ground floor accessible; upper floors via stairs.',
    parkingNotes: 'Nearby garages.',
    amenities: ['restrooms', 'gift shop', 'exhibits'],
    historicalNote:
      'The Boston Massacre occurred just outside in 1770. The building housed both the colonial assembly and the royal governor—often at odds. After independence, it served as the state capitol until 1798.',
    displayOrder: 8,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'boston-massacre-site',
    name: 'Boston Massacre Site',
    placeType: 'MONUMENT',
    description:
      'Cobblestone circle marking where British soldiers killed five colonists on March 5, 1770. The event became a rallying cry for independence.',
    lat: 42.3588,
    lng: -71.0576,
    address: 'Corner of State and Congress Streets, Boston, MA 02109',
    hours: 'Always visible',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level; accessible.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'Crispus Attucks, a Black man of African and Wampanoag descent, was among the first killed. The event was heavily publicized by patriots including Paul Revere, whose engraving shaped public perception.',
    displayOrder: 9,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'faneuil-hall',
    name: 'Faneuil Hall',
    placeType: 'GOVERNMENT',
    description:
      'Known as "the Cradle of Liberty" for the revolutionary meetings held here. Donated to the town by merchant Peter Faneuil in 1742.',
    lat: 42.3600,
    lng: -71.0568,
    address: '1 Faneuil Hall Square, Boston, MA 02109',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    website: 'https://www.nps.gov/bost/learn/historyculture/fh.htm',
    phone: '(617) 242-5642',
    accessibilityNotes: 'Accessible entrance; elevator available.',
    parkingNotes: 'Quincy Market garage.',
    amenities: ['restrooms', 'ranger talks'],
    historicalNote:
      'Samuel Adams, James Otis, and other patriots spoke here against British policies. The hall served both as a meeting house and market. The grasshopper weathervane atop it has been a Boston landmark since 1742.',
    displayOrder: 10,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'paul-revere-house',
    name: 'Paul Revere House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'The oldest remaining structure in downtown Boston (circa 1680). Paul Revere owned and lived here from 1770 to 1800. He departed from here on his midnight ride.',
    lat: 42.3637,
    lng: -71.0535,
    address: '19 North Square, Boston, MA 02113',
    hours: 'Daily 9:30am-5:15pm (April-October); reduced winter hours',
    admission: '$6 adults, $5.50 seniors, $1 students',
    website: 'https://www.paulreverehouse.org',
    phone: '(617) 523-2338',
    accessibilityNotes: 'First floor accessible with assistance; upper floor via stairs.',
    parkingNotes: 'North End street parking or nearby garages.',
    amenities: ['exhibits', 'gift shop'],
    historicalNote:
      'Revere was a silversmith, engraver, and industrialist in addition to his famous ride. His home offers insight into colonial domestic life in the North End neighborhood.',
    displayOrder: 11,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'old-north-church',
    name: 'Old North Church',
    placeType: 'CHURCH',
    description:
      'Boston\'s oldest surviving church (1723). On April 18, 1775, sexton Robert Newman hung two lanterns in its steeple—the signal that British troops were leaving Boston by water.',
    lat: 42.3663,
    lng: -71.0545,
    address: '193 Salem Street, Boston, MA 02113',
    hours: 'Daily 9am-5pm (extended summer hours)',
    admission: '$8 adults; donations accepted',
    website: 'https://www.oldnorth.com',
    phone: '(617) 858-8231',
    accessibilityNotes: 'Ground floor accessible.',
    parkingNotes: 'North End garages.',
    amenities: ['restrooms', 'exhibits', 'gift shop', 'tours'],
    historicalNote:
      '"One if by land, two if by sea." The signal alerted riders in Charlestown that the British were crossing the Charles River, initiating the alarm system that brought thousands of militiamen to the roads.',
    displayOrder: 12,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'copp-hill-burying-ground',
    name: 'Copp\'s Hill Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Second oldest cemetery in Boston (1659). Contains graves of notable colonists and offers views of Charlestown where the Battle of Bunker Hill took place.',
    lat: 42.3668,
    lng: -71.0555,
    address: 'Hull Street, Boston, MA 02113',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground; steep in places.',
    parkingNotes: 'North End street parking.',
    amenities: [],
    historicalNote:
      'British soldiers used gravestones for target practice; musket ball marks remain visible on some stones. From here, the British directed artillery fire during the Battle of Bunker Hill.',
    displayOrder: 13,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'uss-constitution',
    name: 'USS Constitution',
    placeType: 'MUSEUM',
    description:
      'The world\'s oldest commissioned warship still afloat (launched 1797). "Old Ironsides" earned her nickname in the War of 1812 but represents the naval power the Revolution made possible.',
    lat: 42.3724,
    lng: -71.0566,
    address: 'Building 5, Charlestown Navy Yard, Boston, MA 02129',
    hours: 'Tue-Sun 10am-4pm (extended summer hours)',
    admission: 'Free; donations appreciated',
    website: 'https://www.nps.gov/bost/learn/historyculture/ussc.htm',
    phone: '(617) 242-5601',
    accessibilityNotes: 'Ship deck has limited accessibility.',
    parkingNotes: 'Navy Yard parking.',
    amenities: ['restrooms', 'museum', 'tours'],
    historicalNote:
      'The Constitution was built with funds authorized by Congress in 1794. Her construction in Boston\'s shipyards connected the new nation\'s defense to the city\'s maritime tradition.',
    displayOrder: 14,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'bunker-hill-monument',
    name: 'Bunker Hill Monument',
    placeType: 'MONUMENT',
    description:
      'Granite obelisk (221 feet) commemorating the Battle of Bunker Hill on June 17, 1775. The battle was technically fought on Breed\'s Hill, where the monument stands.',
    lat: 42.3763,
    lng: -71.0608,
    address: 'Monument Square, Charlestown, MA 02129',
    hours: 'Grounds open daily; monument climbing seasonal',
    admission: 'Free',
    website: 'https://www.nps.gov/bost/learn/historyculture/bhm.htm',
    phone: '(617) 242-5641',
    accessibilityNotes: '294 steps to top; no elevator.',
    parkingNotes: 'Street parking in Charlestown.',
    amenities: ['restrooms', 'ranger talks'],
    historicalNote:
      'Though the British won the battle, they suffered devastating casualties—over 1,000 killed or wounded. The colonial defenders proved they could stand against professional soldiers.',
    displayOrder: 15,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },

  // ADDITIONAL REVOLUTIONARY SITES
  {
    id: 'griffin-wharf-tea-party',
    name: 'Boston Tea Party Ships & Museum',
    placeType: 'MUSEUM',
    description:
      'Interactive museum near the site of Griffin\'s Wharf where the Boston Tea Party occurred on December 16, 1773. Features replica ships and immersive exhibits.',
    lat: 42.3522,
    lng: -71.0512,
    address: '306 Congress Street, Boston, MA 02210',
    hours: 'Daily 10am-5pm',
    admission: '$32 adults, $30 seniors, $23 children',
    website: 'https://www.bostonteapartyship.com',
    phone: '(617) 338-1773',
    accessibilityNotes: 'Accessible; some ship areas have steps.',
    parkingNotes: 'Seaport garages.',
    amenities: ['restrooms', 'gift shop', 'tea room', 'exhibits'],
    historicalNote:
      'The original wharf no longer exists; the harbor shoreline has changed dramatically. The museum recreates the event through theatrical presentations and allows visitors to throw tea into the harbor.',
    displayOrder: 16,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'long-wharf',
    name: 'Long Wharf',
    placeType: 'LANDMARK',
    description:
      'Historic wharf extending into Boston Harbor since 1710. British troops embarked and disembarked here; the wharf was central to colonial trade and the events leading to revolution.',
    lat: 42.3596,
    lng: -71.0485,
    address: 'Long Wharf, Boston, MA 02110',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Accessible boardwalk.',
    parkingNotes: 'Harbor garage.',
    amenities: ['restaurants', 'ferry terminal'],
    historicalNote:
      'British ships anchored at Long Wharf during the occupation. When the British evacuated on March 17, 1776, their fleet departed from the harbor visible from this spot.',
    displayOrder: 17,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'dorchester-heights',
    name: 'Dorchester Heights',
    placeType: 'MONUMENT',
    description:
      'The position where Henry Knox\'s artillery overlooked Boston Harbor. When colonial forces fortified this hill overnight on March 4-5, 1776, the British position became untenable.',
    lat: 42.3318,
    lng: -71.0457,
    address: 'Thomas Park, South Boston, MA 02127',
    hours: 'Grounds open daily; monument interior closed',
    admission: 'Free',
    website: 'https://www.nps.gov/bost/learn/historyculture/dh.htm',
    phone: null,
    accessibilityNotes: 'Steep hill; paths available.',
    parkingNotes: 'Street parking.',
    amenities: ['park benches'],
    historicalNote:
      'Knox\'s artillery, dragged overland from Fort Ticonderoga, gave Washington the firepower to threaten the British fleet. Faced with bombardment from heights they couldn\'t assault, the British evacuated Boston.',
    displayOrder: 18,
    featured: true,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'green-dragon-tavern-site',
    name: 'Green Dragon Tavern Site',
    placeType: 'LANDMARK',
    description:
      'Marker and modern establishment near the location of the colonial tavern where Sons of Liberty met to plan resistance, including the Boston Tea Party.',
    lat: 42.3621,
    lng: -71.0549,
    address: '11 Marshall Street, Boston, MA 02108',
    hours: 'Modern tavern hours vary',
    admission: 'Free (exterior)',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'The original Green Dragon was demolished in 1854. It was known as the "Headquarters of the Revolution" where Samuel Adams, Paul Revere, and others gathered to organize resistance.',
    displayOrder: 19,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'liberty-tree-site',
    name: 'Liberty Tree Site',
    placeType: 'MONUMENT',
    description:
      'Plaque marking the location of the great elm tree where colonists hanged effigies of British officials and gathered to protest. The original tree was cut down by Loyalists in 1775.',
    lat: 42.3518,
    lng: -71.0629,
    address: 'Corner of Washington and Essex Streets, Boston, MA 02111',
    hours: 'Always visible',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'The Liberty Tree became a symbol of colonial resistance throughout the colonies. British soldiers hated it so intensely that they cut it down for firewood.',
    displayOrder: 20,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'province-house-site',
    name: 'Province House Site',
    placeType: 'LANDMARK',
    description:
      'Location of the royal governor\'s mansion from 1716 to 1776. The building was demolished in 1922; only markers remain.',
    lat: 42.3561,
    lng: -71.0606,
    address: 'Near 333 Washington Street, Boston, MA 02108',
    hours: 'Always visible',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'Royal governors including Thomas Hutchinson resided here. After the British evacuation, it served briefly as the state\'s executive mansion.',
    displayOrder: 21,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'south-meeting-house-old',
    name: 'Old South Church (Copley Square)',
    placeType: 'CHURCH',
    description:
      'The congregation that met at Old South Meeting House built this Italian Gothic structure in 1873. It continues the tradition of the congregation founded in 1669.',
    lat: 42.3496,
    lng: -71.0774,
    address: '645 Boylston Street, Boston, MA 02116',
    hours: 'Tours by appointment',
    admission: 'Free; donations appreciated',
    website: 'https://www.oldsouth.org',
    phone: '(617) 536-1970',
    accessibilityNotes: 'Accessible entrance.',
    parkingNotes: 'Copley Place garage.',
    amenities: ['tours'],
    historicalNote:
      'While this building is post-Revolutionary, the congregation\'s direct link to the Tea Party debates makes it part of the continuous story of Boston\'s revolutionary heritage.',
    displayOrder: 22,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'revere-mall',
    name: 'Paul Revere Mall (Prado)',
    placeType: 'LANDMARK',
    description:
      'Tree-lined plaza connecting Hanover Street to Old North Church. Features an equestrian statue of Paul Revere by Cyrus Dallin (1940).',
    lat: 42.3649,
    lng: -71.0545,
    address: 'Hanover Street, Boston, MA 02113',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Accessible paths.',
    parkingNotes: 'North End garages.',
    amenities: ['benches'],
    historicalNote:
      'The bronze plaques along the walls commemorate notable North Enders and events. The mall provides the classic view of Old North Church\'s steeple.',
    displayOrder: 23,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'ebenezer-hancock-house',
    name: 'Ebenezer Hancock House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'One of the oldest brick buildings in Boston (1767). Home of John Hancock\'s uncle, deputy paymaster of the Continental Army.',
    lat: 42.3595,
    lng: -71.0548,
    address: '10 Marshall Street, Boston, MA 02108',
    hours: 'Exterior viewable',
    admission: 'Free (exterior)',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level viewing.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'The building survived urban development that destroyed much of colonial Boston. It represents the prosperous merchant class that funded and supported the Revolution.',
    displayOrder: 24,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },

  // MUSEUMS
  {
    id: 'boston-museum-african-american-history',
    name: 'Museum of African American History',
    placeType: 'MUSEUM',
    description:
      'Museum dedicated to preserving and interpreting Black heritage in New England from the colonial era through the 19th century, including the role of Black soldiers in the Revolution.',
    lat: 42.3583,
    lng: -71.0682,
    address: '46 Joy Street, Boston, MA 02114',
    hours: 'Tue-Sat 10am-4pm',
    admission: '$10 adults, $8 seniors/students',
    website: 'https://www.maah.org',
    phone: '(617) 725-0022',
    accessibilityNotes: 'Limited accessibility; historic buildings.',
    parkingNotes: 'Boston Common Garage.',
    amenities: ['exhibits', 'tours'],
    historicalNote:
      'The museum includes the African Meeting House, the oldest Black church edifice in America. Black Bostonians served in the Revolution, and some like Crispus Attucks became martyrs to the cause.',
    displayOrder: 25,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'freedom-trail-foundation',
    name: 'Freedom Trail Foundation Visitor Center',
    placeType: 'MUSEUM',
    description:
      'Starting point for guided Freedom Trail tours. Provides orientation, maps, and historical context for the 2.5-mile walking trail.',
    lat: 42.3554,
    lng: -71.0623,
    address: 'Boston Common Visitor Center, 139 Tremont Street, Boston, MA 02111',
    hours: 'Daily 8:30am-5pm',
    admission: 'Center free; guided tours vary',
    website: 'https://www.thefreedomtrail.org',
    phone: '(617) 357-8300',
    accessibilityNotes: 'Fully accessible.',
    parkingNotes: 'Boston Common Garage.',
    amenities: ['restrooms', 'gift shop', 'tour bookings'],
    historicalNote:
      'The Freedom Trail was established in 1951 to connect sixteen Revolutionary-era sites. It remains one of America\'s most popular historical walking tours.',
    displayOrder: 26,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },

  // ADDITIONAL SITES
  {
    id: 'central-burying-ground',
    name: 'Central Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Cemetery on Boston Common established in 1756. Contains graves of British soldiers and lesser-known colonists.',
    lat: 42.3535,
    lng: -71.0652,
    address: 'Boston Common, Boylston Street entrance, Boston, MA 02116',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground.',
    parkingNotes: 'Boston Common Garage.',
    amenities: [],
    historicalNote:
      'Unlike Granary and King\'s Chapel, this cemetery has fewer famous occupants but represents the broader population of colonial and Revolutionary-era Boston.',
    displayOrder: 27,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'boston-athenaeum',
    name: 'Boston Athenaeum',
    placeType: 'MUSEUM',
    description:
      'Independent library founded in 1807, housing rare books, art, and historical collections including Revolutionary-era materials.',
    lat: 42.3579,
    lng: -71.0627,
    address: '10 1/2 Beacon Street, Boston, MA 02108',
    hours: 'Mon-Sat 9am-5pm',
    admission: 'Free public areas; member access to collections',
    website: 'https://www.bostonathenaeum.org',
    phone: '(617) 227-0270',
    accessibilityNotes: 'First floor accessible.',
    parkingNotes: 'Boston Common Garage.',
    amenities: ['exhibits', 'reading rooms'],
    historicalNote:
      'The Athenaeum\'s collections include George Washington\'s personal library and extensive 18th-century materials related to the Revolution.',
    displayOrder: 28,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'castle-island',
    name: 'Castle Island / Fort Independence',
    placeType: 'BATTLEFIELD',
    description:
      'Fortified island in Boston Harbor with military history dating to 1634. During the Revolution, the British held the position before evacuating.',
    lat: 42.3380,
    lng: -71.0115,
    address: '2010 William J Day Boulevard, Boston, MA 02127',
    hours: 'Fort tours summer weekends; grounds open daily',
    admission: 'Free',
    website: 'https://www.mass.gov/locations/castle-island-fort-independence',
    phone: null,
    accessibilityNotes: 'Paths mostly accessible; fort interior has stairs.',
    parkingNotes: 'Free parking lot.',
    amenities: ['walking paths', 'restrooms', 'beach'],
    historicalNote:
      'The island has been fortified since the earliest colonial days. The current granite fort (1851) replaced earlier structures. Washington\'s forces took control after the British evacuation.',
    displayOrder: 29,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'north-end',
    name: 'North End Historic District',
    placeType: 'LANDMARK',
    description:
      'Boston\'s oldest residential neighborhood, home to Paul Revere, the Old North Church, and a dense concentration of colonial-era history. Now known for Italian-American heritage.',
    lat: 42.3650,
    lng: -71.0545,
    address: 'North End, Boston, MA 02113',
    hours: 'Public neighborhood',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Historic narrow streets; generally accessible.',
    parkingNotes: 'Limited street parking; garages available.',
    amenities: ['restaurants', 'cafes', 'historic sites'],
    historicalNote:
      'The tight streets of the North End have changed remarkably little in layout since the 18th century. Walking here offers a sense of the neighborhood Paul Revere knew.',
    displayOrder: 30,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'hutchinson-house-site',
    name: 'Thomas Hutchinson House Site',
    placeType: 'LANDMARK',
    description:
      'Marker near where Governor Thomas Hutchinson\'s mansion stood before a mob destroyed it in 1765 during the Stamp Act protests.',
    lat: 42.3621,
    lng: -71.0550,
    address: 'Near Hanover Street, North End, Boston, MA 02113',
    hours: 'Always visible',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-level.',
    parkingNotes: 'North End parking.',
    amenities: [],
    historicalNote:
      'Hutchinson, though a native Bostonian, enforced British policies and became hated by patriots. The destruction of his home, including his invaluable historical manuscript collection, marked an escalation in resistance.',
    displayOrder: 31,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'quincy-market',
    name: 'Quincy Market',
    placeType: 'LANDMARK',
    description:
      'Historic market building (1826) adjacent to Faneuil Hall. While post-Revolutionary, it extended the market tradition that made Faneuil Hall a gathering place.',
    lat: 42.3601,
    lng: -71.0551,
    address: 'Quincy Market, Boston, MA 02109',
    hours: 'Mon-Sat 10am-9pm, Sun 11am-7pm',
    admission: 'Free',
    website: 'https://www.faneuilhallmarketplace.com',
    phone: '(617) 523-1300',
    accessibilityNotes: 'Fully accessible.',
    parkingNotes: 'Quincy Market garage.',
    amenities: ['restrooms', 'food stalls', 'shops'],
    historicalNote:
      'The granite market building was designed by Alexander Parris. It continues Boston\'s tradition as a commercial port and gathering place.',
    displayOrder: 32,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'adams-courthouse',
    name: 'John Adams Courthouse',
    placeType: 'GOVERNMENT',
    description:
      'Historic courthouse (1894) named for John Adams, who defended the British soldiers accused in the Boston Massacre—a principled stance that defined his career.',
    lat: 42.3621,
    lng: -71.0594,
    address: 'Pemberton Square, Boston, MA 02108',
    hours: 'Court business hours',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Accessible.',
    parkingNotes: 'Nearby garages.',
    amenities: [],
    historicalNote:
      'Adams successfully argued that the soldiers acted in self-defense, securing acquittals for most. His commitment to rule of law, even for unpopular clients, influenced American legal tradition.',
    displayOrder: 33,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'boston-harbor-islands',
    name: 'Boston Harbor Islands',
    placeType: 'LANDMARK',
    description:
      'Archipelago of islands that witnessed British naval operations during the siege of Boston. Several islands have Colonial and Revolutionary-era fortifications.',
    lat: 42.3250,
    lng: -70.9600,
    address: 'Boston Harbor Islands, Boston, MA',
    hours: 'Seasonal ferry service; check schedule',
    admission: 'Ferry fees apply; island access free',
    website: 'https://www.bostonharborislands.org',
    phone: '(617) 223-8666',
    accessibilityNotes: 'Varies by island.',
    parkingNotes: 'Park at Long Wharf.',
    amenities: ['ferries', 'camping on some islands', 'hiking'],
    historicalNote:
      'The harbor islands controlled access to Boston. British ships anchored among them during the siege. Fort Warren on Georges Island, though later, is a related military site.',
    displayOrder: 34,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
  {
    id: 'bostonian-society',
    name: 'Bostonian Society / Old State House Museum',
    placeType: 'MUSEUM',
    description:
      'The historical society that preserves and interprets the Old State House and Boston\'s Revolutionary heritage.',
    lat: 42.3588,
    lng: -71.0577,
    address: '206 Washington Street, Boston, MA 02109',
    hours: 'Daily 10am-5pm',
    admission: 'Included with Old State House',
    website: 'https://www.revolutionaryspaces.org',
    phone: '(617) 720-1713',
    accessibilityNotes: 'See Old State House.',
    parkingNotes: 'Nearby garages.',
    amenities: ['exhibits', 'research library'],
    historicalNote:
      'Now merged with Revolutionary Spaces, the organization has preserved Boston\'s Revolutionary landmarks since 1881 and maintains extensive archives and artifact collections.',
    displayOrder: 35,
    featured: false,
    town: { connect: { id: 'us-ma-boston' } },
  },
];
