// MODEL: Claude Opus (historical content and descriptions)
// MODEL: Claude Sonnet (data structure)
// Concord, MA - Places seed data (25 historic sites)

import { Prisma } from '@prisma/client';

/**
 * Places in Concord, Massachusetts
 *
 * Concord's Revolutionary significance centers on the North Bridge fight
 * on April 19, 1775, but the town's deeper history includes its role as
 * a center of colonial resistance, the Provincial Congress, and the hiding
 * of military supplies. Many sites also connect to Concord's later literary
 * golden age, though Revolutionary content takes precedence here.
 */

export const concordPlaces: Prisma.PlaceCreateInput[] = [
  // BATTLEFIELDS & COMBAT SITES
  {
    id: 'north-bridge',
    name: 'North Bridge',
    placeType: 'BATTLEFIELD',
    description:
      'The wooden bridge where colonial minutemen engaged British regulars on the morning of April 19, 1775. Often called the site of "the shot heard round the world," though that phrase more accurately describes the day\'s events collectively.',
    lat: 42.4680,
    lng: -71.3508,
    address: '174 Liberty Street, Concord, MA 01742',
    hours: 'Grounds open daily, dawn to dusk',
    admission: 'Free',
    website: 'https://www.nps.gov/mima/planyourvisit/north-bridge.htm',
    phone: '(978) 369-6993',
    accessibilityNotes:
      'Paved path from parking area to bridge. Bridge itself is wooden with slight incline.',
    parkingNotes: 'Parking lot at North Bridge Visitor Center.',
    amenities: ['restrooms', 'visitor center', 'ranger programs'],
    historicalNote:
      'The current bridge is a reconstruction; several versions have stood here since 1775. British soldiers fired first, killing two minutemen, before the colonials returned fire. Three British soldiers died. The engagement lasted perhaps three minutes.',
    displayOrder: 1,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'minute-man-statue-concord',
    name: 'Minute Man Statue (Daniel Chester French)',
    placeType: 'MONUMENT',
    description:
      'Bronze statue by Daniel Chester French depicting a farmer-soldier leaving his plow. Dedicated in 1875 for the centennial of the battle, it became an iconic symbol of the American minuteman.',
    lat: 42.4678,
    lng: -71.3512,
    address: 'North Bridge, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Accessible via paved path from parking.',
    parkingNotes: 'Use North Bridge parking lot.',
    amenities: [],
    historicalNote:
      'French was only 23 when he created this sculpture. Ralph Waldo Emerson\'s "Concord Hymn" is inscribed on the base: "By the rude bridge that arched the flood, / Their flag to April\'s breeze unfurled..."',
    displayOrder: 2,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'british-soldiers-grave',
    name: 'Grave of the British Soldiers',
    placeType: 'CEMETERY',
    description:
      'Simple grave marker for the two British soldiers killed at the North Bridge. Their comrades left them behind during the retreat, and Concord residents buried them.',
    lat: 42.4681,
    lng: -71.3503,
    address: 'North Bridge, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Short walk from main path on grass.',
    parkingNotes: 'Use North Bridge parking lot.',
    amenities: [],
    historicalNote:
      'The inscription, added later, reads in part: "They came three thousand miles and died, to keep the past upon its throne." The sentiment reflects 19th-century reconciliation between former enemies.',
    displayOrder: 3,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // HISTORIC HOUSES
  {
    id: 'old-manse',
    name: 'The Old Manse',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Built in 1770 for Reverend William Emerson, this house overlooks the North Bridge. Emerson watched the battle from here. Later residents included Nathaniel Hawthorne, who wrote "Mosses from an Old Manse" here.',
    lat: 42.4672,
    lng: -71.3501,
    address: '269 Monument Street, Concord, MA 01742',
    hours: 'Mid-April to October: Mon-Sat 10am-5pm, Sun 12pm-5pm',
    admission: '$12 adults, $10 seniors, $6 students',
    website: 'https://thetrustees.org/place/the-old-manse/',
    phone: '(978) 369-3909',
    accessibilityNotes:
      'First floor partially accessible. Upper floors via stairs only.',
    parkingNotes: 'Small lot on Monument Street; overflow at North Bridge lot.',
    amenities: ['guided tours', 'gift shop', 'gardens'],
    historicalNote:
      'Rev. William Emerson was Ralph Waldo Emerson\'s grandfather. The house remained in the Emerson family for nearly two centuries. Both literary and Revolutionary history converge here.',
    displayOrder: 4,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'wright-tavern',
    name: 'Wright Tavern',
    placeType: 'TAVERN',
    description:
      'Colonial tavern that served as headquarters for both sides on April 19, 1775. Minutemen gathered here before the battle; British officers commandeered it afterward.',
    lat: 42.4604,
    lng: -71.3493,
    address: '2 Lexington Road, Concord, MA 01742',
    hours: 'Exterior viewable; interior access limited',
    admission: 'Exterior free; interior by arrangement',
    website: null,
    phone: null,
    accessibilityNotes: 'Historic building; limited accessibility.',
    parkingNotes: 'Street parking in Concord center.',
    amenities: [],
    historicalNote:
      'Major John Buttrick and other militia officers planned their response to the British here. After the skirmish, British officers reportedly demanded food and drink. The building remains one of the best-preserved colonial taverns in Massachusetts.',
    displayOrder: 5,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'colonel-barrett-farm',
    name: 'Colonel James Barrett Farm',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Home and farm of Colonel James Barrett, the senior militia commander. British soldiers marched here on April 19 searching for hidden military supplies, but found little—the colonists had moved most stores.',
    lat: 42.4794,
    lng: -71.3778,
    address: '448 Barrett\'s Mill Road, Concord, MA 01742',
    hours: 'Grounds open; house privately owned',
    admission: 'Free (exterior only)',
    website: null,
    phone: null,
    accessibilityNotes: 'Rural road; limited facilities.',
    parkingNotes: 'Limited roadside parking.',
    amenities: [],
    historicalNote:
      'The British search party was delayed by a swollen stream and suspicious locals. By the time they reached the farm, most supplies had been hidden in nearby woods and fields. Barrett\'s wife reportedly fed the British officers breakfast.',
    displayOrder: 6,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'meriam-house',
    name: 'Meriam\'s Corner',
    placeType: 'LANDMARK',
    description:
      'The farmhouse and intersection where intense fighting began during the British retreat. Minutemen from surrounding towns converged here, and casualties on both sides mounted.',
    lat: 42.4545,
    lng: -71.3290,
    address: '34 Old Bedford Road, Concord, MA 01742',
    hours: 'Open daily (exterior)',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: null,
    accessibilityNotes: 'Roadside viewing; limited accessibility.',
    parkingNotes: 'Small pulloff area.',
    amenities: ['historical markers'],
    historicalNote:
      'The Meriam family watched the British column pass in the morning. By afternoon, hundreds of militiamen had gathered, and the running battle that would continue to Lexington began in earnest.',
    displayOrder: 7,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'concord-colonial-inn',
    name: 'Colonial Inn',
    placeType: 'TAVERN',
    description:
      'Historic inn incorporating structures dating to 1716. One wing served as a storehouse for colonial military supplies in early 1775.',
    lat: 42.4605,
    lng: -71.3490,
    address: '48 Monument Square, Concord, MA 01742',
    hours: 'Open daily as operating inn',
    admission: 'Free to enter public areas',
    website: 'https://www.concordscolonialinn.com',
    phone: '(978) 369-9200',
    accessibilityNotes: 'Main floor accessible.',
    parkingNotes: 'Behind inn and street parking.',
    amenities: ['restaurant', 'lodging', 'bar'],
    historicalNote:
      'The oldest portion of the inn was home to Dr. Timothy Minot, who treated wounded from both sides after the battle. The inn offers a tangible connection to colonial-era hospitality.',
    displayOrder: 8,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // MUSEUMS & VISITOR CENTERS
  {
    id: 'concord-museum',
    name: 'Concord Museum',
    placeType: 'MUSEUM',
    description:
      'Houses one of the finest collections of Revolutionary War artifacts in New England, including one of the two lanterns hung in Old North Church and Paul Revere\'s own account of his ride.',
    lat: 42.4613,
    lng: -71.3439,
    address: '53 Cambridge Turnpike, Concord, MA 01742',
    hours: 'Wed-Sun 10am-4pm; summer hours may extend',
    admission: '$15 adults, $12 seniors, $8 students',
    website: 'https://concordmuseum.org',
    phone: '(978) 369-9763',
    accessibilityNotes: 'Wheelchair accessible; elevator available.',
    parkingNotes: 'Free parking lot.',
    amenities: ['restrooms', 'gift shop', 'exhibits', 'research library'],
    historicalNote:
      'The museum\'s April 19 collection includes powder horns, muskets, and documents from the battle. The "One if by land, two if by sea" lantern is a highlight, connecting Concord to the broader alarm network.',
    displayOrder: 9,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'north-bridge-visitor-center',
    name: 'North Bridge Visitor Center',
    placeType: 'MUSEUM',
    description:
      'National Park Service facility with exhibits on the battle and the road to revolution. Starting point for ranger programs and walking tours.',
    lat: 42.4665,
    lng: -71.3495,
    address: '174 Liberty Street, Concord, MA 01742',
    hours: 'Daily 9am-5pm (April-October); limited winter hours',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: '(978) 369-6993',
    accessibilityNotes: 'Fully accessible.',
    parkingNotes: 'Free parking lot adjacent.',
    amenities: ['restrooms', 'bookstore', 'exhibits', 'ranger desk'],
    historicalNote:
      'Exhibits explore both the military engagement and the political tensions that led to it. The center provides context often missing from battlefield visits alone.',
    displayOrder: 10,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // MONUMENTS & MARKERS
  {
    id: 'obelisk-concord',
    name: 'Battle Monument (Obelisk)',
    placeType: 'MONUMENT',
    description:
      'Granite obelisk on Monument Square marking the center of colonial Concord and commemorating April 19, 1775.',
    lat: 42.4607,
    lng: -71.3492,
    address: 'Monument Square, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Accessible from sidewalk.',
    parkingNotes: 'Street parking in Concord center.',
    amenities: [],
    historicalNote:
      'Erected in 1836, the monument replaced an earlier wooden marker. Its position near Wright Tavern places it at the heart of the colonial town where militia gathered.',
    displayOrder: 11,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'major-buttrick-marker',
    name: 'Major John Buttrick Memorial',
    placeType: 'MONUMENT',
    description:
      'Marker honoring Major Buttrick, who reportedly gave the order "Fire, fellow soldiers! For God\'s sake, fire!" at the North Bridge.',
    lat: 42.4679,
    lng: -71.3509,
    address: 'North Bridge, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Adjacent to main path.',
    parkingNotes: 'Use North Bridge parking.',
    amenities: [],
    historicalNote:
      'The exact words of Buttrick\'s command are debated by historians, but he was clearly the officer who initiated the colonial return fire that marked the first organized American military resistance.',
    displayOrder: 12,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // CEMETERIES
  {
    id: 'old-hill-burying-ground',
    name: 'Old Hill Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Concord\'s oldest cemetery, established in 1635. Final resting place of Revolutionary War veterans and colonial-era settlers.',
    lat: 42.4598,
    lng: -71.3487,
    address: 'Lexington Road, Concord, MA 01742',
    hours: 'Dawn to dusk',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground; steep sections.',
    parkingNotes: 'Street parking nearby.',
    amenities: [],
    historicalNote:
      'Several participants in the April 19 events are buried here. The stones offer a direct connection to the people who witnessed and shaped the Revolution in Concord.',
    displayOrder: 13,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'sleepy-hollow-cemetery',
    name: 'Sleepy Hollow Cemetery',
    placeType: 'CEMETERY',
    description:
      'Historic rural cemetery established in 1855. While primarily known for Author\'s Ridge (Emerson, Thoreau, Hawthorne, Alcott), also contains graves of Revolutionary-era families.',
    lat: 42.4649,
    lng: -71.3416,
    address: '34 Bedford Street, Concord, MA 01742',
    hours: 'Daily 7am-dusk',
    admission: 'Free',
    website: 'https://www.concordma.gov/1004/Sleepy-Hollow-Cemetery',
    phone: '(978) 318-3233',
    accessibilityNotes: 'Hilly terrain; some paths paved.',
    parkingNotes: 'Parking inside cemetery.',
    amenities: ['walking paths', 'historical markers'],
    historicalNote:
      'Though established after the Revolution, the cemetery contains reinterred remains and markers for earlier families. Its proximity to battle sites and 19th-century literary connections make it a significant stop.',
    displayOrder: 14,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // TRAILS
  {
    id: 'battle-road-trail-concord',
    name: 'Battle Road Trail (Concord Section)',
    placeType: 'TRAIL',
    description:
      'The Concord portion of the five-mile trail tracing the route of the British march and retreat. Passes through fields and forests that witnessed the running battle.',
    lat: 42.4570,
    lng: -71.3350,
    address: 'Multiple access points; main at Meriam\'s Corner',
    hours: 'Dawn to dusk',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: null,
    accessibilityNotes: 'Mostly paved; some sections have moderate grades.',
    parkingNotes: 'Parking at various trailheads.',
    amenities: ['benches', 'historical markers'],
    historicalNote:
      'The trail follows the approximate path of the original Battle Road. Interpretive markers explain specific engagement sites and tactical decisions made by both sides.',
    displayOrder: 15,
    featured: true,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // CHURCHES
  {
    id: 'first-parish-concord',
    name: 'First Parish in Concord',
    placeType: 'CHURCH',
    description:
      'Unitarian Universalist congregation with roots in Concord\'s founding. The current meetinghouse dates to 1901 but continues a congregation established in 1636.',
    lat: 42.4606,
    lng: -71.3495,
    address: '20 Lexington Road, Concord, MA 01742',
    hours: 'Services and events; check schedule',
    admission: 'Free',
    website: 'https://firstparish.org',
    phone: '(978) 369-9602',
    accessibilityNotes: 'Accessible entrance available.',
    parkingNotes: 'Parking behind church.',
    amenities: [],
    historicalNote:
      'The congregation served as the religious and civic heart of colonial Concord. Earlier meetinghouses on this site hosted town meetings where resistance to British policy was debated.',
    displayOrder: 16,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // GOVERNMENT & CIVIC
  {
    id: 'concord-town-house',
    name: 'Concord Town House',
    placeType: 'GOVERNMENT',
    description:
      'Victorian-era town hall (1873) built on the site of earlier civic buildings. Town meetings have occurred in this general location since the colonial era.',
    lat: 42.4603,
    lng: -71.3489,
    address: '22 Monument Square, Concord, MA 01742',
    hours: 'Business hours; town meetings as scheduled',
    admission: 'Free',
    website: 'https://www.concordma.gov',
    phone: '(978) 318-3000',
    accessibilityNotes: 'Main floor accessible.',
    parkingNotes: 'Street parking.',
    amenities: ['restrooms'],
    historicalNote:
      'Colonial town meetings here debated responses to British acts and organized local militia. The tradition of direct democracy continues in the same location.',
    displayOrder: 17,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },

  // ADDITIONAL LANDMARKS
  {
    id: 'provincial-congress-site',
    name: 'Provincial Congress Site',
    placeType: 'LANDMARK',
    description:
      'Marker indicating where the Massachusetts Provincial Congress met in October 1774, effectively establishing a shadow government outside British control.',
    lat: 42.4605,
    lng: -71.3492,
    address: 'Near Wright Tavern, Concord Center',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-side; accessible.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'The Provincial Congress organized militia, stockpiled supplies, and prepared for potential conflict—actions that made Concord a prime target for the British expedition in April 1775.',
    displayOrder: 18,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'elisha-jones-house',
    name: 'Bullet Hole House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Colonial-era house that still bears musket ball damage from April 19, 1775. The name comes from visible bullet holes in the exterior.',
    lat: 42.4610,
    lng: -71.3498,
    address: 'Monument Street, Concord, MA 01742',
    hours: 'Exterior viewable; private residence',
    admission: 'Free (exterior)',
    website: null,
    phone: null,
    accessibilityNotes: 'Viewable from public street.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'The house was caught in crossfire as British soldiers retreated through town. The preserved damage offers tangible evidence of the violence that passed through Concord\'s streets.',
    displayOrder: 19,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'punkatasset-hill',
    name: 'Punkatasset Hill',
    placeType: 'LANDMARK',
    description:
      'The ridge where colonial militiamen gathered on the morning of April 19 before descending to confront the British at the North Bridge.',
    lat: 42.4695,
    lng: -71.3530,
    address: 'Liberty Street, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Hiking terrain; not accessible.',
    parkingNotes: 'Use North Bridge parking.',
    amenities: ['historical markers'],
    historicalNote:
      'From this vantage point, minutemen watched smoke rise from Concord center and believed (incorrectly) that the British were burning the town. This sight prompted their advance toward the bridge.',
    displayOrder: 20,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'egg-rock',
    name: 'Egg Rock',
    placeType: 'LANDMARK',
    description:
      'Glacial boulder at the confluence of the Sudbury and Assabet rivers marking the founding spot of Concord in 1635.',
    lat: 42.4580,
    lng: -71.3555,
    address: 'Near Lowell Road, Concord, MA 01742',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Natural terrain; limited accessibility.',
    parkingNotes: 'Limited roadside parking.',
    amenities: [],
    historicalNote:
      'While predating the Revolution by 140 years, Egg Rock establishes Concord\'s deep roots in colonial Massachusetts history. The town\'s founding generation set patterns of self-governance that persisted to 1775.',
    displayOrder: 21,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'orchard-house',
    name: 'Orchard House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Home of the Alcott family where Louisa May Alcott wrote "Little Women." While primarily a literary site, the Alcotts\' connections to abolition and reform extend Revolutionary ideals.',
    lat: 42.4563,
    lng: -71.3422,
    address: '399 Lexington Road, Concord, MA 01742',
    hours: 'Tours Mon-Sun; check website for times',
    admission: '$14 adults, $12 seniors, $8 students',
    website: 'https://www.louisamayalcott.org',
    phone: '(978) 369-4118',
    accessibilityNotes: 'First floor partially accessible; stairs to upper floors.',
    parkingNotes: 'Free parking lot.',
    amenities: ['guided tours', 'gift shop'],
    historicalNote:
      'Bronson Alcott\'s Transcendentalist philosophy built on Revolutionary ideals of individual liberty. The house connects 1775 to later American reform movements.',
    displayOrder: 22,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'walden-pond',
    name: 'Walden Pond',
    placeType: 'LANDMARK',
    description:
      'The pond where Henry David Thoreau lived from 1845-1847 and wrote "Walden." While post-Revolutionary, Thoreau\'s ideas of civil disobedience extended the spirit of 1775.',
    lat: 42.4385,
    lng: -71.3330,
    address: '915 Walden Street, Concord, MA 01742',
    hours: 'Daily dawn to dusk; parking fees apply',
    admission: '$15 parking (MA residents $8)',
    website: 'https://www.mass.gov/locations/walden-pond-state-reservation',
    phone: '(978) 369-3254',
    accessibilityNotes: 'Beach area accessible; trails vary.',
    parkingNotes: 'State parking lot; fills early on summer weekends.',
    amenities: ['restrooms', 'swimming', 'trails', 'replica cabin'],
    historicalNote:
      'Thoreau\'s essay "Civil Disobedience" argued for individual resistance to unjust laws—a direct philosophical descendant of the minutemen\'s stand against imperial authority.',
    displayOrder: 23,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'emerson-house',
    name: 'Ralph Waldo Emerson House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Home of the essayist and philosopher who wrote the "Concord Hymn" commemorating April 19, 1775. Emerson spent most of his adult life here.',
    lat: 42.4593,
    lng: -71.3458,
    address: '28 Cambridge Turnpike, Concord, MA 01742',
    hours: 'Mid-April to October: Thu-Sun 10am-4:30pm',
    admission: '$12 adults, $8 students',
    website: 'https://www.rwe.org',
    phone: '(978) 369-2236',
    accessibilityNotes: 'First floor accessible with assistance.',
    parkingNotes: 'Street parking; Concord Museum lot nearby.',
    amenities: ['guided tours'],
    historicalNote:
      'Emerson\'s grandfather watched the North Bridge fight from the Old Manse. The "Concord Hymn," written for the 1837 dedication of the Battle Monument, remains the most famous literary response to April 19.',
    displayOrder: 24,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
  {
    id: 'concord-free-public-library',
    name: 'Concord Free Public Library',
    placeType: 'LANDMARK',
    description:
      'One of the first free public libraries in the United States (1873). Houses significant collections relating to Concord\'s Revolutionary and literary history.',
    lat: 42.4606,
    lng: -71.3479,
    address: '129 Main Street, Concord, MA 01742',
    hours: 'Mon-Thu 9am-9pm, Fri-Sat 9am-5pm, Sun 1pm-5pm',
    admission: 'Free',
    website: 'https://concordlibrary.org',
    phone: '(978) 318-3300',
    accessibilityNotes: 'Fully accessible.',
    parkingNotes: 'Public lot behind library.',
    amenities: ['restrooms', 'special collections', 'reading rooms'],
    historicalNote:
      'The library\'s Special Collections include manuscripts, maps, and documents relating to April 19, 1775, and Concord\'s role in the Revolution.',
    displayOrder: 25,
    featured: false,
    town: { connect: { id: 'us-ma-concord' } },
  },
];
