// MODEL: Claude Opus (historical content and descriptions)
// MODEL: Claude Sonnet (data structure)
// Lexington, MA - Places seed data (30 historic sites)

import { Prisma } from '@prisma/client';

/**
 * Places in Lexington, Massachusetts
 *
 * These locations represent the core Revolutionary War sites and supporting
 * historic places that make Lexington a flagship destination. Each place
 * includes visitor-practical information alongside historical context.
 */

export const lexingtonPlaces: Prisma.PlaceCreateInput[] = [
  // BATTLEFIELDS & COMBAT SITES
  {
    id: 'lexington-green',
    name: 'Lexington Battle Green',
    placeType: 'BATTLEFIELD',
    description:
      'The triangular common where the first shots of the American Revolution were fired on April 19, 1775. Approximately 77 colonial militiamen faced 700 British regulars here at dawn.',
    lat: 42.4490,
    lng: -71.2310,
    address: '1625 Massachusetts Ave, Lexington, MA 02420',
    hours: 'Open daily, dawn to dusk',
    admission: 'Free',
    website: 'https://www.lexingtonma.gov/visitors/battle-green',
    phone: null,
    accessibilityNotes:
      'Paved pathways around perimeter. Central grass area may be uneven.',
    parkingNotes: 'Street parking along Massachusetts Ave. Visitor Center lot nearby.',
    amenities: ['benches', 'historical markers', 'monuments'],
    historicalNote:
      'Eight militiamen died here on April 19, 1775. Their names are inscribed on the Revolutionary Monument. The Green itself is largely unchanged since the battle, though surrounding buildings have evolved.',
    displayOrder: 1,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'parker-boulder',
    name: 'Captain Parker Boulder',
    placeType: 'MONUMENT',
    description:
      'Granite boulder marking the approximate line where Captain John Parker\'s militia stood on April 19, 1775. Inscribed with his reported command.',
    lat: 42.4492,
    lng: -71.2308,
    address: 'Battle Green, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Located on grass; accessible via paved path nearby.',
    parkingNotes: 'Same as Battle Green.',
    amenities: [],
    historicalNote:
      'The famous quote "Stand your ground. Don\'t fire unless fired upon, but if they mean to have a war, let it begin here" was added in 1910. Its historical accuracy is debated, but the defiant spirit it captures is well-documented.',
    displayOrder: 2,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'minuteman-statue',
    name: 'Minuteman Statue',
    placeType: 'MONUMENT',
    description:
      'Bronze statue by sculptor Henry Hudson Kitson, depicting a colonial farmer leaving his plow to join the militia. Dedicated in 1900.',
    lat: 42.4493,
    lng: -71.2315,
    address: 'Battle Green, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Paved approach from Massachusetts Ave.',
    parkingNotes: 'Same as Battle Green.',
    amenities: [],
    historicalNote:
      'Kitson\'s statue represents the ideal of the citizen-soldier rather than any specific individual. The same sculptor created the similar (but distinct) Minute Man statue at the North Bridge in Concord.',
    displayOrder: 3,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'revolutionary-monument',
    name: 'Revolutionary Monument',
    placeType: 'MONUMENT',
    description:
      'Obelisk memorial marking the common grave of the militiamen killed on April 19, 1775. The oldest Revolutionary War monument in the United States.',
    lat: 42.4488,
    lng: -71.2312,
    address: 'Battle Green, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Short paved path from street.',
    parkingNotes: 'Same as Battle Green.',
    amenities: [],
    historicalNote:
      'Erected in 1799, this was the first public monument to American Revolution casualties. The remains of seven of the eight fallen militiamen rest beneath it (one was buried in the Old Burying Ground).',
    displayOrder: 4,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // HISTORIC HOUSES
  {
    id: 'hancock-clarke-house',
    name: 'Hancock-Clarke House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Parsonage where Samuel Adams and John Hancock were staying the night before the battle. Paul Revere arrived here around midnight to deliver his warning.',
    lat: 42.4532,
    lng: -71.2353,
    address: '36 Hancock Street, Lexington, MA 02420',
    hours: 'April-October: Mon-Sat 10am-4pm, Sun 12pm-4pm',
    admission: '$10 adults, $5 children, free under 6',
    website: 'https://www.lexingtonhistory.org/hancock-clarke-house',
    phone: '(781) 862-1703',
    accessibilityNotes:
      'First floor accessible. Upper floors via stairs only. Period doorways may be narrow.',
    parkingNotes: 'Limited street parking. Visitor Center lot 0.2 miles.',
    amenities: ['gift shop', 'guided tours'],
    historicalNote:
      'Reverend Jonas Clarke lived here and was a key organizer of resistance. The house contains the drum that William Diamond reportedly beat to summon the militia and other original artifacts.',
    displayOrder: 5,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'munroe-tavern',
    name: 'Munroe Tavern',
    placeType: 'TAVERN',
    description:
      'Served as British headquarters during their retreat from Concord. Earl Percy used this tavern to coordinate his relief column and tend to wounded soldiers.',
    lat: 42.4418,
    lng: -71.2090,
    address: '1332 Massachusetts Ave, Lexington, MA 02420',
    hours: 'April-October: Mon-Sat 10am-4pm, Sun 12pm-4pm',
    admission: '$10 adults, $5 children, free under 6',
    website: 'https://www.lexingtonhistory.org/munroe-tavern',
    phone: '(781) 674-9238',
    accessibilityNotes: 'First floor accessible with assistance. Upper floors via stairs.',
    parkingNotes: 'On-site parking lot.',
    amenities: ['gift shop', 'restrooms', 'guided tours'],
    historicalNote:
      'Tavern keeper William Munroe hid the family silver in the well before fleeing. George Washington dined here in 1789, and the chair he used is still on display.',
    displayOrder: 6,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'buckman-tavern',
    name: 'Buckman Tavern',
    placeType: 'TAVERN',
    description:
      'Where Lexington\'s militiamen gathered and waited through the night before the battle. The front door still bears a bullet hole from the British volley.',
    lat: 42.4486,
    lng: -71.2325,
    address: '1 Bedford Street, Lexington, MA 02420',
    hours: 'April-October: Mon-Sat 10am-4pm, Sun 12pm-4pm',
    admission: '$10 adults, $5 children, free under 6',
    website: 'https://www.lexingtonhistory.org/buckman-tavern',
    phone: '(781) 862-5598',
    accessibilityNotes:
      'First floor accessible. Narrow doorways typical of 18th century construction.',
    parkingNotes: 'Metered parking along Bedford Street. Visitor Center lot nearby.',
    amenities: ['gift shop', 'guided tours'],
    historicalNote:
      'The bullet hole in the front door is one of the most tangible connections to the events of April 19. The tavern\'s tap room looks much as it did when militiamen gathered here in the pre-dawn darkness.',
    displayOrder: 7,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'follen-community-church',
    name: 'First Parish Church',
    placeType: 'CHURCH',
    description:
      'Successor to the original Lexington meeting house that stood near the Green in 1775. The congregation dates to 1692.',
    lat: 42.4487,
    lng: -71.2296,
    address: '7 Harrington Road, Lexington, MA 02421',
    hours: 'Varies; exterior always visible',
    admission: 'Free',
    website: 'https://www.fplex.org',
    phone: '(781) 862-8200',
    accessibilityNotes: 'Building is wheelchair accessible.',
    parkingNotes: 'Small lot; additional street parking.',
    amenities: [],
    historicalNote:
      'The original meeting house stood on the Green and may have been struck by British musket fire. It was replaced in the early 19th century.',
    displayOrder: 8,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'old-burying-ground',
    name: 'Old Burying Ground',
    placeType: 'CEMETERY',
    description:
      'Final resting place of Captain John Parker and other Lexington residents from the colonial era. Established 1690.',
    lat: 42.4479,
    lng: -71.2326,
    address: '9 Harrington Road, Lexington, MA 02420',
    hours: 'Daily, dawn to dusk',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground and grass. Not fully accessible.',
    parkingNotes: 'Street parking on Harrington Road.',
    amenities: [],
    historicalNote:
      'Captain John Parker died of tuberculosis in September 1775, just five months after the battle. His grave is marked with a flag and special monument.',
    displayOrder: 9,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // MUSEUMS & VISITOR CENTERS
  {
    id: 'lexington-visitor-center',
    name: 'Lexington Visitors Center',
    placeType: 'MUSEUM',
    description:
      'Starting point for exploring Lexington\'s historic sites. Offers maps, information, exhibits, and diorama of the battle.',
    lat: 42.4485,
    lng: -71.2307,
    address: '1875 Massachusetts Ave, Lexington, MA 02420',
    hours: 'Daily 9am-5pm (April-November), 10am-4pm (December-March)',
    admission: 'Free',
    website: 'https://www.tourlexington.us',
    phone: '(781) 862-2480',
    accessibilityNotes: 'Fully wheelchair accessible. Accessible restrooms.',
    parkingNotes: 'On-site parking lot. First 2 hours free.',
    amenities: ['restrooms', 'gift shop', 'information desk', 'exhibits'],
    historicalNote:
      'Houses the diorama depicting the moment just before the first shots were fired. Created by the Lexington Historical Society.',
    displayOrder: 10,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'scottish-rite-museum',
    name: 'National Heritage Museum',
    placeType: 'MUSEUM',
    description:
      'Features rotating exhibits on American history, including significant Revolutionary War collections and artifacts.',
    lat: 42.4393,
    lng: -71.2044,
    address: '33 Marrett Road, Lexington, MA 02421',
    hours: 'Wed-Sat 10am-4pm',
    admission: 'Free',
    website: 'https://nationalheritagemuseum.org',
    phone: '(781) 861-6559',
    accessibilityNotes: 'Fully wheelchair accessible.',
    parkingNotes: 'Free on-site parking.',
    amenities: ['restrooms', 'gift shop', 'research library'],
    historicalNote:
      'Though operated by the Scottish Rite of Freemasonry, the museum is open to all and includes excellent exhibits on colonial-era fraternal organizations and their role in the Revolution.',
    displayOrder: 11,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // TRAILS & ROUTES
  {
    id: 'battle-road-trail',
    name: 'Battle Road Trail',
    placeType: 'TRAIL',
    description:
      'Five-mile walking and biking trail following the route of the British march and retreat between Lexington and Concord. Part of Minute Man National Historical Park.',
    lat: 42.4472,
    lng: -71.2613,
    address: 'Multiple access points; main trailhead at North Great Road',
    hours: 'Daily, dawn to dusk',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: '(978) 369-6993',
    accessibilityNotes:
      'Paved for most of its length. Some sections have moderate grades. Wheelchair accessible.',
    parkingNotes: 'Parking at Minute Man Visitor Center and various trailheads.',
    amenities: ['benches', 'historical markers', 'restrooms at visitor center'],
    historicalNote:
      'Follows sections of the original Battle Road where running fights occurred during the British retreat. Stone walls, fields, and forests look much as they did in 1775.',
    displayOrder: 12,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'minuteman-bikeway',
    name: 'Minuteman Commuter Bikeway',
    placeType: 'TRAIL',
    description:
      'Paved rail-trail following the path of a former railroad right-of-way. Connects Lexington to Bedford and Cambridge.',
    lat: 42.4430,
    lng: -71.2249,
    address: 'Multiple access points throughout Lexington',
    hours: 'Daily, dawn to dusk',
    admission: 'Free',
    website: 'https://minutemanbikeway.org',
    phone: null,
    accessibilityNotes: 'Fully paved and accessible. Flat grade.',
    parkingNotes: 'Parking at Lexington Center and several access points.',
    amenities: ['benches', 'bike racks'],
    historicalNote:
      'While the bikeway itself is modern, it passes through landscapes where militiamen mustered on April 19, 1775.',
    displayOrder: 13,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // MONUMENTS & MARKERS (Additional)
  {
    id: 'line-of-minute-men-marker',
    name: 'Line of Minute Men Marker',
    placeType: 'MONUMENT',
    description:
      'Row of stones marking the approximate positions where militiamen stood before the British opened fire.',
    lat: 42.4491,
    lng: -71.2309,
    address: 'Battle Green, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'On grass; visible from paved paths.',
    parkingNotes: 'Same as Battle Green.',
    amenities: [],
    historicalNote:
      'Each stone represents one militiaman. The line helps visitors understand the scale and disposition of Parker\'s small force facing the British column.',
    displayOrder: 14,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'ye-olde-burying-ground-sign',
    name: 'Jonathan Harrington House Site',
    placeType: 'LANDMARK',
    description:
      'Marker at the approximate location where mortally wounded Jonathan Harrington crawled to die at his wife\'s feet.',
    lat: 42.4487,
    lng: -71.2303,
    address: 'Harrington Road, Lexington, MA 02420',
    hours: 'Visible daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-side marker; fully accessible.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'Jonathan Harrington, shot on the Green, managed to crawl to his home across the street before dying. His wife Ruth watched the entire battle unfold.',
    displayOrder: 15,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'british-expedition-marker',
    name: 'British Expedition Marker',
    placeType: 'MONUMENT',
    description:
      'Stone marker indicating where the British column approached the Green on the morning of April 19.',
    lat: 42.4494,
    lng: -71.2295,
    address: 'Massachusetts Ave at Bedford St, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Sidewalk accessible.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'Lt. Col. Francis Smith\'s column of approximately 700 British regulars arrived from this direction after an overnight march from Boston.',
    displayOrder: 16,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // HISTORIC HOUSES (Additional)
  {
    id: 'mason-house',
    name: 'Marrett House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Historic home with connections to Lexington\'s colonial and Revolutionary era families. Managed by Historic New England.',
    lat: 42.4356,
    lng: -71.2003,
    address: '971 Marrett Road, Lexington, MA 02421',
    hours: 'Tours by appointment; check website',
    admission: '$10 adults',
    website: 'https://www.historicnewengland.org/property/marrett-house/',
    phone: '(781) 861-0113',
    accessibilityNotes: 'Limited accessibility; call ahead.',
    parkingNotes: 'On-site parking.',
    amenities: ['guided tours'],
    historicalNote:
      'The Marrett family were prominent Lexington citizens. The house illustrates how colonial families lived before and after the Revolution.',
    displayOrder: 17,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'depot-square',
    name: 'Depot Square',
    placeType: 'LANDMARK',
    description:
      'Historic town center featuring the 1846 railroad depot and surrounding Victorian-era commercial buildings.',
    lat: 42.4472,
    lng: -71.2264,
    address: 'Depot Square, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Public square; sidewalks accessible.',
    parkingNotes: 'Public parking garage nearby.',
    amenities: ['restaurants', 'shops'],
    historicalNote:
      'While the depot is from a later era, this area was part of the colonial town center. The square offers convenient access to shops and restaurants.',
    displayOrder: 18,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // NPS SITES
  {
    id: 'minute-man-visitor-center',
    name: 'Minute Man Visitor Center',
    placeType: 'MUSEUM',
    description:
      'National Park Service visitor center with multimedia presentation "Road to Revolution," exhibits, and park information. Primary orientation point for Minute Man National Historical Park.',
    lat: 42.4472,
    lng: -71.2613,
    address: '250 North Great Road, Lincoln, MA 01773',
    hours: 'Daily 9am-5pm (April-October), 11am-3pm (November-March)',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: '(978) 369-6993',
    accessibilityNotes: 'Fully accessible. Captioned multimedia presentation.',
    parkingNotes: 'Free parking lot.',
    amenities: ['restrooms', 'bookstore', 'exhibits', 'ranger programs'],
    historicalNote:
      'The 25-minute multimedia presentation uses dramatic lighting and a large mural to recreate the events of April 19, 1775. Highly recommended starting point.',
    displayOrder: 19,
    featured: true,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'hartwell-tavern',
    name: 'Hartwell Tavern',
    placeType: 'TAVERN',
    description:
      'Restored 18th-century tavern within Minute Man NHP. Living history demonstrations during summer months.',
    lat: 42.4547,
    lng: -71.2790,
    address: 'Battle Road Trail, Lincoln, MA 01773',
    hours: 'Seasonal; check NPS website',
    admission: 'Free',
    website: 'https://www.nps.gov/mima',
    phone: '(978) 369-6993',
    accessibilityNotes: 'Grounds accessible; historic building has steps.',
    parkingNotes: 'Parking at Battle Road Trail access points.',
    amenities: ['living history programs'],
    historicalNote:
      'Ephraim Hartwell operated this tavern in 1775. Located along Battle Road, it would have witnessed the running battles as the British retreated toward Boston.',
    displayOrder: 20,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // ADDITIONAL LANDMARKS
  {
    id: 'cary-memorial-hall',
    name: 'Cary Memorial Hall',
    placeType: 'GOVERNMENT',
    description:
      'Grand public hall built in 1928. Hosts town meetings and cultural events. Named for Samuel Cary, a Revolutionary War veteran.',
    lat: 42.4475,
    lng: -71.2308,
    address: '1605 Massachusetts Ave, Lexington, MA 02420',
    hours: 'During events and town meetings',
    admission: 'Varies by event',
    website: 'https://www.lexingtonma.gov/cary-memorial-hall',
    phone: '(781) 862-0500',
    accessibilityNotes: 'Accessible entrance on side.',
    parkingNotes: 'Public parking lots nearby.',
    amenities: ['restrooms'],
    historicalNote:
      'While the building is 20th century, it commemorates Revolutionary veterans and hosts the annual Patriots Day ceremonies.',
    displayOrder: 21,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'belfry-hill',
    name: 'Belfry Hill',
    placeType: 'LANDMARK',
    description:
      'Hill where the original alarm bell tower stood. The belfry\'s bell was rung to summon the militia on April 19, 1775.',
    lat: 42.4499,
    lng: -71.2324,
    address: 'Clark Street, Lexington, MA 02420',
    hours: 'Open daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Steep path to hilltop.',
    parkingNotes: 'Street parking on Clark Street.',
    amenities: [],
    historicalNote:
      'The current belfry structure is a reconstruction; the original stood here in 1775. The bell itself is now in the Hancock-Clarke House.',
    displayOrder: 22,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'lexington-depot',
    name: 'Lexington Depot',
    placeType: 'LANDMARK',
    description:
      'Historic 1846 railroad station, now home to the Lexington Historical Society visitor center and gift shop.',
    lat: 42.4472,
    lng: -71.2257,
    address: '13 Depot Square, Lexington, MA 02420',
    hours: 'Mon-Sat 10am-4pm',
    admission: 'Free',
    website: 'https://www.lexingtonhistory.org',
    phone: '(781) 862-1703',
    accessibilityNotes: 'Ground floor accessible.',
    parkingNotes: 'Depot Square parking.',
    amenities: ['gift shop', 'historical society information'],
    historicalNote:
      'The Historical Society maintains this building and coordinates tours of the three historic houses (Hancock-Clarke, Munroe Tavern, Buckman Tavern).',
    displayOrder: 23,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },

  // AREAS OF INTEREST
  {
    id: 'massachusetts-avenue-historic',
    name: 'Massachusetts Avenue Historic District',
    placeType: 'LANDMARK',
    description:
      'The main street of Lexington, following the approximate route of the 1775 road. Colonial, Federal, and Victorian buildings line this commercial corridor.',
    lat: 42.4480,
    lng: -71.2310,
    address: 'Massachusetts Avenue, Lexington, MA',
    hours: 'Public street; always accessible',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Sidewalks throughout.',
    parkingNotes: 'Metered street parking and public lots.',
    amenities: ['restaurants', 'shops'],
    historicalNote:
      'This was the road the British marched along en route to Concord. Many buildings date to the 18th and 19th centuries.',
    displayOrder: 24,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'tower-park',
    name: 'Tower Park',
    placeType: 'LANDMARK',
    description:
      'Small park featuring a stone tower built in 1861 as a water standpipe. Offers views of the surrounding area.',
    lat: 42.4421,
    lng: -71.2365,
    address: 'Tower Street, Lexington, MA 02420',
    hours: 'Dawn to dusk',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Park paths; tower interior not accessible.',
    parkingNotes: 'Street parking.',
    amenities: ['walking paths'],
    historicalNote:
      'While post-Revolutionary, the park provides a vantage point to understand Lexington\'s geography and the terrain militiamen would have known.',
    displayOrder: 25,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'muzzey-house-site',
    name: 'Isaac Muzzey House Site',
    placeType: 'LANDMARK',
    description:
      'Marker at the approximate location of the home of Isaac Muzzey, one of the eight militiamen killed on April 19, 1775.',
    lat: 42.4483,
    lng: -71.2315,
    address: 'Massachusetts Avenue, Lexington, MA 02420',
    hours: 'Visible daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Street-side; accessible.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'Isaac Muzzey was 67 years old when he stood with the militia. The original house no longer stands, but this marker preserves his memory.',
    displayOrder: 26,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'ye-olde-burying-ground-munroe',
    name: 'Robert Munroe Gravestone',
    placeType: 'MONUMENT',
    description:
      'Grave marker for Robert Munroe, a veteran of the French and Indian War, killed at age 64 on Lexington Green.',
    lat: 42.4479,
    lng: -71.2327,
    address: 'Old Burying Ground, Lexington, MA 02420',
    hours: 'Dawn to dusk',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Uneven ground in cemetery.',
    parkingNotes: 'Street parking on Harrington Road.',
    amenities: [],
    historicalNote:
      'Munroe had fought alongside the British in the previous war. His gravestone notes he was "killed by the Troops of George III."',
    displayOrder: 27,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'the-liberty-ride',
    name: 'Liberty Ride Trolley Tour',
    placeType: 'LANDMARK',
    description:
      'Narrated trolley tour connecting major historic sites in Lexington and Concord. Seasonal operation.',
    lat: 42.4485,
    lng: -71.2307,
    address: 'Departs from Lexington Visitors Center',
    hours: 'Seasonal; check website for schedule',
    admission: '$28 adults, $12 children',
    website: 'https://www.libertyride.us',
    phone: '(781) 862-0500',
    accessibilityNotes: 'Trolley has limited accessibility; call ahead.',
    parkingNotes: 'Park at Visitor Center.',
    amenities: ['narrated tour'],
    historicalNote:
      'The 90-minute tour covers the events of April 19, 1775, traveling the route between Lexington and Concord with stops at key sites.',
    displayOrder: 28,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'sanderson-house-site',
    name: 'Sanderson House Site',
    placeType: 'LANDMARK',
    description:
      'Site where several militiamen gathered before proceeding to the Green. The Sanderson family were active participants in the alarm.',
    lat: 42.4476,
    lng: -71.2335,
    address: 'Bedford Street, Lexington, MA 02420',
    hours: 'Street-side; visible daily',
    admission: 'Free',
    website: null,
    phone: null,
    accessibilityNotes: 'Sidewalk accessible.',
    parkingNotes: 'Street parking.',
    amenities: [],
    historicalNote:
      'Elijah Sanderson was one of the men captured by the British patrol that also captured Paul Revere. He was later released.',
    displayOrder: 29,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
  {
    id: 'patriots-day-parade-route',
    name: 'Patriots Day Parade Route',
    placeType: 'LANDMARK',
    description:
      'The annual Patriots Day parade follows streets through Lexington center, commemorating the events of April 19 with reenactors, bands, and civic organizations.',
    lat: 42.4480,
    lng: -71.2310,
    address: 'Massachusetts Avenue, Lexington Center',
    hours: 'Third Monday of April; parade typically 2:00 PM',
    admission: 'Free to watch',
    website: 'https://lexington250.org',
    phone: null,
    accessibilityNotes: 'Sidewalk viewing; accessible.',
    parkingNotes: 'Arrive early; parking fills quickly on Patriots Day.',
    amenities: [],
    historicalNote:
      'The dawn reenactment on the Green and the afternoon parade are the centerpieces of Lexington\'s Patriots Day celebration, held annually since the 19th century.',
    displayOrder: 30,
    featured: false,
    town: { connect: { id: 'us-ma-lexington' } },
  },
];
