// MODEL: Claude Sonnet
import { Prisma } from '@prisma/client';

/**
 * Salem, Massachusetts - Places
 *
 * Salem's Revolutionary significance centers on its maritime economy.
 * The town's merchant fleet converted to privateering during the war,
 * capturing over 450 British vessels — more than any other American port.
 * Earlier, Salem was a flashpoint for resistance: the 1774 confrontation
 * over military stores preceded Lexington and Concord by months.
 */

export const salemPlaces: Prisma.PlaceCreateInput[] = [
  {
    id: 'salem-peabody-essex-museum',
    name: 'Peabody Essex Museum',
    placeType: 'MUSEUM',
    description:
      'One of the oldest continuously operating museums in America, founded in 1799 by Salem sea captains. The maritime collections document the port\'s global trade networks and wartime privateering economy. Holdings include logbooks, navigational instruments, and captured ship inventories from the Revolutionary period.',
    historicalNote:
      'Founded as the East India Marine Society, the museum\'s early members were required to have sailed beyond the Cape of Good Hope or Cape Horn. Many were former privateers.',
    address: '161 Essex Street, Salem, MA 01970',
    website: 'https://www.pem.org/',
    phone: '(978) 745-9500',
    hours: 'Tue-Sun 10am-5pm',
    admission: '$20 adults, free for Salem residents',
    featured: true,
    displayOrder: 1,
    amenities: ['Gift shop', 'Cafe', 'Restrooms', 'Wheelchair accessible', 'Audio guides'],
    accessibilityNotes: 'Fully accessible with elevators to all floors',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-custom-house',
    name: 'Custom House',
    placeType: 'LANDMARK',
    description:
      'Federal-era customs office built in 1819 on the site of earlier customs operations. Salem\'s pre-war customs revenue was among the highest in the colonies, making it a target for British trade enforcement. The building is part of the Salem Maritime National Historic Site.',
    historicalNote:
      'Nathaniel Hawthorne worked here as a customs surveyor from 1846-1849, drawing on Salem\'s maritime past for his fiction.',
    address: '178 Derby Street, Salem, MA 01970',
    website: 'https://www.nps.gov/sama/',
    hours: 'Daily 9am-5pm (seasonal)',
    admission: 'Free (NPS)',
    featured: true,
    displayOrder: 2,
    amenities: ['Ranger talks', 'Historic exhibits', 'Restrooms'],
    accessibilityNotes: 'First floor accessible; upper floors via stairs',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-derby-wharf',
    name: 'Derby Wharf',
    placeType: 'LANDMARK',
    description:
      'A half-mile stone wharf extending into Salem Harbor, built by the Derby family beginning in the 1760s. Elias Hasket Derby outfitted privateers from this wharf during the Revolution, and his ships captured British merchant vessels throughout the war. The wharf is now part of the Salem Maritime National Historic Site.',
    historicalNote:
      'Elias Hasket Derby is sometimes called America\'s first millionaire. His fortune derived from wartime privateering and postwar China trade.',
    address: 'Derby Street, Salem, MA 01970',
    lat: 42.5185,
    lng: -70.8835,
    website: 'https://www.nps.gov/sama/',
    hours: 'Open daily, dawn to dusk',
    admission: 'Free',
    featured: true,
    displayOrder: 3,
    amenities: ['Walking path', 'Harbor views', 'Historic markers'],
    accessibilityNotes: 'Paved surface but uneven in sections near the end',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-house-seven-gables',
    name: 'The House of the Seven Gables',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Built in 1668 for Captain John Turner, this is the oldest surviving timber-frame mansion in New England. The house passed through merchant families whose fortunes rose and fell with Salem\'s maritime economy. Nathaniel Hawthorne\'s 1851 novel brought the house national attention.',
    historicalNote:
      'The Turner family\'s shipping interests connected them to the pre-Revolutionary trade disputes that shaped Salem\'s politics. The house survived because later owners preserved it rather than demolishing for development.',
    address: '115 Derby Street, Salem, MA 01970',
    website: 'https://www.7gables.org/',
    phone: '(978) 744-0991',
    hours: 'Daily 10am-5pm (seasonal hours vary)',
    admission: '$18 adults',
    featured: true,
    displayOrder: 4,
    amenities: ['Guided tours', 'Museum shop', 'Gardens', 'Restrooms'],
    accessibilityNotes: 'Limited accessibility in historic house; gardens accessible',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-maritime-nhs',
    name: 'Salem Maritime National Historic Site',
    placeType: 'MUSEUM',
    description:
      'The first National Historic Site in the United States, designated in 1938. The site preserves twelve historic structures and approximately ten acres of land along Salem\'s waterfront. It documents the port\'s role in colonial trade, Revolutionary privateering, and the early republic\'s global commerce.',
    address: '160 Derby Street, Salem, MA 01970',
    website: 'https://www.nps.gov/sama/',
    phone: '(978) 740-1650',
    hours: 'Daily 9am-5pm',
    admission: 'Free',
    featured: true,
    displayOrder: 5,
    amenities: ['Visitor center', 'Ranger-led tours', 'Film', 'Restrooms', 'Bookstore'],
    accessibilityNotes: 'Visitor center fully accessible; some historic buildings have limited access',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-old-town-hall',
    name: 'Old Town Hall',
    placeType: 'GOVERNMENT',
    description:
      'Built in 1816 in Federal style, this building replaced earlier meetinghouses where Salem residents debated Revolutionary-era politics. The ground floor housed a market, while the upper floor served as a civic gathering space. Now used for public events and exhibits.',
    address: '32 Derby Square, Salem, MA 01970',
    hours: 'Varies by event',
    admission: 'Free (public building)',
    featured: true,
    displayOrder: 6,
    amenities: ['Event space', 'Historic architecture'],
    accessibilityNotes: 'Ground floor accessible; upper floor via stairs',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-common',
    name: 'Salem Common',
    placeType: 'LANDMARK',
    description:
      'An 8.5-acre public park that served as militia training ground before and during the Revolution. Colonial troops mustered here, and the common hosted public gatherings where residents debated resistance to British policies. The surrounding neighborhood preserves Federal and Georgian architecture.',
    address: 'Washington Square, Salem, MA 01970',
    hours: 'Open daily',
    admission: 'Free',
    displayOrder: 7,
    amenities: ['Walking paths', 'Benches', 'Bandstand'],
    accessibilityNotes: 'Paved perimeter path; grass interior',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-witch-house',
    name: 'The Witch House (Jonathan Corwin House)',
    placeType: 'HISTORIC_HOUSE',
    description:
      'Built around 1675, this is the only structure still standing with direct ties to the 1692 witch trials. Judge Jonathan Corwin conducted preliminary examinations of accused witches here. While predating the Revolution, the house illustrates the continuity of Salem\'s built environment into the 18th century.',
    address: '310 Essex Street, Salem, MA 01970',
    website: 'https://thewitchhouse.org/',
    hours: 'Mid-Mar through Nov, daily 10am-5pm',
    admission: '$10.25 adults',
    displayOrder: 8,
    amenities: ['Self-guided tour', 'Period furnishings'],
    accessibilityNotes: 'Limited accessibility; historic structure with narrow passages and stairs',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-first-church',
    name: 'First Church in Salem',
    placeType: 'CHURCH',
    description:
      'Congregation established in 1629, making it one of the oldest in North America. The current building dates to 1836, but the congregation\'s history spans the colonial and Revolutionary periods. Church records document how Salem\'s religious and political communities overlapped during the resistance movement.',
    address: '316 Essex Street, Salem, MA 01970',
    website: 'https://www.firstchurchinsalem.org/',
    hours: 'Sunday services; office hours weekdays',
    admission: 'Free',
    displayOrder: 9,
    amenities: ['Historic congregation', 'Archives'],
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-charter-street-cemetery',
    name: 'Charter Street Cemetery',
    placeType: 'CEMETERY',
    description:
      'Salem\'s oldest burying ground, established in 1637. Contains graves of Mayflower passengers, witch trial judge John Hathorne, and numerous 18th-century merchants and mariners whose families shaped the town\'s Revolutionary politics. The carved headstones are notable examples of colonial funerary art.',
    address: 'Charter Street, Salem, MA 01970',
    hours: 'Daily, dawn to dusk',
    admission: 'Free',
    displayOrder: 10,
    amenities: ['Historic gravestones', 'Walking paths'],
    accessibilityNotes: 'Uneven terrain, grass and gravel',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-mcintire-historic-district',
    name: 'McIntire Historic District',
    placeType: 'LANDMARK',
    description:
      'A residential district featuring homes designed by Salem architect Samuel McIntire in the Federal style. Many houses were built for merchants who profited from wartime privateering and postwar trade. The neighborhood demonstrates how Revolutionary-era wealth reshaped Salem\'s built environment.',
    historicalNote:
      'McIntire was self-taught. His distinctive style — combining classical elements with local craftsmanship — defined Salem\'s post-Revolution architectural identity.',
    address: 'Chestnut Street area, Salem, MA 01970',
    hours: 'Exterior viewing anytime; interiors by arrangement',
    admission: 'Free (public streets)',
    displayOrder: 11,
    amenities: ['Walking area', 'Historic architecture'],
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-willows-park',
    name: 'Salem Willows Park',
    placeType: 'LANDMARK',
    description:
      'A waterfront park at the tip of a peninsula overlooking Salem Harbor. The site offers views of the harbor approaches that privateers and merchant vessels used during the 18th century. Now a public recreation area with an amusement arcade and food stands.',
    address: '167 Fort Avenue, Salem, MA 01970',
    hours: 'Open daily',
    admission: 'Free (park); concessions vary',
    displayOrder: 12,
    amenities: ['Waterfront views', 'Food stands', 'Picnic areas', 'Parking'],
    accessibilityNotes: 'Paved paths near facilities; beach area less accessible',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-pioneer-village',
    name: 'Pioneer Village',
    placeType: 'MUSEUM',
    description:
      'A 1930 recreation of Salem\'s earliest settlement, built for the Massachusetts Bay Colony tercentenary. The village includes thatched-roof cottages, dugouts, and a governor\'s house representing life in the 1630s. It provides context for the century and a half of development that preceded Salem\'s Revolutionary role.',
    address: 'Forest River Park, Salem, MA 01970',
    hours: 'Seasonal, check for current schedule',
    admission: 'Nominal fee',
    displayOrder: 13,
    amenities: ['Living history', 'Costumed interpreters'],
    accessibilityNotes: 'Outdoor site with uneven ground',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-phillips-house',
    name: 'Phillips House',
    placeType: 'HISTORIC_HOUSE',
    description:
      'A Federal-period mansion on Chestnut Street operated by Historic New England. The house contains original furnishings spanning several generations of a single Salem family. Collections include decorative arts acquired through the maritime trade that defined Salem\'s economy from the colonial period onward.',
    address: '34 Chestnut Street, Salem, MA 01970',
    website: 'https://www.historicnewengland.org/property/phillips-house/',
    phone: '(978) 744-0440',
    hours: 'Jun-Oct, Sat-Sun 11am-4pm',
    admission: '$8 adults',
    displayOrder: 14,
    amenities: ['Guided tours', 'Period furnishings', 'Gardens'],
    accessibilityNotes: 'First floor partially accessible; upper floors via stairs',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-pickering-wharf',
    name: 'Pickering Wharf',
    placeType: 'LANDMARK',
    description:
      'A waterfront commercial area built on the site of historic wharves. The Pickering family operated from this section of the harbor during the colonial period. While the current shops and restaurants are modern, the location preserves the waterfront geography that made Salem a major port.',
    address: 'Pickering Wharf, Salem, MA 01970',
    hours: 'Shops and restaurants vary',
    displayOrder: 15,
    amenities: ['Shopping', 'Restaurants', 'Harbor views', 'Marina'],
    accessibilityNotes: 'Boardwalk areas accessible; some shops vary',
    town: { connect: { id: 'us-ma-salem' } },
  },
  {
    id: 'salem-assembly-house',
    name: 'Hamilton Hall',
    placeType: 'LANDMARK',
    description:
      'A Federal-style assembly hall built in 1805 and designed by Samuel McIntire. Named for Alexander Hamilton, the building served as a social gathering space for Salem\'s merchant class. Its construction reflects the prosperity that postwar trade and earlier privateering brought to the town\'s elite.',
    address: '9 Chestnut Street, Salem, MA 01970',
    hours: 'Private events; exterior viewing anytime',
    displayOrder: 16,
    amenities: ['Historic architecture'],
    town: { connect: { id: 'us-ma-salem' } },
  },
];
