// MODEL: Claude Opus (content) + Claude Sonnet (implementation)
// Arlington (Menotomy) flagship seed data - the bloodiest fighting of April 19

import { Prisma } from '@prisma/client';

// Arlington town update with full flagship content
export const arlingtonTownUpdate: Prisma.TownUpdateInput = {
  whyMatters: `Arlington—then called Menotomy—saw the bloodiest fighting of April 19, 1775. As the British column retreated from Concord, exhausted and increasingly desperate, they passed through a gauntlet of militia fire along what is now Massachusetts Avenue. Here the fighting turned vicious. Men died in houses, in yards, in hand-to-hand combat. More soldiers fell in Menotomy than at Lexington and Concord combined. The violence here foreshadowed what the war would become: not a series of formal battles but a grinding conflict where civilians and soldiers, regulars and militia, would kill each other in close quarters.`,
  tourismInfo: {
    walkabilityScore: 80,
    publicTransit: 'Good - MBTA bus routes along Mass Ave; close to Alewife T station',
    bestTimeToVisit: 'Patriots Day (April) for commemorations; spring and fall for walking',
    estimatedTimeNeeded: '3-4 hours for Revolutionary sites',
    visitorCenterAddress: 'Jason Russell House Museum, 7 Jason Street',
    accessibilityNotes: 'Some historic homes have limited accessibility; outdoor sites generally accessible',
    nearbyTowns: ['Cambridge', 'Lexington', 'Somerville', 'Medford'],
  },
  scoreBreakdown: {
    historicalSignificance: 80,
    preservation: 75,
    accessibility: 80,
    documentation: 75,
    visitorExperience: 75,
  },
};

// Arlington events - focused on April 19 fighting and aftermath
export const arlingtonEvents: Prisma.EventCreateInput[] = [
  {
    id: 'event-menotomy-ambush',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Battle of Menotomy - Main Engagement',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `As the British column entered Menotomy in the late afternoon, militia from towns across eastern Massachusetts had gathered along the road. The fighting that erupted was fiercer than anything that day. Exhausted soldiers, low on ammunition, faced fresh militia fighters who knew the terrain. Men shot from windows, from behind walls, from apple orchards. The British, increasingly desperate, began searching houses for snipers, leading to close-quarters killing.`,
    significanceWeight: 90,
    lat: 42.4154,
    lng: -71.1565,
  },
  {
    id: 'event-jason-russell-house',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Jason Russell House Attack',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `Jason Russell, a lame old man who refused to flee his home, was killed in his doorway as British soldiers stormed the house seeking militia who had fired from within. Inside, eleven militiamen had taken refuge; all but one were killed or wounded. The house became a symbol of the day's violence—civilians and soldiers dying together in domestic spaces. Russell's death, along with the killing of his wife's relatives sheltering there, showed that this would not be a gentlemen's war.`,
    significanceWeight: 85,
    lat: 42.4181,
    lng: -71.1689,
  },
  {
    id: 'event-cooper-tavern-killing',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Cooper Tavern Killings',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `At Cooper Tavern, British soldiers killed two men—Benjamin and Rachel Cooper's guests or employees—who were unarmed and apparently not participating in the fighting. Whether this was deliberate murder or the chaos of combat, contemporaries debated. The incident became part of the propaganda narrative about British atrocities, though the exact circumstances remain unclear. What is certain is that noncombatants died in Menotomy.`,
    significanceWeight: 75,
    lat: 42.4150,
    lng: -71.1545,
  },
  {
    id: 'event-percy-relief-arrives',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Percy\'s Relief Column Reaches Menotomy',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `Lord Percy's relief column, with fresh troops and artillery, had rescued Smith's exhausted force at Lexington. By the time they reached Menotomy, Percy's discipline was also fraying. His flanking parties cleared houses along the route, sometimes killing whoever they found. The artillery kept militia at a distance but could not prevent the steady harassment. Percy later praised his soldiers' restraint, but accounts suggest the fighting was brutal on both sides.`,
    significanceWeight: 80,
    lat: 42.4154,
    lng: -71.1565,
  },
  {
    id: 'event-foot-of-rocks-ambush',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Foot of the Rocks Ambush',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `At a rocky outcropping near the Mystic River, militia from Danvers and Lynn ambushed the British column. The terrain favored the Americans, who fired from elevated positions. British casualties mounted. This engagement, near the current Alewife area, was one of several that made the Menotomy stretch the deadliest of the day's march. The rocks provided natural fortification that militia used effectively.`,
    significanceWeight: 75,
    lat: 42.4120,
    lng: -71.1480,
  },
  {
    id: 'event-mother-batherick-capture',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Mother Batherick Captures British Soldiers',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `According to local tradition, an elderly woman known as Mother Batherick captured several exhausted and wounded British soldiers who had become separated from their column. Whether she held them at pitchfork-point or simply found them unable to continue, the story became a symbol of civilian participation in the day's events. The tale, likely embellished, captures how the entire community was drawn into the fighting.`,
    significanceWeight: 60,
    lat: 42.4160,
    lng: -71.1600,
  },
  {
    id: 'event-menotomy-casualty-count',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Menotomy Casualties Tallied',
    startDate: new Date('1775-04-20'),
    datePrecision: 'DAY',
    summary: `When the fighting ended and counts were made, Menotomy proved the deadliest location of April 19. Forty British soldiers had been killed and many more wounded. Approximately twenty-five Americans died, including militia from multiple towns and civilians like Jason Russell. The bodies were gathered, the wounded tended. The stone walls and houses bore the marks of the fighting. More men died in this single stretch of road than in the famed battles at Lexington Green and Concord Bridge combined.`,
    significanceWeight: 80,
    lat: 42.4154,
    lng: -71.1565,
  },
  {
    id: 'event-menotomy-militia-muster',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Menotomy Militia Muster on the Alarm',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `When word reached Menotomy that the regulars were marching, local militia gathered under Captain Benjamin Locke. Many took positions along the expected return route rather than marching to Concord. They were joined by companies from distant towns who had arrived too late for the morning's fighting. This convergence meant the British would face their heaviest opposition not at Lexington or Concord but here, on the road through Menotomy.`,
    significanceWeight: 70,
    lat: 42.4154,
    lng: -71.1565,
  },
  {
    id: 'event-samuel-whittemore-fight',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Samuel Whittemore\'s Stand',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `Samuel Whittemore, an 80-year-old veteran of earlier colonial wars, positioned himself behind a stone wall with musket, two pistols, and a sword. He killed or wounded three British soldiers before being shot, bayoneted, and left for dead. Astonishingly, he survived—living another eighteen years. His action became legendary: the oldest combatant of April 19, refusing to let age diminish his participation in what he saw as a just fight.`,
    significanceWeight: 85,
    lat: 42.4140,
    lng: -71.1520,
  },
  {
    id: 'event-blacks-retreat-menotomy',
    town: { connect: { id: 'us-ma-arlington' } },
    name: 'Black Militiamen in Menotomy Fighting',
    startDate: new Date('1775-04-19'),
    datePrecision: 'DAY',
    summary: `Several Black militiamen participated in the Menotomy fighting. Like Prince Estabrook wounded at Lexington, these men joined their communities in response to the alarm. Their presence was noted but often not individually recorded—they appear in casualty lists and muster rolls without the biographical detail given to white participants. Their service on April 19 would later fuel debates about whether Black men should serve in the Continental Army.`,
    significanceWeight: 75,
    lat: 42.4154,
    lng: -71.1565,
  },
];

// Arlington people - local fighters and victims
export const arlingtonPeople: Prisma.PersonCreateInput[] = [
  {
    id: 'person-samuel-whittemore',
    name: 'Samuel Whittemore',
    roles: ['Militia Veteran', 'Farmer'],
    bioShort: 'Eighty-year-old veteran who killed three British soldiers and survived being left for dead.',
    bioLong: `Samuel Whittemore had already lived a full life of war by April 19, 1775. He had fought at Louisbourg in 1745 and served in other colonial conflicts. At eighty, most men would have stayed home. Whittemore armed himself with musket, pistols, and sword, took position behind a stone wall, and waited for the British column. He shot three soldiers before being overwhelmed—shot in the face, bayoneted repeatedly, left for dead. Neighbors found him trying to reload his musket. He survived, recovered, and lived to ninety-eight. Massachusetts later named him the official state hero.`,
    birthYear: 1695,
    deathYear: 1793,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-jason-russell',
    name: 'Jason Russell',
    roles: ['Farmer', 'Civilian Victim'],
    bioShort: 'Menotomy farmer killed defending his home against British soldiers.',
    bioLong: `Jason Russell, about sixty years old and lame, refused to flee when militia gathered at his house on April 19. "An Englishman's home is his castle," he reportedly said. When British soldiers stormed the house seeking the militia firing from within, Russell was killed in his doorway, shot and bayoneted. His death became a symbol of British brutality and civilian suffering. His house, preserved as a museum, still shows the bullet holes from that day's fighting.`,
    birthYear: 1715,
    deathYear: 1775,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-benjamin-locke',
    name: 'Benjamin Locke',
    roles: ['Captain', 'Menotomy Militia'],
    bioShort: 'Captain of the Menotomy militia company on April 19.',
    bioLong: `Benjamin Locke commanded the Menotomy militia company that mustered when the alarm arrived. Rather than march toward Concord, Locke positioned his men along the road the British would use to return to Boston. This tactical decision contributed to making Menotomy the deadliest stretch of the retreat. Locke's local knowledge—understanding which houses provided cover, which walls offered protection—proved valuable in the close-quarters fighting.`,
    birthYear: 1730,
    deathYear: 1795,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-lord-percy-arlington',
    name: 'Hugh Percy, 2nd Duke of Northumberland',
    roles: ['British General', 'Relief Column Commander'],
    bioShort: 'British commander who led the relief column through Menotomy.',
    bioLong: `Lord Percy commanded the relief force that rescued Smith's exhausted column at Lexington. A professional officer who respected his American opponents, Percy tried to maintain discipline during the retreat through Menotomy, but the fighting's intensity strained his control. His flanking parties became increasingly aggressive in clearing houses. Percy later wrote that he had never seen such fighting spirit and admitted the Americans had proven themselves capable soldiers.`,
    birthYear: 1742,
    deathYear: 1817,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-jabez-wyman',
    name: 'Jabez Wyman',
    roles: ['Militiaman', 'Woburn Company'],
    bioShort: 'Militiaman killed while pursuing British flanking party.',
    bioLong: `Jabez Wyman of Woburn was among the militiamen killed in Menotomy. He had marched with his company to intercept the British retreat and was killed engaging one of Percy's flanking parties. His death, like many that day, came not in a formal battle but in the chaotic fighting along the road—brief, violent encounters between small groups of men in orchards, behind walls, and in backyards.`,
    birthYear: 1750,
    deathYear: 1775,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-john-hicks',
    name: 'John Hicks',
    roles: ['Militiaman', 'Cambridge Company'],
    bioShort: 'Cambridge militiaman killed at Foot of the Rocks.',
    bioLong: `John Hicks was among the Cambridge militia who took position at the rocky outcropping near the Mystic River. He was killed in the ambush there, one of several Cambridge men who died in the Menotomy fighting despite their town lying just to the east. His death illustrated how the day's casualties spread across multiple communities, as men from throughout eastern Massachusetts converged on the British route.`,
    birthYear: 1748,
    deathYear: 1775,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-william-barber',
    name: 'William Barber',
    roles: ['Militiaman', 'Charlestown Company'],
    bioShort: 'Charlestown militiaman wounded in the Menotomy fighting.',
    bioLong: `William Barber of Charlestown survived the Menotomy fighting but was seriously wounded. Like many wounded that day, he was carried to a nearby house for treatment. The lack of military medical services meant local physicians and family members provided what care they could. Barber's survival was fortunate; many with similar wounds died of infection in the days following.`,
    birthYear: 1745,
    deathYear: 1820,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-mother-batherick',
    name: 'Experience "Mother" Batherick',
    roles: ['Civilian', 'Folk Hero'],
    bioShort: 'Elderly woman who reportedly captured exhausted British soldiers.',
    bioLong: `Experience Batherick, known as "Mother Batherick," became a folk hero for allegedly capturing British soldiers during the April 19 retreat. The story varies in telling—she may have found them exhausted and surrendering, or held them at pitchfork point, or simply provided the kind of fierce presence that discouraged resistance. Whatever the precise truth, her story represented civilian participation in the day's events and was told for generations.`,
    birthYear: 1700,
    deathYear: 1790,
    verificationStatus: 'ORAL_TRADITION',
  },
  {
    id: 'person-james-miller-arlington',
    name: 'James Miller',
    roles: ['Militiaman', 'Killed at Russell House'],
    bioShort: 'One of eleven militiamen killed or wounded inside the Russell House.',
    bioLong: `James Miller was among the militiamen who took refuge in Jason Russell's house during the fighting. When British soldiers stormed the building, Miller was killed in the cellar where several men had retreated. The close-quarters fighting inside the house was vicious—bayonets in tight spaces, nowhere to flee. The Russell House became a killing ground that represented the war's emerging brutality.`,
    birthYear: 1740,
    deathYear: 1775,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-thomas-hadley',
    name: 'Thomas Hadley',
    roles: ['Militiaman', 'Lynn Company'],
    bioShort: 'Lynn militiaman who participated in Foot of the Rocks ambush.',
    bioLong: `Thomas Hadley marched with the Lynn company that arrived in time to participate in the Menotomy fighting. His company took position at the Foot of the Rocks, using the terrain advantage to fire down on the British column. Men from Lynn and other North Shore towns had further to march, but many arrived in time for the heaviest fighting of the day.`,
    birthYear: 1742,
    deathYear: 1810,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-moses-richardson',
    name: 'Moses Richardson',
    roles: ['Militiaman', 'Woburn Company'],
    bioShort: 'Woburn militiaman who served at Menotomy and throughout the siege.',
    bioLong: `Moses Richardson was among the Woburn militia who responded to the April 19 alarm and fought in the Menotomy engagement. He survived the day and continued to serve during the subsequent siege of Boston. His experience was typical of many militia: a farmer who mustered for the emergency, fought a confused engagement, and then remained for months of siege duty before returning home.`,
    birthYear: 1735,
    deathYear: 1805,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-thomas-gardner-arlington',
    name: 'Thomas Gardner',
    roles: ['Colonel', 'Cambridge Regiment'],
    bioShort: 'Cambridge officer who led men in the Menotomy fighting.',
    bioLong: `Colonel Thomas Gardner commanded Cambridge militia during the April 19 fighting, including the engagements around Menotomy. He would later be mortally wounded at Bunker Hill. Gardner represented the educated, property-owning class who provided militia leadership—men with enough standing in their communities to command respect and enough stake in the outcome to risk everything.`,
    birthYear: 1724,
    deathYear: 1775,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-samuel-cook',
    name: 'Samuel Cook',
    roles: ['Captain', 'Menotomy Militia'],
    bioShort: 'Captain of a Menotomy militia company who led men on April 19.',
    bioLong: `Samuel Cook commanded one of the Menotomy militia companies that mustered when the alarm arrived on April 19, 1775. Like other local officers, Cook knew the terrain and positioned his men to advantage. His company participated in the ambushes along the road that made Menotomy the deadliest stretch of the British retreat.`,
    birthYear: 1730,
    deathYear: 1805,
    verificationStatus: 'VERIFIED',
  },
];

// Arlington stories
export const arlingtonStories: Prisma.StoryCreateInput[] = [
  {
    id: 'story-russell-house-survivor',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'Inside the Russell House',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Militia Survivor',
    narratorRole: 'Woburn Company',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `We took shelter in Russell's house when the regulars came thick along the road. There were eleven of us inside, firing from the windows. Jason Russell—the owner, an old lame man—stood in his doorway. When the soldiers stormed in, he went down first. They came through the door and up the stairs and we retreated to the cellar. In that dark space, with bayonets and musket butts, they killed us. I don't know how I survived. When it was over, I crawled out past the bodies of men I had marched with that morning.`,
    audioScript: `We took shelter in Russell's house when the regulars came thick along the road. There were eleven of us inside, firing from the windows. Jason Russell stood in his doorway.`,
  },
  {
    id: 'story-whittemore-stand',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'The Old Man\'s Stand',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Neighbor',
    narratorRole: 'Menotomy Resident',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `Samuel Whittemore was eighty years old and still talking about Louisbourg, about King George's War, about every fight he'd ever been in. When the alarm came, we told him to stay home. He had no business fighting at his age. He ignored us, took his musket and pistols and that old sword, and went to the wall by the road. When the regulars came, he shot three of them before they got him. Shot in the face, run through with bayonets. We found him still trying to reload. He lived—eighteen more years. Some men are too stubborn to die.`,
    audioScript: `Samuel Whittemore was eighty years old and still talking about Louisbourg, about every fight he'd ever been in. When the alarm came, we told him to stay home.`,
  },
  {
    id: 'story-menotomy-civilian',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'A Woman\'s Witness',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Menotomy Farmwife',
    narratorRole: 'Civilian Witness',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `We hid in the swamp when the shooting started. My children clung to me in the water and muck while the battle raged along the road. I could see our house from where we hid. Soldiers—I couldn't tell whose—went through it. When we came back, the furniture was broken, food taken, blood on the floors. Our neighbors were dead. Jason Russell dead in his doorway. Young men we had known since they were boys, dead behind walls and in ditches. The war came to our homes that day. There was no battlefield, just our town become a slaughter.`,
    audioScript: `We hid in the swamp when the shooting started. My children clung to me in the water and muck while the battle raged along the road.`,
  },
  {
    id: 'story-menotomy-british-soldier',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'Through the Gauntlet',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'British Soldier',
    narratorRole: '4th Regiment of Foot',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `By Menotomy we had been marching and fighting for hours. Ammunition running low, men dropping from exhaustion and wounds. Every wall, every window, every tree seemed to hide a rebel with a musket. Percy's flankers searched the houses, but the shooting never stopped. We killed everyone we found—there was no time for prisoners, no certainty who was a fighter. I saw things that day I do not wish to remember. The rebels were not soldiers by any standard we knew, but they fought with a fury that made us fear for our lives.`,
    audioScript: `By Menotomy we had been marching and fighting for hours. Ammunition running low, men dropping from exhaustion and wounds. Every wall seemed to hide a rebel.`,
  },
  {
    id: 'story-modern-arlington-museum',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'Preserving the Russell House',
    storyType: 'MODERN_VOICE',
    narratorName: 'Museum Director',
    narratorRole: 'Jason Russell House Museum',
    verificationStatus: 'VERIFIED',
    textVersion: `The bullet holes are still in the walls. People come expecting a sanitized museum and find evidence of violence—actual holes where musket balls struck, the cellar where men died. We don't soften the story. Arlington's role on April 19 was brutal and chaotic. More people died here than at Lexington or Concord. The famous battles make good paintings. What happened here was grimmer: close-quarters killing in a family home. Jason Russell died in his doorway. Eleven men died or were wounded in his cellar. That's the reality we preserve.`,
    audioScript: `The bullet holes are still in the walls. People come expecting a sanitized museum and find evidence of violence. We don't soften the story.`,
  },
  {
    id: 'story-modern-arlington-historian',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'The Forgotten Battle',
    storyType: 'MODERN_VOICE',
    narratorName: 'Local Historian',
    narratorRole: 'Arlington Historical Society',
    verificationStatus: 'VERIFIED',
    textVersion: `Everyone knows Lexington and Concord. Arlington—Menotomy—gets overlooked, which is ironic because this is where the heaviest casualties occurred. Forty British dead, around twenty-five Americans. The fighting here wasn't the opening shot or the first real battle. It was something messier: a running fight through a town, soldiers killing civilians, militia shooting from houses. It doesn't fit the narrative of patriotic farmers defending liberty. It looks more like what war actually is—ugly, confusing, and deadly for everyone caught up in it.`,
    audioScript: `Everyone knows Lexington and Concord. Arlington gets overlooked, which is ironic because this is where the heaviest casualties occurred.`,
  },
  {
    id: 'story-modern-arlington-battlefield',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'Walking the Battle Road',
    storyType: 'MODERN_VOICE',
    narratorName: 'Walking Tour Guide',
    narratorRole: 'Battle Road Tours',
    verificationStatus: 'VERIFIED',
    textVersion: `I walk people along Massachusetts Avenue and ask them to imagine it unpaved, lined with stone walls and apple orchards, with exhausted British soldiers trying to fight their way through while fresh militia poured fire from every conceivable hiding place. The terrain has changed—strip malls where farms stood—but some original features remain. The Whittemore marker. The Russell House. The footprint of the road itself. You have to work to see the battlefield, but it's still here underneath modern Arlington.`,
    audioScript: `I walk people along Massachusetts Avenue and ask them to imagine it unpaved, lined with stone walls, with exhausted British soldiers trying to fight their way through.`,
  },
  {
    id: 'story-modern-arlington-archaeology',
    town: { connect: { id: 'us-ma-arlington' } },
    title: 'Finding the Battle',
    storyType: 'MODERN_VOICE',
    narratorName: 'Archaeologist',
    narratorRole: 'Massachusetts Archaeological Society',
    verificationStatus: 'VERIFIED',
    textVersion: `We've found musket balls, military buttons, fragments of cartridge boxes—the debris of the running battle. Every time someone digs a foundation in old Arlington, there's a chance of finding April 19 artifacts. The challenge is that the battle happened along a road that's been continuously occupied for 250 years. We're looking for traces of one violent afternoon buried under centuries of daily life. But the artifacts are there. The battle left its mark in the soil.`,
    audioScript: `We've found musket balls, military buttons, fragments of cartridge boxes—the debris of the running battle. Every time someone digs a foundation, there's a chance.`,
  },
];

// Arlington theme connections
export const arlingtonThemeConnections: Array<{ themeId: string; relevanceNote: string }> = [
  { themeId: 'citizen-soldiers', relevanceNote: 'Militia from multiple towns converged here to fight' },
  { themeId: 'liberty-freedom', relevanceNote: 'The deadliest fighting of the day that started the war' },
  { themeId: 'women-revolution', relevanceNote: 'Civilian women caught in the violence; Mother Batherick legend' },
  { themeId: 'preservation-memory', relevanceNote: 'Jason Russell House preserved with bullet holes intact' },
  { themeId: 'enslaved-free-black', relevanceNote: 'Black militiamen participated in the fighting' },
  { themeId: 'military-innovation', relevanceNote: 'Guerrilla tactics and close-quarters combat' },
  { themeId: 'propaganda-communication', relevanceNote: 'Menotomy casualties used in propaganda about British brutality' },
  { themeId: 'loyalists-divided', relevanceNote: 'Community torn apart; some fled, others fought' },
];

// Arlington sources
export const arlingtonSources: Prisma.SourceCreateInput[] = [
  {
    id: 'source-russell-house-museum',
    type: 'INSTITUTIONAL',
    title: 'Jason Russell House Museum',
    publisherOrHolder: 'Arlington Historical Society',
    url: 'https://arlingtonhistorical.org/jason-russell-house/',
    credibilityTier: 'TIER1',
    notes: 'Primary site for Menotomy April 19 interpretation',
  },
  {
    id: 'source-fischer-revere',
    type: 'SECONDARY',
    title: 'Paul Revere\'s Ride',
    publisherOrHolder: 'David Hackett Fischer / Oxford University Press',
    credibilityTier: 'TIER1',
    notes: 'Comprehensive scholarly account including Menotomy fighting',
  },
  {
    id: 'source-arlington-historical',
    type: 'INSTITUTIONAL',
    title: 'Arlington Historical Society Archives',
    publisherOrHolder: 'Arlington Historical Society',
    url: 'https://arlingtonhistorical.org',
    credibilityTier: 'TIER2',
    notes: 'Local records and oral traditions',
  },
  {
    id: 'source-april-morning-depositions',
    type: 'PRIMARY',
    title: 'Depositions of April 19 Participants',
    publisherOrHolder: 'Massachusetts Provincial Congress',
    credibilityTier: 'TIER1',
    notes: 'First-hand accounts taken shortly after the battles',
  },
  {
    id: 'source-coburn-menotomy',
    type: 'SECONDARY',
    title: 'The Battle of April 19, 1775',
    publisherOrHolder: 'Frank Warren Coburn',
    credibilityTier: 'TIER2',
    notes: 'Classic early study with detailed Menotomy coverage',
  },
  {
    id: 'source-murdock-april19',
    type: 'SECONDARY',
    title: 'The Nineteenth of April 1775',
    publisherOrHolder: 'Harold Murdock',
    credibilityTier: 'TIER2',
    notes: 'Critical examination of April 19 evidence',
  },
  {
    id: 'source-smith-report',
    type: 'PRIMARY',
    title: 'Lt. Col. Smith\'s Report to General Gage',
    publisherOrHolder: 'British Army Records',
    credibilityTier: 'TIER1',
    notes: 'British commander\'s official report on the expedition',
  },
  {
    id: 'source-percy-letter',
    type: 'PRIMARY',
    title: 'Lord Percy\'s Letter to General Harvey',
    publisherOrHolder: 'Percy Family Papers',
    credibilityTier: 'TIER1',
    notes: 'Percy\'s personal account of the retreat',
  },
  {
    id: 'source-mma-april19',
    type: 'INSTITUTIONAL',
    title: 'Minute Man National Historical Park',
    publisherOrHolder: 'National Park Service',
    url: 'https://www.nps.gov/mima',
    credibilityTier: 'TIER1',
    notes: 'NPS interpretation of full April 19 engagement',
  },
  {
    id: 'source-arlington-town-history',
    type: 'SECONDARY',
    title: 'History of the Town of Arlington',
    publisherOrHolder: 'Various editions',
    credibilityTier: 'TIER2',
    notes: 'Town histories with local perspectives on the battle',
  },
  {
    id: 'source-whittemore-biography',
    type: 'SECONDARY',
    title: 'Samuel Whittemore: Massachusetts State Hero',
    publisherOrHolder: 'Massachusetts General Court',
    credibilityTier: 'TIER2',
    notes: 'Documentation of Whittemore\'s official recognition',
  },
  {
    id: 'source-mass-soldiers-sailors',
    type: 'PRIMARY',
    title: 'Massachusetts Soldiers and Sailors of the Revolutionary War',
    publisherOrHolder: 'Commonwealth of Massachusetts',
    credibilityTier: 'TIER1',
    notes: 'Service records of Menotomy participants',
  },
];

// Arlington town links
export const arlingtonTownLinks: Prisma.TownLinkCreateInput[] = [
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-lexington' } },
    linkType: 'ROUTE',
    reason: 'Battle Road connected Lexington and Menotomy; retreat route',
    weight: 95,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-concord' } },
    linkType: 'ROUTE',
    reason: 'Part of the same day\'s fighting; British marched through both',
    weight: 85,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-cambridge' } },
    linkType: 'ROUTE',
    reason: 'British retreated through Menotomy toward Cambridge/Charlestown',
    weight: 85,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-boston' } },
    linkType: 'SHARED_EVENT',
    reason: 'British expedition originated from Boston; retreat ended there',
    weight: 80,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-woburn' } },
    linkType: 'SHARED_PERSON',
    reason: 'Woburn militia fought and died at Menotomy',
    weight: 75,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-danvers' } },
    linkType: 'SHARED_EVENT',
    reason: 'Danvers militia participated in Foot of the Rocks ambush',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-lynn' } },
    linkType: 'SHARED_EVENT',
    reason: 'Lynn company fought at Menotomy',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-medford' } },
    linkType: 'ROUTE',
    reason: 'Adjacent town; some fighting extended into Medford',
    weight: 65,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-charlestown' } },
    linkType: 'SHARED_PERSON',
    reason: 'Charlestown militia participated in Menotomy fighting',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-arlington' } },
    toTown: { connect: { id: 'us-ma-salem' } },
    linkType: 'SHARED_EVENT',
    reason: 'Salem militia marched but arrived after main fighting',
    weight: 60,
  },
];

// Arlington routes
export const arlingtonRoutes: Prisma.RouteCreateInput[] = [
  {
    id: 'route-menotomy-battlefield',
    name: 'Menotomy Battlefield Walk',
    description: 'Walking tour of the deadliest fighting of April 19, 1775',
    totalMiles: 2.0,
  },
  {
    id: 'route-battle-road-arlington',
    name: 'Battle Road: Arlington Section',
    description: 'The section of the British retreat through what is now Arlington',
    totalMiles: 3.0,
  },
];

// Arlington route stops
export const arlingtonRouteStops: Array<{
  routeId: string;
  townId: string;
  stopOrder: number;
  notes: string;
}> = [
  {
    routeId: 'route-menotomy-battlefield',
    townId: 'us-ma-arlington',
    stopOrder: 1,
    notes: 'Jason Russell House - site of the deadliest house fighting',
  },
  {
    routeId: 'route-menotomy-battlefield',
    townId: 'us-ma-arlington',
    stopOrder: 2,
    notes: 'Samuel Whittemore marker - where the 80-year-old veteran made his stand',
  },
  {
    routeId: 'route-menotomy-battlefield',
    townId: 'us-ma-arlington',
    stopOrder: 3,
    notes: 'Foot of the Rocks area - site of major ambush',
  },
  {
    routeId: 'route-battle-road-arlington',
    townId: 'us-ma-lexington',
    stopOrder: 1,
    notes: 'British column after Percy\'s relief',
  },
  {
    routeId: 'route-battle-road-arlington',
    townId: 'us-ma-arlington',
    stopOrder: 2,
    notes: 'Through Menotomy - heaviest casualties',
  },
  {
    routeId: 'route-battle-road-arlington',
    townId: 'us-ma-cambridge',
    stopOrder: 3,
    notes: 'Retreat continues toward Charlestown',
  },
];
