// MODEL: Claude Opus (content) + Claude Sonnet (implementation)
// Cambridge flagship seed data - Washington's headquarters and siege command center

import { Prisma } from '@prisma/client';

// Cambridge town update with full flagship content
export const cambridgeTownUpdate: Prisma.TownUpdateInput = {
  whyMatters: `Cambridge became the nerve center of the American Revolution in 1775. When Washington arrived to take command of the Continental Army, he found not a professional fighting force but a collection of militia units from across New England, camped in a loose arc from Roxbury to Chelsea. His task was to transform this assembly into something capable of facing British regulars. The town's role was administrative and strategic rather than dramatic—no major battles occurred here, but every decision about the siege emanated from headquarters. Harvard Yard became a barracks, Christ Church served officers, and the Vassall house became the command center where Washington learned, often painfully, what it meant to lead an army of citizens.`,
  tourismInfo: {
    walkabilityScore: 95,
    publicTransit: 'Excellent - Red Line T stops at Harvard Square and Central Square',
    bestTimeToVisit: 'Spring or fall for comfortable walking; Harvard commencement in May adds historical resonance',
    estimatedTimeNeeded: '4-6 hours for Revolutionary sites; full day with Harvard campus',
    visitorCenterAddress: 'Harvard Information Center, 1350 Massachusetts Ave',
    accessibilityNotes: 'Most sites wheelchair accessible; some historic buildings have limited access',
    nearbyTowns: ['Boston', 'Lexington', 'Arlington', 'Somerville'],
  },
  scoreBreakdown: {
    historicalSignificance: 85,
    preservation: 80,
    accessibility: 95,
    documentation: 85,
    visitorExperience: 85,
  },
};

// Cambridge events - focused on command and siege operations
export const cambridgeEvents: Prisma.EventCreateInput[] = [
  {
    id: 'event-washington-takes-command',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Washington Takes Command of Continental Army',
    startDate: new Date('1775-07-03'),
    datePrecision: 'DAY',
    summary: `Under an elm tree on Cambridge Common, George Washington formally assumed command of the Continental Army. The ceremony was simple—no grand parade, no elaborate protocol. Washington faced an army of perhaps 16,000 men, poorly supplied, with enlistments expiring, and no clear organizational structure. He immediately began the work of imposing order on chaos, a task that would consume the next eight months.`,
    significanceWeight: 95,
    lat: 42.3751,
    lng: -71.1189,
  },
  {
    id: 'event-siege-cambridge-hq',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Siege of Boston Command Operations',
    startDate: new Date('1775-07-04'),
    endDate: new Date('1776-03-17'),
    datePrecision: 'DAY',
    summary: `For eight months, Cambridge served as the headquarters for the siege of Boston. Washington coordinated defensive positions stretching from Roxbury to Chelsea, managed chronic supply shortages, dealt with expiring enlistments, and attempted to forge a unified command structure from thirteen colonial militias with different traditions and expectations. The siege was largely a war of patience and logistics rather than pitched battles.`,
    significanceWeight: 90,
    lat: 42.3770,
    lng: -71.1167,
  },
  {
    id: 'event-vassall-house-headquarters',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Longfellow House Becomes Washington\'s Headquarters',
    startDate: new Date('1775-07-15'),
    datePrecision: 'MONTH',
    summary: `Washington established his headquarters in the abandoned Vassall house (now Longfellow House), a Georgian mansion whose Loyalist owner had fled to England. Here Washington held councils of war, received intelligence reports, corresponded with Congress, and grappled with the endless administrative demands of maintaining an army. Martha Washington joined him here for the winter of 1775-76.`,
    significanceWeight: 85,
    lat: 42.3769,
    lng: -71.1264,
  },
  {
    id: 'event-harvard-barracks',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Harvard College Converted to Military Use',
    startDate: new Date('1775-06-01'),
    datePrecision: 'MONTH',
    summary: `Harvard suspended classes and its buildings became barracks for Continental soldiers. Students were sent home or relocated. Massachusetts Hall housed troops, and Harvard Yard became a drilling ground. The college would not fully resume normal operations until after the British evacuated Boston. This conversion represented the total mobilization of colonial society for the war effort.`,
    significanceWeight: 75,
    lat: 42.3744,
    lng: -71.1169,
  },
  {
    id: 'event-powder-house-supply',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Continental Army Supply Crisis',
    startDate: new Date('1775-08-01'),
    datePrecision: 'MONTH',
    summary: `Washington discovered the army had only 36 barrels of gunpowder—enough for perhaps nine rounds per man. He was so shocked he reportedly sat silent for half an hour. The crisis forced a defensive posture and desperate efforts to acquire powder from any source. Had the British attacked during this period, the result might have been catastrophic. The shortage shaped every tactical decision for months.`,
    significanceWeight: 80,
    lat: 42.3751,
    lng: -71.1189,
  },
  {
    id: 'event-council-of-war-october',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Council of War Debates Attack on Boston',
    startDate: new Date('1775-10-18'),
    datePrecision: 'DAY',
    summary: `Washington convened his generals to consider an amphibious assault on Boston. The council unanimously rejected the plan as too risky given the army's inexperience and the British naval superiority. This pattern—Washington proposing bold action, his officers urging caution—would repeat throughout the siege. The decision to wait proved wise, though frustrating.`,
    significanceWeight: 70,
    lat: 42.3769,
    lng: -71.1264,
  },
  {
    id: 'event-enlistment-crisis',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Enlistment Crisis and Army Reorganization',
    startDate: new Date('1775-12-31'),
    datePrecision: 'DAY',
    summary: `Most Continental Army enlistments expired on December 31, 1775. Washington faced the nightmare scenario of his army dissolving while besieging Boston. Some men simply went home. Others demanded bounties to re-enlist. Through desperate measures—appeals to patriotism, promises of pay, threats—enough men stayed to maintain the siege, but the experience left Washington deeply skeptical of short enlistments.`,
    significanceWeight: 85,
    lat: 42.3751,
    lng: -71.1189,
  },
  {
    id: 'event-martha-washington-arrives',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Martha Washington Arrives at Headquarters',
    startDate: new Date('1775-12-11'),
    datePrecision: 'DAY',
    summary: `Martha Washington arrived in Cambridge after a journey from Virginia, bringing supplies and establishing herself as hostess at headquarters. Her presence provided stability and helped maintain morale among the officers. She organized sewing circles to make clothing for soldiers and visited the sick. This began a pattern she would maintain throughout the war, joining Washington in winter quarters.`,
    significanceWeight: 70,
    lat: 42.3769,
    lng: -71.1264,
  },
  {
    id: 'event-riflemen-arrive',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Virginia and Pennsylvania Riflemen Arrive',
    startDate: new Date('1775-08-01'),
    datePrecision: 'MONTH',
    summary: `Companies of frontier riflemen from Virginia, Pennsylvania, and Maryland arrived in Cambridge, having marched hundreds of miles. Their long rifles could hit targets at distances impossible for smoothbore muskets, and they were deployed as snipers against British positions. However, their undisciplined behavior and resentment of New England authority caused constant problems. Daniel Morgan's company was among the most effective.`,
    significanceWeight: 75,
    lat: 42.3751,
    lng: -71.1189,
  },
  {
    id: 'event-knox-artillery-plan',
    town: { connect: { id: 'us-ma-cambridge' } },
    name: 'Knox Proposes Fort Ticonderoga Artillery Mission',
    startDate: new Date('1775-11-16'),
    datePrecision: 'DAY',
    summary: `Henry Knox, a Boston bookseller turned artillery officer, proposed bringing captured British cannon from Fort Ticonderoga to break the siege stalemate. Washington approved the audacious plan. Knox departed in late November on what would become a legendary winter journey across frozen lakes and mountains, returning with 60 tons of artillery that would finally tip the balance.`,
    significanceWeight: 85,
    lat: 42.3769,
    lng: -71.1264,
  },
];

// Cambridge people - command staff and key figures
export const cambridgePeople: Prisma.PersonCreateInput[] = [
  {
    id: 'person-george-washington',
    name: 'George Washington',
    roles: ['Commander-in-Chief', 'General'],
    bioShort: 'Commander-in-Chief of the Continental Army who established his headquarters in Cambridge.',
    bioLong: `George Washington arrived in Cambridge in July 1775 to find an army in name only. His experience in the French and Indian War had not prepared him for the challenge of creating a unified command from thirteen colonial militias, each with its own traditions and jealousies. In Cambridge, Washington learned the limits of his authority and the necessity of patience. He could order, but men might not obey. He could plan attacks, but his officers might reject them. The eight months in Cambridge taught him that leading an army of citizens required different skills than commanding regulars.`,
    birthYear: 1732,
    deathYear: 1799,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-artemas-ward',
    name: 'Artemas Ward',
    roles: ['General', 'Massachusetts Militia Commander'],
    bioShort: 'Massachusetts general who commanded American forces before Washington arrived.',
    bioLong: `Artemas Ward held command of the forces besieging Boston from April until July 1775, organizing the siege lines and maintaining discipline during a chaotic period. A Harvard graduate and veteran of the French and Indian War, Ward suffered from ill health but provided steady leadership during the critical early months. When Washington arrived, Ward served as second in command, though his influence waned. His contribution to establishing the siege before Washington's arrival is often overlooked.`,
    birthYear: 1727,
    deathYear: 1800,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-charles-lee',
    name: 'Charles Lee',
    roles: ['General', 'Former British Officer'],
    bioShort: 'Eccentric former British officer who served as Washington\'s second in command.',
    bioLong: `Charles Lee brought professional military experience that few Americans possessed—he had served in the British army across Europe and fought with distinction. His knowledge was invaluable, but his arrogance and ambition created friction. Lee openly believed himself more qualified than Washington for command. In Cambridge, he proved useful in training troops and planning defenses, but his contempt for amateur soldiers and elected officials made him a difficult subordinate.`,
    birthYear: 1732,
    deathYear: 1782,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-horatio-gates',
    name: 'Horatio Gates',
    roles: ['General', 'Adjutant General'],
    bioShort: 'Former British officer who served as adjutant general, organizing army administration.',
    bioLong: `Horatio Gates served as adjutant general, responsible for the administrative machinery of the army—returns, orders, discipline, and organization. A former British officer who had settled in Virginia, Gates brought professional experience to the chaotic task of creating an army from scratch. His meticulous attention to paperwork and procedure helped impose order on the siege operations, though he chafed at his subordinate role.`,
    birthYear: 1727,
    deathYear: 1806,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-nathanael-greene',
    name: 'Nathanael Greene',
    roles: ['General', 'Rhode Island Brigade Commander'],
    bioShort: 'Self-taught military leader who became one of Washington\'s most trusted generals.',
    bioLong: `Nathanael Greene arrived in Cambridge commanding Rhode Island troops, having taught himself military science from books. A Quaker who had been expelled from his meeting for attending a military parade, Greene impressed Washington with his intelligence and dedication. During the siege, he commanded positions in Roxbury and Jamaica Plain, learning the practical realities of command. His ability to learn from mistakes and his organizational skills marked him for future responsibility.`,
    birthYear: 1742,
    deathYear: 1786,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-william-heath',
    name: 'William Heath',
    roles: ['General', 'Massachusetts Militia'],
    bioShort: 'Massachusetts farmer-general who commanded siege positions.',
    bioLong: `William Heath, a farmer from Roxbury who had studied military tactics for years, commanded American positions during the siege. He had helped coordinate the militia response on April 19 and served competently if not brilliantly during the siege. Washington found him reliable but unimaginative. Heath's service in Cambridge exemplified the citizen-soldier ethos—a man of modest means who studied war as a civic duty.`,
    birthYear: 1737,
    deathYear: 1814,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-john-sullivan',
    name: 'John Sullivan',
    roles: ['General', 'New Hampshire Brigade Commander'],
    bioShort: 'New Hampshire lawyer and general who commanded during the siege.',
    bioLong: `John Sullivan, a New Hampshire lawyer, arrived in Cambridge with his colony's troops. Ambitious and sometimes rash, Sullivan proved an aggressive commander who sought action during the siege's long months of waiting. Washington appreciated his energy while sometimes questioning his judgment. Sullivan's frustration with the defensive posture reflected that of many officers who wanted decisive action.`,
    birthYear: 1740,
    deathYear: 1795,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-israel-putnam',
    name: 'Israel Putnam',
    roles: ['General', 'Connecticut Commander'],
    bioShort: 'Legendary Connecticut farmer-soldier known for bravery at Bunker Hill.',
    bioLong: `Israel Putnam arrived in Cambridge already a legend—the man who had been captured by Native Americans and nearly burned at the stake, who had crawled into a wolf's den, who had ridden down a cliff to escape the British. At Bunker Hill, his cry "Don't fire until you see the whites of their eyes" (attribution disputed) became immortal. During the siege, Old Put commanded Connecticut forces, his reputation inspiring troops even as his tactical skills proved limited.`,
    birthYear: 1718,
    deathYear: 1790,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-richard-gridley',
    name: 'Richard Gridley',
    roles: ['Colonel', 'Chief Engineer'],
    bioShort: 'Experienced military engineer who designed American fortifications.',
    bioLong: `Richard Gridley, at 64, was the oldest officer in the Continental Army and its most experienced engineer. He had designed the fortifications at Bunker Hill and continued building defensive works throughout the siege. His knowledge of siegecraft—how to build redoubts, where to place batteries, how to protect against artillery—was invaluable. Gridley represented the technical expertise that citizen-soldiers often lacked.`,
    birthYear: 1710,
    deathYear: 1796,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-martha-washington-cambridge',
    name: 'Martha Washington',
    roles: ['Commander\'s Wife', 'Camp Administrator'],
    bioShort: 'Washington\'s wife who managed headquarters social affairs and supported troops.',
    bioLong: `Martha Washington's arrival in Cambridge in December 1775 transformed headquarters from a purely military operation to something resembling a functioning household. She managed social obligations, hosted dinners for officers, organized clothing production for soldiers, and visited the sick. Her presence helped maintain morale and provided a symbol of domestic normalcy amid the chaos of war. She would repeat this pattern every winter of the conflict.`,
    birthYear: 1731,
    deathYear: 1802,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-benjamin-church',
    name: 'Benjamin Church',
    roles: ['Surgeon General', 'Spy'],
    bioShort: 'Continental Army surgeon discovered to be a British spy.',
    bioLong: `Benjamin Church held the position of Surgeon General of the Continental Army, responsible for medical care of troops. In September 1775, an encrypted letter to the British was traced to him. Court-martialed and convicted of treason, Church was imprisoned. His betrayal shocked the army and revealed the vulnerability of the American cause to infiltration. The affair prompted greater attention to security and intelligence.`,
    birthYear: 1734,
    deathYear: 1778,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-john-glover',
    name: 'John Glover',
    roles: ['Colonel', 'Marblehead Regiment Commander'],
    bioShort: 'Marblehead fisherman whose sailors would later rescue the army at Brooklyn.',
    bioLong: `John Glover commanded the Marblehead regiment—fishermen and sailors who were comfortable on water in ways most soldiers were not. During the siege, they manned positions and conducted raids, but their unique skills were not yet fully utilized. That would come later, when Glover's men rowed Washington's army across the East River in the dark after the Battle of Brooklyn and across the Delaware before Trenton.`,
    birthYear: 1732,
    deathYear: 1797,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-joseph-reed',
    name: 'Joseph Reed',
    roles: ['Secretary', 'Aide-de-Camp'],
    bioShort: 'Washington\'s military secretary who handled correspondence and intelligence.',
    bioLong: `Joseph Reed served as Washington's military secretary at Cambridge, handling the enormous volume of correspondence that command required. A Philadelphia lawyer, Reed managed intelligence reports, drafted orders, and served as a confidant to the commander. His role was administrative but essential—the siege required constant communication with Congress, state governments, and subordinate officers.`,
    birthYear: 1741,
    deathYear: 1785,
    verificationStatus: 'VERIFIED',
  },
  {
    id: 'person-samuel-osgood',
    name: 'Samuel Osgood',
    roles: ['Aide-de-Camp', 'Massachusetts Provincial Congress'],
    bioShort: 'Massachusetts officer who served on Washington\'s staff.',
    bioLong: `Samuel Osgood served as an aide-de-camp at Cambridge, one of the young men who carried messages, copied orders, and assisted with the endless details of running an army. From Andover, Osgood brought local knowledge and connections. He would later serve in the Continental Congress and as the first Postmaster General under the Constitution.`,
    birthYear: 1747,
    deathYear: 1813,
    verificationStatus: 'VERIFIED',
  },
];

// Cambridge stories
export const cambridgeStories: Prisma.StoryCreateInput[] = [
  {
    id: 'story-washington-elm',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Under the Washington Elm',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Continental Soldier',
    narratorRole: 'Massachusetts Militiaman',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `We had been waiting for weeks, knowing a new commander was coming from Virginia. When he arrived, there was no great ceremony. He simply read his commission under an elm tree on the Common, took the salute, and went to work. He was taller than any of us, with an air of command that made you straighten your spine. But what struck me most was how quickly he got to business—inspecting positions, asking questions, discovering that we had almost no powder. The general's face when he heard that news... I never want to see that expression again.`,
    audioScript: `We had been waiting for weeks, knowing a new commander was coming from Virginia. When he arrived, there was no great ceremony. He simply read his commission under an elm tree on the Common, took the salute, and went to work.`,
  },
  {
    id: 'story-martha-cambridge',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Martha at Headquarters',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Headquarters Staff',
    narratorRole: 'Aide-de-Camp',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `When Mrs. Washington arrived, headquarters changed. Before, it was all military business—dispatches, councils, complaints about supplies. She brought order of a different kind. Dinners became occasions where officers could speak of something besides the siege. She organized the women to sew shirts for soldiers who had none. When smallpox swept through camp, she visited the sick. The general, I noticed, was calmer with her there. He still worked from dawn to midnight, but he seemed less alone in his burden.`,
    audioScript: `When Mrs. Washington arrived, headquarters changed. Before, it was all military business—dispatches, councils, complaints about supplies. She brought order of a different kind.`,
  },
  {
    id: 'story-harvard-barracks',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Soldiers in the Yard',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Harvard Student',
    narratorRole: 'Displaced Scholar',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `They sent us home when the soldiers came. The college where I had studied Latin and philosophy became a barracks. Men from New Hampshire and Connecticut slept in Massachusetts Hall, cooked their meals in the Yard, drilled where we had walked to lectures. When I returned after the siege lifted, the buildings smelled of smoke and unwashed men. Books were missing. But I could not resent the soldiers. They had traded their farms and shops for cold camps and uncertain futures. If they needed Harvard's walls more than I needed Cicero, so be it.`,
    audioScript: `They sent us home when the soldiers came. The college where I had studied Latin and philosophy became a barracks. Men from New Hampshire and Connecticut slept in Massachusetts Hall.`,
  },
  {
    id: 'story-powder-alarm-cambridge',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'The Day We Discovered the Truth',
    storyType: 'HISTORICAL_VOICE',
    narratorName: 'Artillery Officer',
    narratorRole: 'Continental Army',
    verificationStatus: 'ORAL_TRADITION',
    textVersion: `I was there when the general received the powder return. Thirty-six barrels. For an army of thousands, facing British regulars who could fire three rounds a minute. He dismissed everyone and sat alone. When I returned an hour later, he had composed himself, but I had seen what none of us were supposed to see—the weight of knowing that one British assault could end everything. After that, every decision was shaped by what we lacked. We could not attack. We could barely defend. We could only wait and pray the enemy stayed behind their lines.`,
    audioScript: `I was there when the general received the powder return. Thirty-six barrels. For an army of thousands, facing British regulars who could fire three rounds a minute.`,
  },
  {
    id: 'story-modern-cambridge-preservationist',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Preserving the Siege Story',
    storyType: 'MODERN_VOICE',
    narratorName: 'Historical Preservationist',
    narratorRole: 'Longfellow House Curator',
    verificationStatus: 'VERIFIED',
    textVersion: `People come to Longfellow House expecting to hear about the poet. They're surprised to learn Washington lived here first. But the siege of Boston happened here—in these rooms, around this table. Washington sat where you're standing, trying to figure out how to beat the most powerful military in the world with an army that might dissolve on New Year's Eve. We have letters he wrote here, agonizing over supplies, discipline, strategy. The house makes the history tangible. You can't walk through these rooms and not feel the weight of those decisions.`,
    audioScript: `People come to Longfellow House expecting to hear about the poet. They're surprised to learn Washington lived here first. But the siege of Boston happened here—in these rooms, around this table.`,
  },
  {
    id: 'story-modern-cambridge-academic',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Teaching the Revolution at Harvard',
    storyType: 'MODERN_VOICE',
    narratorName: 'History Professor',
    narratorRole: 'Harvard University',
    verificationStatus: 'VERIFIED',
    textVersion: `I teach the Revolution in buildings that housed Revolutionary soldiers. Massachusetts Hall, where my office is, served as barracks in 1775. Students find this remarkable—that the institution continued, transformed but unbroken, from a college disrupted by war to a university that studies that war. Cambridge's Revolutionary role was administrative rather than dramatic. No battle occurred here. But the decisions made at Washington's headquarters shaped everything that followed. The siege was won not by assault but by organization, patience, and the arrival of Knox's artillery.`,
    audioScript: `I teach the Revolution in buildings that housed Revolutionary soldiers. Massachusetts Hall, where my office is, served as barracks in 1775.`,
  },
  {
    id: 'story-modern-cambridge-tour',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Walking Washington\'s Cambridge',
    storyType: 'MODERN_VOICE',
    narratorName: 'Walking Tour Guide',
    narratorRole: 'Cambridge Historical Tours',
    verificationStatus: 'VERIFIED',
    textVersion: `The Washington Elm is gone—it fell in 1923, weakened by age and storms. But I stand where it stood and tell visitors: here, on July 3, 1775, a Virginia planter became the commander of an American army. The elm's absence actually helps make my point. History doesn't preserve itself. We have to choose what to remember. Cambridge chose to remember Washington's arrival, marking the spot even after the tree died. Every marker, every preserved building, represents a decision that this mattered enough to keep.`,
    audioScript: `The Washington Elm is gone—it fell in 1923, weakened by age and storms. But I stand where it stood and tell visitors: here, on July 3, 1775, a Virginia planter became the commander of an American army.`,
  },
  {
    id: 'story-modern-cambridge-archaeology',
    town: { connect: { id: 'us-ma-cambridge' } },
    title: 'Uncovering the Siege',
    storyType: 'MODERN_VOICE',
    narratorName: 'Archaeologist',
    narratorRole: 'Cambridge Archaeological Survey',
    verificationStatus: 'VERIFIED',
    textVersion: `Archaeology in Cambridge means working around development. We have maybe two weeks when a foundation is dug before concrete goes in. But in those windows, we find the siege. Musket balls, uniform buttons, fragments of camp life. Near the Common, we found what appears to be a refuse pit from 1775—broken crockery, animal bones, a bent pewter spoon. These objects tell us about daily life in the camps: what soldiers ate, how they lived, the mundane reality behind the heroic narrative. The siege was eight months of cold, boredom, and uncertainty. The artifacts show that.`,
    audioScript: `Archaeology in Cambridge means working around development. We have maybe two weeks when a foundation is dug before concrete goes in. But in those windows, we find the siege.`,
  },
];

// Cambridge theme connections
export const cambridgeThemeConnections: Array<{ themeId: string; relevanceNote: string }> = [
  { themeId: 'citizen-soldiers', relevanceNote: 'Washington transformed militia into Continental Army here' },
  { themeId: 'military-innovation', relevanceNote: 'Siege operations and army organization developed at headquarters' },
  { themeId: 'liberty-freedom', relevanceNote: 'Command center for the fight for independence' },
  { themeId: 'women-revolution', relevanceNote: 'Martha Washington established patterns of camp support' },
  { themeId: 'enslaved-free-black', relevanceNote: 'Debates over Black soldiers began during siege planning' },
  { themeId: 'propaganda-communication', relevanceNote: 'Intelligence operations coordinated from headquarters' },
  { themeId: 'preservation-memory', relevanceNote: 'Longfellow House preserves Washington headquarters' },
  { themeId: 'loyalists-divided', relevanceNote: 'Loyalist properties like Vassall house confiscated for military use' },
  { themeId: 'economic-resistance', relevanceNote: 'Siege economics—supply chains and resource management' },
];

// Cambridge sources
export const cambridgeSources: Prisma.SourceCreateInput[] = [
  {
    id: 'source-longfellow-nps',
    type: 'INSTITUTIONAL',
    title: 'Longfellow House-Washington\'s Headquarters National Historic Site',
    publisherOrHolder: 'National Park Service',
    url: 'https://www.nps.gov/long/index.htm',
    credibilityTier: 'TIER1',
    notes: 'Primary interpretive authority for Washington\'s Cambridge headquarters',
  },
  {
    id: 'source-washington-papers',
    type: 'PRIMARY',
    title: 'The Papers of George Washington, Revolutionary War Series',
    publisherOrHolder: 'University of Virginia Press',
    credibilityTier: 'TIER1',
    notes: 'Definitive collection of Washington\'s correspondence during the siege',
  },
  {
    id: 'source-siege-boston-french',
    type: 'SECONDARY',
    title: 'The First Year of the American Revolution',
    publisherOrHolder: 'Allen French',
    credibilityTier: 'TIER1',
    notes: 'Detailed account of siege operations and command decisions',
  },
  {
    id: 'source-cambridge-historical',
    type: 'INSTITUTIONAL',
    title: 'Cambridge Historical Commission Archives',
    publisherOrHolder: 'City of Cambridge',
    url: 'https://www.cambridgema.gov/historic',
    credibilityTier: 'TIER1',
    notes: 'Local records and documentation of Revolutionary-era Cambridge',
  },
  {
    id: 'source-harvard-archives-rev',
    type: 'PRIMARY',
    title: 'Harvard University Archives: Revolutionary War Collection',
    publisherOrHolder: 'Harvard University',
    url: 'https://library.harvard.edu/archives',
    credibilityTier: 'TIER1',
    notes: 'Records of college operations during the siege',
  },
  {
    id: 'source-mccullough-1776',
    type: 'SECONDARY',
    title: '1776',
    publisherOrHolder: 'David McCullough / Simon & Schuster',
    credibilityTier: 'TIER2',
    notes: 'Popular history covering siege of Boston through evacuation',
  },
  {
    id: 'source-chernow-washington',
    type: 'SECONDARY',
    title: 'Washington: A Life',
    publisherOrHolder: 'Ron Chernow / Penguin Press',
    credibilityTier: 'TIER2',
    notes: 'Comprehensive biography with detailed Cambridge siege coverage',
  },
  {
    id: 'source-philbrick-bunker',
    type: 'SECONDARY',
    title: 'Bunker Hill: A City, A Siege, A Revolution',
    publisherOrHolder: 'Nathaniel Philbrick / Viking',
    credibilityTier: 'TIER2',
    notes: 'Covers Cambridge\'s role in siege context',
  },
  {
    id: 'source-cambridge-museum',
    type: 'INSTITUTIONAL',
    title: 'Cambridge Historical Society',
    publisherOrHolder: 'Cambridge Historical Society',
    url: 'https://cambridgehistory.org',
    credibilityTier: 'TIER2',
    notes: 'Local historical interpretation and collections',
  },
  {
    id: 'source-mass-historical-siege',
    type: 'PRIMARY',
    title: 'Massachusetts Historical Society: Siege Papers',
    publisherOrHolder: 'Massachusetts Historical Society',
    url: 'https://www.masshist.org',
    credibilityTier: 'TIER1',
    notes: 'Primary documents from siege period',
  },
  {
    id: 'source-washington-orders-cambridge',
    type: 'PRIMARY',
    title: 'General Orders, Cambridge Headquarters 1775-1776',
    publisherOrHolder: 'Library of Congress',
    url: 'https://www.loc.gov/collections/george-washington-papers',
    credibilityTier: 'TIER1',
    notes: 'Washington\'s daily orders during siege operations',
  },
  {
    id: 'source-continental-congress-cambridge',
    type: 'PRIMARY',
    title: 'Journals of the Continental Congress: Military Correspondence',
    publisherOrHolder: 'Library of Congress',
    credibilityTier: 'TIER1',
    notes: 'Congressional oversight of Cambridge operations',
  },
  {
    id: 'source-martha-washington-letters',
    type: 'PRIMARY',
    title: 'Martha Washington Letters',
    publisherOrHolder: 'Mount Vernon Ladies\' Association',
    url: 'https://www.mountvernon.org',
    credibilityTier: 'TIER1',
    notes: 'Correspondence from Cambridge headquarters period',
  },
  {
    id: 'source-heath-memoirs',
    type: 'PRIMARY',
    title: 'Memoirs of Major-General William Heath',
    publisherOrHolder: 'Original 1798 / Reprint editions',
    credibilityTier: 'TIER1',
    notes: 'First-hand account of siege operations from Massachusetts general',
  },
  {
    id: 'source-putnam-biography',
    type: 'SECONDARY',
    title: 'Israel Putnam: Pioneer, Ranger, and Major-General',
    publisherOrHolder: 'William Cutter',
    credibilityTier: 'TIER2',
    notes: 'Biography covering Cambridge service',
  },
  // TIER 3 — General reference
  {
    id: 'source-cambridge-wikipedia-siege',
    type: 'TERTIARY',
    title: 'Siege of Boston - Wikipedia',
    publisherOrHolder: 'Wikipedia',
    url: 'https://en.wikipedia.org/wiki/Siege_of_Boston',
    credibilityTier: 'TIER3',
    notes: 'General reference covering the siege period when Cambridge served as Continental Army headquarters. Cross-check with primary sources.',
  },
];

// Cambridge town links
export const cambridgeTownLinks: Prisma.TownLinkCreateInput[] = [
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ma-boston' } },
    linkType: 'SHARED_EVENT',
    reason: 'Cambridge headquarters directed the siege of Boston',
    weight: 95,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ma-lexington' } },
    linkType: 'ROUTE',
    reason: 'Midnight Ride route passed through; siege followed April 19 battles',
    weight: 85,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ma-concord' } },
    linkType: 'SHARED_EVENT',
    reason: 'Siege operations followed from Concord fight; intelligence coordination',
    weight: 80,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ma-arlington' } },
    linkType: 'SHARED_EVENT',
    reason: 'Siege lines connected through Menotomy positions',
    weight: 75,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ma-marblehead' } },
    linkType: 'SHARED_PERSON',
    reason: 'Glover\'s Marblehead regiment served in siege operations',
    weight: 80,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-va-mount-vernon' } },
    linkType: 'SHARED_PERSON',
    reason: 'Washington departed Mount Vernon for Cambridge command',
    weight: 85,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-pa-philadelphia' } },
    linkType: 'SHARED_EVENT',
    reason: 'Congress directed operations and appointed Washington from Philadelphia',
    weight: 80,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ny-fort-ticonderoga' } },
    linkType: 'SHARED_EVENT',
    reason: 'Knox\'s artillery expedition planned at Cambridge, departed for Ticonderoga',
    weight: 85,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ri-newport' } },
    linkType: 'SHARED_PERSON',
    reason: 'Greene\'s Rhode Island troops served under Cambridge command',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ct-new-haven' } },
    linkType: 'SHARED_PERSON',
    reason: 'Connecticut troops under Putnam served in siege',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-nh-portsmouth' } },
    linkType: 'SHARED_PERSON',
    reason: 'Sullivan\'s New Hampshire brigade served at Cambridge',
    weight: 70,
  },
  {
    fromTown: { connect: { id: 'us-ma-cambridge' } },
    toTown: { connect: { id: 'us-ny-brooklyn' } },
    linkType: 'COMPARISON',
    reason: 'Army formed at Cambridge would retreat through Brooklyn in 1776',
    weight: 65,
  },
];

// Cambridge routes
export const cambridgeRoutes: Prisma.RouteCreateInput[] = [
  {
    id: 'route-washington-hq-walk',
    name: 'Washington\'s Cambridge',
    description: 'Walking tour of Continental Army headquarters and siege command sites',
    totalMiles: 2.5,
  },
  {
    id: 'route-siege-command',
    name: 'Siege Command Sites',
    description: 'Key locations where siege of Boston was planned and directed',
    totalMiles: 3.0,
  },
];

// Cambridge route stops
export const cambridgeRouteStops: Array<{
  routeId: string;
  townId: string;
  stopOrder: number;
  notes: string;
}> = [
  {
    routeId: 'route-washington-hq-walk',
    townId: 'us-ma-cambridge',
    stopOrder: 1,
    notes: 'Cambridge Common - Washington Elm site where command was assumed',
  },
  {
    routeId: 'route-washington-hq-walk',
    townId: 'us-ma-cambridge',
    stopOrder: 2,
    notes: 'Longfellow House - Washington\'s headquarters during siege',
  },
  {
    routeId: 'route-washington-hq-walk',
    townId: 'us-ma-cambridge',
    stopOrder: 3,
    notes: 'Christ Church - Where officers worshipped during siege',
  },
  {
    routeId: 'route-siege-command',
    townId: 'us-ma-cambridge',
    stopOrder: 1,
    notes: 'Harvard Yard - Troop barracks and drilling ground',
  },
  {
    routeId: 'route-siege-command',
    townId: 'us-ma-cambridge',
    stopOrder: 2,
    notes: 'Longfellow House - Command headquarters',
  },
  {
    routeId: 'route-siege-command',
    townId: 'us-ma-boston',
    stopOrder: 3,
    notes: 'Dorchester Heights - Where Knox\'s artillery broke the siege',
  },
];
