/**
 * Seed Places, historical Events, and Stories for the 15 stub towns.
 * Run: npx tsx scripts/seed-stub-towns.ts [--dry-run]
 */

import "dotenv/config";
import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient({ log: ["error"] });
const DRY = process.argv.includes("--dry-run");

// ── Helpers ───────────────────────────────────────────────────────────────────

async function upsertPlace(data: Prisma.PlaceCreateInput) {
  if (DRY) { console.log(`  [place] ${data.name}`); return; }
  await prisma.place.upsert({
    where: { id: data.id as string },
    create: data,
    update: { name: data.name, description: data.description },
  });
}

async function upsertEvent(data: Prisma.EventCreateInput) {
  if (DRY) { console.log(`  [event] ${data.name}`); return; }
  await prisma.event.upsert({
    where: { id: data.id as string },
    create: data,
    update: { name: data.name, summary: data.summary },
  });
}

async function upsertStory(data: Prisma.StoryCreateInput) {
  if (DRY) { console.log(`  [story] ${data.title}`); return; }
  const existing = await prisma.story.findUnique({ where: { slug: data.slug as string } });
  if (existing) return;
  await prisma.story.create({ data });
}

// ── CT: Lebanon ───────────────────────────────────────────────────────────────

async function seedLebanon() {
  const id = "us-ct-lebanon";
  await upsertPlace({ id: "place-lebanon-war-office", name: "Jonathan Trumbull War Office", placeType: "GOVERNMENT", description: "The small wooden building where Governor Jonathan Trumbull conducted Connecticut's wartime business from 1775 to 1783. Trumbull was the only colonial governor to side with the Patriots and remain in office throughout the war. He met here with Washington, Rochambeau, and Lafayette, coordinating supplies, troops, and strategy. The building still stands on the Lebanon Green, maintained by the Connecticut Daughters of the American Revolution.", lat: 41.6375, lng: -72.2036, address: "169 W Town St, Lebanon, CT 06249", hours: "May–Oct, Sat–Sun 10am–4pm", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-lebanon-trumbull-house", name: "Jonathan Trumbull Sr. House", placeType: "HISTORIC_HOUSE", description: "The gambrel-roofed home of Governor Trumbull, built in 1740, which served as the nerve center of Connecticut's wartime government. Washington visited here in 1775 and 1781. The house reflects the modest prosperity of a Congregationalist merchant-farmer who became one of the most indispensable figures in the American supply chain. The Lebanon Historical Society manages the site.", lat: 41.6380, lng: -72.2033, address: "169 W Town St, Lebanon, CT 06249", hours: "May–Oct, Sat–Sun 10am–4pm", admission: "Small fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-lebanon-green", name: "Lebanon Green (French Army Encampment Site)", placeType: "LANDMARK", description: "The broad Lebanon Green, one of the longest town greens in New England, served as the encampment site for Rochambeau's French army during its march from Newport to Yorktown in June 1781. An estimated 5,000 French soldiers camped here for several days. The Green retains its 18th-century character and is surrounded by period buildings.", lat: 41.6374, lng: -72.2038, address: "Lebanon Green, Lebanon, CT 06249", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-lebanon-beaumont-farm", name: "Beaumont-Caulkins Farm Site", placeType: "LANDMARK", description: "The agricultural landscape around Lebanon sustained the Trumbull family's commercial and political operations. Governor Trumbull's store and warehouses in the town center were used to collect and distribute war materiel. Connecticut contributed more men and supplies proportionally than any other colony, and Lebanon was the administrative center of that effort.", lat: 41.6390, lng: -72.2050, address: "Lebanon, CT 06249", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-lebanon-trumbull-cemetery", name: "Trumbull Family Cemetery", placeType: "CEMETERY", description: "The burial ground containing graves of the Trumbull family, including members who served in the Continental Army. Jonathan Trumbull Sr. is buried at the First Congregational Church. The surrounding cemetery holds graves of Lebanon men who died in the Revolution, a roster that reflects the town's outsized contribution to the Patriot cause.", lat: 41.6362, lng: -72.2029, address: "Lebanon, CT 06249", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-lebanon-trumbull-governor", name: "Jonathan Trumbull Sides with Patriots", startDate: new Date("1775-07-01"), datePrecision: "MONTH", summary: "Trumbull's decision made Connecticut the only colony whose sitting royal-era governor backed the Revolution, providing continuity of government and administrative capacity that proved essential.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-lebanon-french-army-march", name: "Rochambeau's Army Camps on Lebanon Green", startDate: new Date("1781-06-18"), datePrecision: "DAY", summary: "The French army's transit through Connecticut demonstrated Trumbull's logistical achievement — he had organized a supply network capable of feeding and equipping a foreign army on the move.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-lebanon-washington-visit", name: "Washington Meets Trumbull in Lebanon", startDate: new Date("1775-10-18"), datePrecision: "MONTH", summary: "Washington's reliance on Trumbull demonstrated the personal networks that kept the Continental Army operational when Congress and the commissary system repeatedly failed.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-lebanon-brother-jonathan", slug: "story-lebanon-brother-jonathan", title: "Brother Jonathan: The Governor Who Kept the Army Alive", storyType: "HISTORICAL_VOICE", textVersion: "Washington called him 'Brother Jonathan.' The nickname stuck and eventually became slang for Connecticut itself — and then for America. Jonathan Trumbull Sr. was the only royal governor to side with the Patriots, and he did it at considerable personal cost. His mercantile business collapsed under the weight of wartime requisitions. He gave more than he charged. He requisitioned cattle, blankets, shoes, and powder from Connecticut farmers and merchants, promising payment that came slowly if at all. His ledgers from the Lebanon War Office record thousands of transactions — a monument to the unglamorous arithmetic of keeping an army in the field.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── IN: Vincennes ─────────────────────────────────────────────────────────────

async function seedVincennes() {
  const id = "us-in-vincennes";
  await upsertPlace({ id: "place-vincennes-clark-memorial", name: "George Rogers Clark National Memorial", placeType: "MONUMENT", description: "A neoclassical rotunda on the banks of the Wabash River marking the site of Fort Sackville, the British fort captured by George Rogers Clark in February 1779. Seven large murals inside depict the campaign. The memorial, built in 1931, occupies the approximate ground where Clark's 172 Virginia militiamen and French-Canadian volunteers accepted the surrender of Lieutenant Governor Henry Hamilton, ending British control of the Northwest Territory.", lat: 38.6768, lng: -87.5299, address: "401 S 2nd St, Vincennes, IN 47591", hours: "Daily 9am–5pm", admission: "Free (NPS)", website: "https://www.nps.gov/gero", town: { connect: { id } } });
  await upsertPlace({ id: "place-vincennes-fort-sackville-site", name: "Fort Sackville Site", placeType: "BATTLEFIELD", description: "The ground beneath the George Rogers Clark Memorial is the site of Fort Sackville, the British fortification that controlled the Wabash River valley and, by extension, British-allied Indigenous nations across the Northwest. Clark's capture of the fort in February 1779 — after a grueling 180-mile winter march through flooded prairies — gave the United States its claim to the territory that would become Ohio, Indiana, Illinois, Michigan, and Wisconsin.", lat: 38.6770, lng: -87.5298, address: "401 S 2nd St, Vincennes, IN 47591", hours: "Daily 9am–5pm", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-vincennes-old-cathedral", name: "Old Cathedral (Basilica of St. Francis Xavier)", placeType: "CHURCH", description: "The oldest Catholic church in Indiana, tracing its origins to the French missionary presence in Vincennes from the 1730s. During the Revolution, the French-Canadian population of Vincennes was divided in its loyalties; many supported Clark's Patriot cause, providing intelligence, supplies, and fighters. The current basilica, built 1826, stands near the site of the original mission church.", lat: 38.6757, lng: -87.5270, address: "205 Church St, Vincennes, IN 47591", hours: "Daily dawn to dusk (grounds)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-vincennes-indiana-territory-capitol", name: "Indiana Territory Capitol", placeType: "GOVERNMENT", description: "Vincennes served as the first capital of the Indiana Territory after the Northwest Ordinance of 1787, which was directly enabled by Clark's 1779 military campaign. The territorial capitol building, reconstructed on its original site, marks Vincennes's transition from contested frontier outpost to seat of American civil government — a transformation that began the night Clark's men crossed the flooded Wabash.", lat: 38.6745, lng: -87.5254, address: "Harrison St, Vincennes, IN 47591", hours: "Mon–Sat 9am–5pm", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-vincennes-wabash-river-crossing", name: "Wabash River Crossing Site", placeType: "LANDMARK", description: "In February 1779, George Rogers Clark's force spent five days crossing the flooded Wabash River bottomlands in chest-deep icy water to reach Vincennes. The crossing point — approximately where the river bends near the memorial — became legendary. Clark kept morale alive by having the drummers march at the front, beating cadence while soldiers waded. No account explains why they didn't turn back.", lat: 38.6780, lng: -87.5320, address: "Wabash River, Vincennes, IN", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-vincennes-clark-wabash-crossing", name: "Clark's Army Crosses the Wabash in Winter", startDate: new Date("1779-02-13"), datePrecision: "DAY", summary: "One of the most audacious military movements of the Revolution — 172 men in chest-deep floodwater for five days — succeeded because Clark understood that Hamilton would not expect an attack in February.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-vincennes-hamilton-surrender", name: "Lieutenant Governor Hamilton Surrenders Fort Sackville", startDate: new Date("1779-02-25"), datePrecision: "DAY", summary: "The capture of 'the Hair-Buyer' Hamilton — so called for his policy of paying Indigenous allies for American scalps — was a propaganda coup as well as a military one. It also established American sovereignty over the entire Northwest.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-vincennes-northwest-ordinance", name: "Northwest Ordinance Organizes Clark's Conquests", startDate: new Date("1787-07-13"), datePrecision: "DAY", summary: "The Ordinance was the most important domestic legislation of the Confederation period. It created the legal framework for admitting new states and, crucially, banned slavery north of the Ohio River.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-vincennes-hair-buyer", slug: "story-vincennes-hair-buyer", title: "The Hair-Buyer's Surrender", storyType: "HISTORICAL_VOICE", textVersion: "Henry Hamilton had a nickname that followed him to his grave: 'the Hair-Buyer.' British policy on the frontier paid Indigenous allies for American scalps, and Hamilton administered that policy from Fort Sackville with bureaucratic efficiency. When Clark's half-frozen men appeared out of the February floodwater, Hamilton couldn't believe it. The attack was impossible — everyone knew you didn't move an army through chest-deep floodwater in February. Hamilton had sent most of his garrison out on raids, expecting no threat until spring. Clark let the fort's defenders watch, from a distance, as he executed four of the captured raiders in full view of the walls. Hamilton surrendered the next morning.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── MA: Quincy ────────────────────────────────────────────────────────────────

async function seedQuincy() {
  const id = "us-ma-quincy";
  await upsertPlace({ id: "place-quincy-adams-birthplace-john", name: "John Adams Birthplace", placeType: "HISTORIC_HOUSE", description: "The saltbox farmhouse at 133 Franklin Street where John Adams was born on October 30, 1735. The house, built around 1681 by Adams's great-grandfather, is one of the oldest presidential birthplaces in the country. Adams grew up here and returned to it throughout his life. The house is managed by Adams National Historical Park and is open for guided tours.", lat: 42.2562, lng: -71.0125, address: "133 Franklin St, Quincy, MA 02169", hours: "Apr–Nov, daily 9am–5pm", admission: "Fee (NPS)", website: "https://www.nps.gov/adam", town: { connect: { id } } });
  await upsertPlace({ id: "place-quincy-adams-birthplace-jqa", name: "John Quincy Adams Birthplace", placeType: "HISTORIC_HOUSE", description: "The adjacent saltbox house at 141 Franklin Street where John Quincy Adams was born on July 11, 1767. The two birthplace houses stand within yards of each other, a physical expression of the Adams family dynasty. John Quincy was seven years old when his mother Abigail brought him to a hilltop to watch the Battle of Bunker Hill from a distance — an experience he recorded in his diary and never forgot.", lat: 42.2559, lng: -71.0127, address: "141 Franklin St, Quincy, MA 02169", hours: "Apr–Nov, daily 9am–5pm", admission: "Fee (NPS)", website: "https://www.nps.gov/adam", town: { connect: { id } } });
  await upsertPlace({ id: "place-quincy-peacefield", name: "Peacefield (Adams National Historical Park)", placeType: "HISTORIC_HOUSE", description: "The Georgian mansion John Adams purchased in 1787 and where he and Abigail lived after his return from Europe. Adams named it 'Peacefield' in honor of the Paris peace treaty he had negotiated. The house remained in the Adams family for four generations, eventually housing John Quincy Adams, Charles Francis Adams, and Henry Adams. It is the most complete surviving Adams family residence.", lat: 42.2517, lng: -71.0046, address: "135 Adams St, Quincy, MA 02169", hours: "Apr–Nov, daily 9am–5pm", admission: "Fee (NPS)", website: "https://www.nps.gov/adam", town: { connect: { id } } });
  await upsertPlace({ id: "place-quincy-first-parish-church", name: "United First Parish Church (Church of the Presidents)", placeType: "CHURCH", description: "The granite church where both John Adams and John Quincy Adams — the only father-and-son presidents before the Bushes — are buried in the family crypt beneath the sanctuary, alongside their wives Abigail and Louisa. The congregation dates to 1639. John Adams was a faithful but heterodox Unitarian parishioner. The church is still an active congregation and offers tours of the presidential crypt.", lat: 42.2510, lng: -71.0028, address: "1306 Hancock St, Quincy, MA 02169", hours: "Varies; crypt tours Apr–Nov", admission: "Small fee for crypt", website: "https://www.ufpc.org", town: { connect: { id } } });
  await upsertPlace({ id: "place-quincy-dorchester-heights", name: "Abigail Adams Historical Society", placeType: "MUSEUM", description: "Quincy's historical society and museum, which holds extensive collections related to the Adams family, Quincy granite quarrying, and the town's Revolutionary history. The nearby Quincy Homestead (circa 1686) is one of the oldest surviving structures in the region and was home to Abigail Adams's grandmother. The museum contextualizes how a small farming and quarrying community produced two presidents and a diplomatic dynasty.", lat: 42.2529, lng: -71.0023, address: "8 Adams St, Quincy, MA 02169", hours: "Tue–Sat 10am–4pm", admission: "Small fee", town: { connect: { id } } });

  await upsertEvent({ id: "event-quincy-adams-continental-congress", name: "John Adams Serves in the Continental Congress", startDate: new Date("1775-09-05"), datePrecision: "MONTH", summary: "Adams was among the most intellectually rigorous members of the Congress, drafting arguments for independence and insisting on legal and constitutional foundations for the break with Britain.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-quincy-abigail-bunker-hill", name: "Abigail Adams Watches the Battle of Bunker Hill", startDate: new Date("1775-06-17"), datePrecision: "DAY", summary: "Abigail's letter describing the battle — including the smoke visible from Penn's Hill — is one of the most vivid firsthand accounts of the engagement and a foundational document of women's participation in Revolutionary life.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-quincy-adams-paris-treaty", name: "Adams Negotiates the Treaty of Paris", startDate: new Date("1782-09-27"), datePrecision: "MONTH", summary: "Adams's insistence on fishing rights and explicit British recognition of American sovereignty shaped the treaty in ways that secured American independence more completely than France had intended.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-quincy-remember-the-ladies", slug: "story-quincy-remember-the-ladies", title: "Remember the Ladies", storyType: "HISTORICAL_VOICE", textVersion: "On March 31, 1776, Abigail Adams wrote to her husband John in Philadelphia: 'In the new code of laws which I suppose it will be necessary for you to make, I desire you would remember the ladies and be more generous and favorable to them than your ancestors.' John wrote back that he couldn't help but laugh. He told her the men knew better than to repeal their 'masculine systems.' She replied, drily, that she was more than a little saucy. The exchange is often cited as a moment of proto-feminism. What it actually shows is a marriage of intellectual equals who disagreed profoundly about the meaning of the liberty they were both fighting for.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── MA: Acton ─────────────────────────────────────────────────────────────────

async function seedActon() {
  const id = "us-ma-acton";
  await upsertPlace({ id: "place-acton-isaac-davis-house", name: "Isaac Davis House (Site)", placeType: "HISTORIC_HOUSE", description: "The site of the house where Captain Isaac Davis lived before leading the Acton Minutemen to Concord on April 19, 1775. Davis was a gunsmith by trade, and the Acton company was notably well-equipped — each man had a musket, bayonet, and cartridge box. Davis said farewell to his wife Hannah and their four children that morning and never returned. He was the first commissioned officer killed in the Concord fight.", lat: 42.4834, lng: -71.4466, address: "Davis Rd area, Acton, MA 01720", hours: "Open daily (exterior only)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-acton-minuteman-monument", name: "Acton Minuteman Monument", placeType: "MONUMENT", description: "A bronze statue of Captain Isaac Davis and James Hayward on Monument Square in South Acton, dedicated in 1851. The monument commemorates the two Acton men who died on April 19, 1775 — Davis at the North Bridge in the morning, Hayward in the afternoon fighting at the Concord road. The Acton company's extraordinary willingness to step forward — 'no one company is better than ours,' Davis reportedly said — is represented in the statue's determined posture.", lat: 42.4821, lng: -71.4268, address: "Monument Square, Acton, MA 01720", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-acton-isaac-davis-trail", name: "Isaac Davis Trail", placeType: "TRAIL", description: "A walking trail in Acton that follows the approximate route Captain Davis and the Acton Minutemen took on the morning of April 19, 1775, from the town center to join the column marching to Concord. The trail passes through conservation land and connects several sites associated with the Davis family. The Acton Conservation Trust maintains the trail.", lat: 42.4840, lng: -71.4340, address: "Acton, MA 01720", hours: "Open daily dawn to dusk", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-acton-south-acton-village", name: "South Acton Village Center", placeType: "LANDMARK", description: "The village center of South Acton, near where the Acton Minutemen assembled on the morning of April 19, 1775. The area retains 18th-century building stock and has been the focus of local preservation efforts. The Acton Historical Society maintains exhibits about the town's role in the opening day of the Revolution.", lat: 42.4710, lng: -71.4417, address: "Main St, South Acton, MA 01720", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-acton-acton-arboretum", name: "Acton Arboretum (Hosmer Grant Site)", placeType: "LANDMARK", description: "The Acton Arboretum occupies land near the original homestead grants of several of the men who fought on April 19, 1775, including the Hosmer family. Abner Hosmer was the other Acton man killed at the North Bridge — a private, the first private to die in the battle. The arboretum's trails pass through landscape essentially unchanged from the 18th century.", lat: 42.4850, lng: -71.4360, address: "Berry Ln, Acton, MA 01720", hours: "Open daily dawn to dusk", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-acton-davis-north-bridge", name: "Captain Isaac Davis Falls at the North Bridge", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "Davis was the first commissioned officer killed in the Revolution — the first of what would become hundreds of thousands. His wife Hannah became one of the war's early widows, left with four children and a farm.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-acton-hayward-afternoon-fight", name: "James Hayward Killed in Afternoon Fighting", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "The afternoon fighting along the Concord Road was deadlier than the morning engagement at the North Bridge, and Acton lost two men in a single day — a devastating toll for a small community.", verificationStatus: "ORAL_TRADITION", significanceWeight: 70, town: { connect: { id } } });
  await upsertEvent({ id: "event-acton-minutemen-muster", name: "Acton Minutemen Muster and March to Concord", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "The Acton company's quality — every man equipped with a bayonet, which was unusual — made them the most combat-ready of the Concord-area companies and influenced the decision to advance at the North Bridge.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-acton-hannah-davis", slug: "story-acton-hannah-davis", title: "Hannah Davis and the Morning He Left", storyType: "HISTORICAL_VOICE", textVersion: "Hannah Davis watched her husband Isaac leave before dawn on April 19, 1775. She was 31 years old. They had four children. Isaac was a gunsmith — he had spent months fitting out his company with the best equipment in the county. He kissed Hannah and the children and walked out the door. The tradition says she begged him not to go. He is said to have told her he was not a man who was afraid. By eight o'clock that morning he was dead at the North Bridge in Concord, the first commissioned officer killed in the American Revolution. Hannah Davis raised her four children alone, remarried once, and outlived her second husband too. She is buried in the South Acton cemetery.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── MA: Lincoln ───────────────────────────────────────────────────────────────

async function seedLincoln() {
  const id = "us-ma-lincoln";
  await upsertPlace({ id: "place-lincoln-hartwell-tavern", name: "Hartwell Tavern (Minuteman National Historical Park)", placeType: "TAVERN", description: "A surviving 18th-century tavern along the Battle Road in Lincoln, maintained by the National Park Service as a living history site. The Hartwell family ran the tavern as a gathering point for the community; on April 19, 1775, militiamen rallied here before joining the fight. NPS interpreters in period dress demonstrate tavern life and discuss the Battle Road. The building is one of the best-preserved structures on the original 1775 route.", lat: 42.4412, lng: -71.3477, address: "Hartwell Tavern, Battle Rd, Lincoln, MA 01773", hours: "Daily, late Apr–Oct 9am–5pm; winter hours vary", admission: "Free (NPS)", website: "https://www.nps.gov/mima", town: { connect: { id } } });
  await upsertPlace({ id: "place-lincoln-parkers-revenge", name: "Parker's Revenge Site", placeType: "BATTLEFIELD", description: "The site along the Battle Road in Lincoln where Captain John Parker's Lexington company — nearly destroyed in the morning — ambushed the retreating British column in the afternoon of April 19, 1775. Parker had reorganized his battered men and marched them to intercept the British route. The ambush, while not decisive, was Parker's act of retribution for the morning killing of his men on Lexington Green. An NPS wayside marker interprets the site.", lat: 42.4431, lng: -71.3446, address: "Battle Rd, Lincoln, MA 01773", hours: "Open daily", admission: "Free (NPS)", town: { connect: { id } } });
  await upsertPlace({ id: "place-lincoln-battle-road-trail", name: "Battle Road Trail — Lincoln Section", placeType: "TRAIL", description: "The five-mile Battle Road Trail through Minuteman National Historical Park runs through Lincoln, following the original Bay Road along which British troops marched to Concord on April 19, 1775, and retreated under fire in the afternoon. The Lincoln section passes through wetlands and woodlands characteristic of the 18th-century landscape. Wayside exhibits mark ambush positions and skirmish sites.", lat: 42.4436, lng: -71.3489, address: "Battle Rd, Lincoln, MA 01773", hours: "Open daily dawn to dusk", admission: "Free (NPS)", website: "https://www.nps.gov/mima", town: { connect: { id } } });
  await upsertPlace({ id: "place-lincoln-bloody-angle", name: "Bloody Angle", placeType: "BATTLEFIELD", description: "A sharp bend in the Battle Road near the Lincoln-Concord line where Minutemen ambushed the British column to devastating effect during the afternoon retreat on April 19, 1775. Colonial militiamen firing from behind stone walls and trees at the angle inflicted some of the heaviest British casualties of the day. The site is marked and interpreted within Minuteman National Historical Park.", lat: 42.4465, lng: -71.3316, address: "Battle Rd near Concord-Lincoln line, Lincoln, MA 01773", hours: "Open daily", admission: "Free (NPS)", town: { connect: { id } } });
  await upsertPlace({ id: "place-lincoln-deCordova-museum", name: "deCordova Sculpture Park", placeType: "MUSEUM", description: "While primarily a contemporary art museum, the deCordova's grounds in Lincoln encompass land that was active farmland during the Revolution. The museum's permanent collection includes works referencing the town's historical identity. Lincoln's preservation of open land reflects the same conservation ethic that maintained the Battle Road landscape.", lat: 42.4275, lng: -71.3181, address: "51 Sandy Pond Rd, Lincoln, MA 01773", hours: "Wed–Sun 10am–5pm", admission: "Fee", website: "https://www.decordova.org", town: { connect: { id } } });

  await upsertEvent({ id: "event-lincoln-british-march-through", name: "British Column Marches Through Lincoln", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "Lincoln's geography — a long stretch of open road flanked by wetlands and woods — made it ideal ambush country on the return, and the town's militiamen exploited every stone wall.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-lincoln-bloody-angle-ambush", name: "Colonial Militia Ambush at the Bloody Angle", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "The Bloody Angle was the single most costly stretch of the entire retreat for the British — more men fell here than at any other point on the road from Concord to Lexington.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-lincoln-parker-revenge", name: "Captain Parker's Revenge at Lincoln", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "Parker's decision to pursue the British column after the morning's losses transformed Lexington's story from a defeat into an act of resistance.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });

  await upsertStory({ id: "story-lincoln-road-fight", slug: "story-lincoln-road-fight", title: "The Road Itself Fought Back", storyType: "HISTORICAL_VOICE", textVersion: "The British had been told the colonials wouldn't stand and fight. After Lexington Green and Concord's North Bridge, the evidence was mixed. But on the road back to Boston — the twelve miles from Concord through Lincoln and Lexington — the evidence became conclusive. Every stone wall was a fighting position. Every bend in the road was an ambush. The Lincoln section of the road had all of these things in abundance, and the militiamen from Lincoln and the surrounding towns knew every angle. By the time the column reached Lexington, it had taken more than two hundred casualties. The road itself had fought back.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── MA: Bedford ───────────────────────────────────────────────────────────────

async function seedBedford() {
  const id = "us-ma-bedford";
  await upsertPlace({ id: "place-bedford-museum", name: "Bedford Museum and Cultural Center", placeType: "MUSEUM", description: "The museum holds the Bedford Flag, generally considered the oldest surviving flag associated with an American military unit. The flag — crimson silk with a painted arm holding a sword, Latin motto, and the date 1737 — was carried by the Bedford militia company and is traditionally said to have been borne on April 19, 1775. The museum's Revolutionary War collection contextualizes Bedford's role in the opening of the war.", lat: 42.4917, lng: -71.2742, address: "27 Mudge Way, Bedford, MA 01730", hours: "Wed–Sun 1–5pm", admission: "Free", website: "https://www.bedfordma.gov/bedford-museum", town: { connect: { id } } });
  await upsertPlace({ id: "place-bedford-town-common", name: "Bedford Town Common", placeType: "LANDMARK", description: "The town common where Bedford's Minuteman company assembled in the pre-dawn hours of April 19, 1775. A marker on the common commemorates the muster and the march to Concord. The common retains its 18th-century character as the civic center of the town. Each April 19, the town holds a Patriots' Day ceremony here.", lat: 42.4906, lng: -71.2747, address: "The Common, Bedford, MA 01730", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-bedford-wilson-house", name: "Captain John Wilson Homestead Area", placeType: "LANDMARK", description: "The area near the homestead of Captain John Wilson, who led Bedford's Minuteman company on April 19, 1775. Wilson marched his men to Concord in time for the North Bridge engagement. The homestead site marks the network of farms and families that constituted Bedford's military community in 1775.", lat: 42.4898, lng: -71.2754, address: "Bedford, MA 01730", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-bedford-minuteman-statue", name: "Bedford Minuteman Statue", placeType: "MONUMENT", description: "A bronze statue of a Minuteman on Bedford's town common, commemorating the men who responded to the April 19 alarm. The figure carries a musket and wears civilian clothing with militia equipment — the standard appearance of New England militiamen in 1775. Bedford's contribution to the North Bridge fight was part of the coordinated response of a dozen towns that had drilled together in the months before Lexington.", lat: 42.4905, lng: -71.2745, address: "The Common, Bedford, MA 01730", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-bedford-town-hall", name: "Bedford Town Hall", placeType: "GOVERNMENT", description: "The current town hall stands near the site of the original meeting house where Bedford's townspeople debated colonial policy in the early 1770s and where the Minuteman company was officially organized under the Massachusetts Provincial Congress's call for armed preparation. Town meetings were the constitutional basis for colonial resistance, and Bedford's records from 1774–1775 document the town's deliberate preparation for war.", lat: 42.4912, lng: -71.2744, address: "10 Mudge Way, Bedford, MA 01730", hours: "Mon–Fri 8:30am–4:30pm", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-bedford-flag-north-bridge", name: "Bedford Flag Carried to the North Bridge", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "If the Bedford Flag was indeed carried on April 19, 1775 — the historical record is suggestive but not conclusive — it is the oldest surviving battle flag from American military history.", verificationStatus: "ORAL_TRADITION", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-bedford-minutemen-muster-april", name: "Bedford Minutemen Muster Before Dawn", startDate: new Date("1775-04-19"), datePrecision: "DAY", summary: "Bedford's rapid response — assembled and marching before dawn — was typical of the towns in the Concord-area network that had been drilling and organizing for months under the Provincial Congress's guidelines.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-bedford-provincial-congress-drills", name: "Bedford Organizes Minuteman Company", startDate: new Date("1774-10-01"), datePrecision: "MONTH", summary: "The Provincial Congress's call for Minuteman companies in October 1774 transformed the ad hoc militia system into a standing rapid-response force — a deliberate preparation for armed resistance that made April 19 possible.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-bedford-oldest-flag", slug: "story-bedford-oldest-flag", title: "The Oldest Flag", storyType: "HISTORICAL_VOICE", textVersion: "The Bedford Flag is made of crimson silk. It is painted, not embroidered, with an armored arm holding a sword emerging from clouds — a traditional European heraldic device. The motto reads Vince aut Morire: Conquer or Die. The flag dates to approximately 1737; it predates the Revolution by nearly forty years. It was a militia company flag before it was an American one. After April 19, 1775, the Nathaniel Page family kept it for generations, folded in a trunk, before donating it to the Bedford Public Library in 1885. It now lives in a climate-controlled case in the Bedford Museum. It is the oldest surviving flag associated with an American military unit — older than the country it outlasted.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── ME: Machias ───────────────────────────────────────────────────────────────

async function seedMachias() {
  const id = "us-me-machias";
  await upsertPlace({ id: "place-machias-burnham-tavern", name: "Burnham Tavern", placeType: "TAVERN", description: "The oldest surviving building in eastern Maine, built in 1770, where Machias patriots met on June 11, 1775, to plan the capture of the British armed schooner HMS Margaretta. The tavern was the community's meeting house, courthouse, and gathering place. After the battle, the wounded British captain James Moore was brought here and died of his injuries. The tavern is maintained by the Daughters of the American Revolution and is open for tours.", lat: 44.7170, lng: -67.4627, address: "14 Free St, Machias, ME 04654", hours: "June–Sept, Mon–Fri 9am–5pm", admission: "Small fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-machias-obrien-memorial", name: "O'Brien Memorial, Machias River", placeType: "MONUMENT", description: "A monument near the Machias River commemorating Jeremiah O'Brien and the other men who captured HMS Margaretta on June 12, 1775 — the first naval battle of the American Revolution. The O'Brien family, originally Irish immigrants, had been in Machias for years; Jeremiah was one of five brothers who participated in the capture. The monument marks the town's claim to the title 'Lexington of the Sea.'", lat: 44.7154, lng: -67.4628, address: "Court St, Machias, ME 04654", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-machias-fort-obrien", name: "Fort O'Brien State Historic Site", placeType: "BATTLEFIELD", description: "A fortification site near the mouth of the Machias River built to defend against British counterattacks after the Margaretta capture. The fort, named for Jeremiah O'Brien, was attacked and rebuilt multiple times during the war. The earthwork remains are partially visible. The site is maintained by Maine Bureau of Parks and Lands and offers views of the coastal geography that made Machias strategically important for privateering.", lat: 44.6671, lng: -67.3883, address: "Fort Rd, Machiasport, ME 04655", hours: "Memorial Day–Labor Day, daily 9am–sunset", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-machias-machias-river", name: "Machias River and Bay", placeType: "LANDMARK", description: "The Machias River and the bay it empties into formed the strategic geography of the June 12, 1775 naval battle. The Margaretta was anchored in the river; the Unity and other boats attacked from the bay. The river has changed relatively little in character. The tidal falls that gave the town its name — 'Machias' from the Passamaquoddy for 'bad little falls' — are still visible at the appropriate tide.", lat: 44.7100, lng: -67.4550, address: "Machias River, Machias, ME 04654", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-machias-historical-society", name: "Machiasport Historical Society", placeType: "MUSEUM", description: "The historical society maintains collections related to the Battle of Machias, the O'Brien family, and the region's role in the Revolution. The collection includes documents, artifacts, and records from the privateering operations Machias supported throughout the war. The society operates out of the Gates House (c. 1807), a federal-style house that reflects the post-war prosperity the Revolution helped create.", lat: 44.7015, lng: -67.3852, address: "Gates House, Machiasport, ME 04655", hours: "July–Aug, Tue–Sat 12:30–4:30pm", admission: "Small fee", town: { connect: { id } } });

  await upsertEvent({ id: "event-machias-margaretta-capture", name: "HMS Margaretta Captured — First Naval Battle of the Revolution", startDate: new Date("1775-06-12"), datePrecision: "DAY", summary: "The Machias action was the first naval battle of the Revolution — two months after Lexington and Concord, before the Continental Navy existed, armed civilians in fishing boats seized a British naval vessel.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-machias-tavern-meeting", name: "Patriots Meet at Burnham Tavern to Plan the Attack", startDate: new Date("1775-06-11"), datePrecision: "DAY", summary: "The Burnham Tavern meeting demonstrates that the decision to attack a Royal Navy vessel was not impulsive — it was a deliberate community decision, made collectively by men who understood the consequences.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-machias-obrien-privateers", name: "Machias Privateers Operate Throughout the War", startDate: new Date("1776-01-01"), datePrecision: "YEAR", summary: "Machias's position at the northeastern frontier of the colonies — remote from British naval bases — made it an ideal base for privateering, which significantly disrupted British coastal supply lines.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-machias-pitchforks", slug: "story-machias-pitchforks", title: "Pitchforks Against a Navy", storyType: "HISTORICAL_VOICE", textVersion: "The men who captured HMS Margaretta were not soldiers. They were fishermen, lumber workers, and small farmers from one of the remotest corners of the colonies. Their weapons included pitchforks. The British officer they killed was a professional naval captain commanding a vessel of the Royal Navy. The disparity was absurd. What the Machias men had was the tidal geography of the bay, boats they knew how to handle, and the conviction — sharpened by the news from Lexington that had arrived just weeks before — that the time for compliance was over. They called it the Lexington of the Sea. The name stuck.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── NC: Edenton ───────────────────────────────────────────────────────────────

async function seedEdenton() {
  const id = "us-nc-edenton";
  await upsertPlace({ id: "place-edenton-barker-house", name: "Penelope Barker House", placeType: "HISTORIC_HOUSE", description: "The home of Penelope Barker, who organized and hosted the Edenton Tea Party on October 25, 1774. Barker collected signatures from 51 women who pledged to boycott British goods — tea, cloth, and other taxed items. The document they signed was among the first political statements by organized women in American history. The house, built in the 1780s, is maintained by the Edenton Historical Commission and serves as a visitor center.", lat: 36.0584, lng: -76.6081, address: "505 S Broad St, Edenton, NC 27932", hours: "Tue–Sat 10am–4pm", admission: "Small fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-edenton-courthouse", name: "Chowan County Courthouse", placeType: "GOVERNMENT", description: "Built in 1767, the Chowan County Courthouse is the oldest surviving courthouse in North Carolina and one of the finest Georgian public buildings in the American South. It was the seat of Chowan County government during the Revolution and the civic backdrop against which the Edenton Tea Party took place. The building served as a meeting place for Patriot organizing in northeastern North Carolina.", lat: 36.0576, lng: -76.6076, address: "117 E King St, Edenton, NC 27932", hours: "Mon–Fri 8am–5pm", admission: "Free (exterior)", town: { connect: { id } } });
  await upsertPlace({ id: "place-edenton-st-pauls-church", name: "St. Paul's Episcopal Church", placeType: "CHURCH", description: "The oldest parish in North Carolina, St. Paul's congregation dates to 1701. The current brick church, begun in 1736, was used as a barracks and hospital during both the Revolutionary and Civil Wars. Several of the men and women associated with the Edenton Tea Party are buried in the churchyard, including Penelope Barker's husband Thomas. The church is still active and offers guided tours.", lat: 36.0570, lng: -76.6075, address: "101 W Church St, Edenton, NC 27932", hours: "Mon–Fri 9am–noon", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-edenton-teapot-monument", name: "Edenton Teapot Monument", placeType: "MONUMENT", description: "A large bronze teapot on a cannon, situated near the waterfront, commemorating the 1774 Edenton Tea Party. The monument acknowledges one of the earliest organized acts of political protest by American women. The imagery of a teapot mounted on a cannon — domestic and martial combined — captures the unusual nature of the event: women using the language of household consumption as political action.", lat: 36.0583, lng: -76.6078, address: "Water St, Edenton, NC 27932", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-edenton-historic-waterfront", name: "Edenton Historic Waterfront", placeType: "LANDMARK", description: "Edenton's colonial-era waterfront on the Albemarle Sound was the commercial center of the town during the 18th century. Ships carrying tobacco and lumber left from these wharves; British goods arrived on the same route. The waterfront retains much of its 18th-century scale. The town's position as a colonial port made the boycott meaningful — Edenton's women were pledging to stop consuming goods that flowed through the harbor they could see from their homes.", lat: 36.0575, lng: -76.6058, address: "Water St, Edenton, NC 27932", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-edenton-tea-party", name: "Edenton Tea Party — Women's Political Pledge", startDate: new Date("1774-10-25"), datePrecision: "DAY", summary: "The Edenton Tea Party was the first recorded organized political action by American women. The signers were not anonymous — their names and a sketch of the gathering appeared in a London newspaper, where it was mocked. The mockery did not stop them.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-edenton-north-carolina-congress", name: "North Carolina Provincial Congress Meets", startDate: new Date("1774-08-25"), datePrecision: "MONTH", summary: "North Carolina's Provincial Congress was one of the first extralegal governing bodies in the colonies, establishing the precedent for the Continental Congress and demonstrating that colonial political infrastructure could function outside British authorization.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });
  await upsertEvent({ id: "event-edenton-british-raid-1778", name: "British Raid the Albemarle Sound Region", startDate: new Date("1778-05-01"), datePrecision: "MONTH", summary: "British raids on the Albemarle Sound demonstrated that the Revolution's costs were not limited to battlefields — civilian communities throughout the coastal South bore significant losses.", verificationStatus: "VERIFIED", significanceWeight: 60, town: { connect: { id } } });

  await upsertStory({ id: "story-edenton-london-cartoon", slug: "story-edenton-london-cartoon", title: "The London Cartoon", storyType: "HISTORICAL_VOICE", textVersion: "When the Edenton women's resolution reached London, a cartoonist named Philip Dawe published a satirical print. It showed the women signing their document in a disorderly scene — babies on the floor, a dog drinking from a teapot, the women dressed provocatively. The cartoon was meant to mock them: look at these women playing politics. In Edenton, people had the same reaction as the Bostonians did when their tea party was ridiculed: they kept going. Penelope Barker, whose name headed the document, was 51 years old when she organized the pledge. She had been widowed twice. She was not playing.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── NC: Halifax ───────────────────────────────────────────────────────────────

async function seedHalifax() {
  const id = "us-nc-halifax";
  await upsertPlace({ id: "place-halifax-historic-site", name: "Historic Halifax State Historic Site", placeType: "GOVERNMENT", description: "A preserved 18th-century townscape on the Roanoke River, including the site where the Halifax Resolves were adopted on April 12, 1776. The site encompasses the remains of the colonial courthouse, jail, tavern, and several private homes. The Halifax Resolves — the first official government call for American independence — were passed here six weeks before the Continental Congress acted. Guided tours available.", lat: 36.3254, lng: -77.5893, address: "25 St David St, Halifax, NC 27839", hours: "Tue–Sat 9am–5pm", admission: "Free (state historic site)", website: "https://www.historicsites.nc.gov/sites/halifax", town: { connect: { id } } });
  await upsertPlace({ id: "place-halifax-constitution-house", name: "Constitution House Site (Resolves Passage Site)", placeType: "LANDMARK", description: "The site of the building where the Fourth Provincial Congress of North Carolina met and passed the Halifax Resolves on April 12, 1776. The structure no longer stands, but the site is marked and interpreted within the Historic Halifax complex. A monument commemorates the passage of the Resolves — the first formal governmental action calling on the Continental Congress to declare independence.", lat: 36.3258, lng: -77.5892, address: "St David St, Halifax, NC 27839", hours: "Open daily (exterior)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-halifax-owens-house", name: "Owens House", placeType: "HISTORIC_HOUSE", description: "One of the surviving 18th-century structures within the Historic Halifax complex, demonstrating the character of the colonial town that hosted the Fourth Provincial Congress. The house reflects the material life of prosperous Roanoke River valley residents — tobacco planters and merchants whose economic interests were intertwined with colonial trade policy.", lat: 36.3251, lng: -77.5890, address: "25 St David St, Halifax, NC 27839", hours: "Tue–Sat 9am–5pm (guided tours)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-halifax-roanoke-river", name: "Roanoke River at Halifax", placeType: "LANDMARK", description: "The Roanoke River flows past Halifax, connecting the Piedmont backcountry to the Albemarle Sound. The river was Halifax's commercial artery — tobacco and naval stores moved downstream to port towns; manufactured goods moved up. The geography that made Halifax a commercial center also made it a natural gathering place for the provincial political community that assembled there in April 1776.", lat: 36.3240, lng: -77.5870, address: "Roanoke River, Halifax, NC 27839", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-halifax-clerk-office", name: "Halifax County Clerk's Office (c. 1832)", placeType: "GOVERNMENT", description: "The Halifax County Clerk's office, while postdating the Revolution, stands on the institutional ground of Halifax County's colonial government. The county records maintained here include documents from the Revolutionary period that trace the legal and political framework through which Halifax County organized resistance to British authority. The building is near the site of the original colonial courthouse.", lat: 36.3263, lng: -77.5912, address: "Halifax, NC 27839", hours: "Mon–Fri 8am–5pm", admission: "Free (exterior)", town: { connect: { id } } });

  await upsertEvent({ id: "event-halifax-resolves", name: "Halifax Resolves: First Official Call for Independence", startDate: new Date("1776-04-12"), datePrecision: "DAY", summary: "North Carolina was the first colony whose official government body — not a pamphleteer or a mob — called explicitly for independence. The Halifax Resolves gave North Carolina's delegation to the Continental Congress the authority to vote for separation from Britain.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-halifax-nc-constitution", name: "North Carolina Adopts Its First Constitution", startDate: new Date("1776-12-18"), datePrecision: "DAY", summary: "North Carolina's 1776 Constitution established one of the most democratic state governments of the founding era — including low property requirements for voting and a strong legislature — reflecting the Piedmont communities' skepticism of concentrated power.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-halifax-provincial-congress", name: "Fourth Provincial Congress Convenes in Halifax", startDate: new Date("1776-04-04"), datePrecision: "DAY", summary: "The Provincial Congress represented the transition from colonial government to revolutionary government — the moment when North Carolina's political community formally replaced royal authority with its own.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-halifax-eight-weeks", slug: "story-halifax-eight-weeks", title: "Eight Weeks Before Philadelphia", storyType: "HISTORICAL_VOICE", textVersion: "On April 12, 1776, the town of Halifax, North Carolina had fewer than a thousand residents. Most people in Britain had never heard of it. Most people in the other colonies hadn't either. But the Fourth Provincial Congress meeting here that day did something no other official government body had done: they voted to instruct their delegates to the Continental Congress to vote for independence. Eight weeks later, on June 7, Richard Henry Lee of Virginia introduced the formal motion in Philadelphia. On July 4, the Congress voted. North Carolina had already answered the question.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── NH: New Castle ────────────────────────────────────────────────────────────

async function seedNewCastle() {
  const id = "us-nh-new-castle";
  await upsertPlace({ id: "place-new-castle-fort-constitution", name: "Fort Constitution Historic Site", placeType: "BATTLEFIELD", description: "The site of Fort William and Mary, the British fortification raided by New Hampshire patriots on December 14–15, 1774 — four months before Lexington and Concord. John Sullivan and John Langdon led the raids, seizing 100 barrels of gunpowder and 16 cannon. The powder was used at the Battle of Bunker Hill. The fort was subsequently renamed Fort Constitution. The walls of the fort are partially preserved and maintained by the state of New Hampshire.", lat: 43.0695, lng: -70.7159, address: "Fort Constitution Rd, New Castle, NH 03854", hours: "Daily dawn to dusk (exterior grounds)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-new-castle-island", name: "New Castle Island", placeType: "LANDMARK", description: "New Castle is New Hampshire's only island municipality — a small island in Portsmouth Harbor connected by bridges. Its position at the harbor entrance made Fort William and Mary the gateway to Portsmouth, New Hampshire's most important colonial port. The island retains its colonial-era character, with 18th and 19th century houses lining narrow streets.", lat: 43.0695, lng: -70.7159, address: "New Castle, NH 03854", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-new-castle-wentworth-hotel", name: "Wentworth by the Sea Hotel (Governor's Castle Site)", placeType: "LANDMARK", description: "Near the site of colonial Governor John Wentworth's summer residence on New Castle Island. Wentworth fled New Hampshire in August 1775 after Patriot pressure made his position untenable — he was the royal governor whose powder magazine had been raided just months before. His departure ended royal government in New Hampshire. The grand hotel that now occupies the area reflects the island's continued role as an elite destination.", lat: 43.0638, lng: -70.7206, address: "588 Wentworth Rd, New Castle, NH 03854", hours: "Hotel; grounds visible from road", admission: "N/A", town: { connect: { id } } });
  await upsertPlace({ id: "place-new-castle-fort-dearborn", name: "Fort Dearborn Site (Great Island Common)", placeType: "LANDMARK", description: "Great Island Common, now a public park, includes the site of Fort Dearborn, which was built on the remains of earlier fortifications to defend Portsmouth Harbor during the later years of the Revolution. The common provides views of the harbor entrance that Fort William and Mary had guarded and gives a sense of the strategic geography that made New Castle the key to New Hampshire's coast.", lat: 43.0710, lng: -70.7135, address: "Great Island Common, New Castle, NH 03854", hours: "Open daily dawn to dusk", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-new-castle-congregational-church", name: "First Congregational Church of New Castle", placeType: "CHURCH", description: "The congregation on New Castle Island dates to the 1650s. During the Revolution, the church was the community anchor for a small island town deeply divided over colonial politics. The church building, several times rebuilt, stands on the same ground where the community debated and acted on the central questions of colonial resistance.", lat: 43.0695, lng: -70.7159, address: "New Castle, NH 03854", hours: "Service times vary", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-new-castle-fort-william-mary-raid", name: "Raid on Fort William and Mary — First Military Seizure of British Property", startDate: new Date("1774-12-14"), datePrecision: "DAY", summary: "The New Castle raid was the first armed seizure of British military property in the colonies — five months before Lexington, by men who knew exactly what they were doing and why.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-new-castle-wentworth-flight", name: "Governor Wentworth Flees New Hampshire", startDate: new Date("1775-08-24"), datePrecision: "DAY", summary: "Wentworth's flight ended royal government in New Hampshire, making it the first colony to effectively establish self-government — a precedent that influenced subsequent colonial decisions.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-new-castle-bunker-hill-powder", name: "Fort William and Mary Powder Used at Bunker Hill", startDate: new Date("1775-06-17"), datePrecision: "DAY", summary: "The connection between the December raid and the June battle is one of the clearest examples of the colonies' deliberate military preparation — the Fort William and Mary seizure was not impulsive raiding but strategic supply acquisition.", verificationStatus: "ORAL_TRADITION", significanceWeight: 80, town: { connect: { id } } });

  await upsertStory({ id: "story-new-castle-december-raid", slug: "story-new-castle-december-raid", title: "Before Lexington", storyType: "HISTORICAL_VOICE", textVersion: "The history books say the Revolution began at Lexington and Concord on April 19, 1775. But on December 14, 1774, four months earlier, four hundred New Hampshire men rowed out to Fort William and Mary on New Castle Island and took it. They overpowered six British soldiers without killing anyone. They took 100 barrels of powder. They came back the next day and took the cannon. The garrison commander filed a formal protest. He had been overpowered and he wanted it on the record. Nobody court-martialed anyone. Nobody in London seemed to understand what had just happened: the colonists had taken the fort.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── NY: Rome / Oriskany ───────────────────────────────────────────────────────

async function seedOriskany() {
  const id = "us-ny-oriskany";
  await upsertPlace({ id: "place-oriskany-battlefield", name: "Oriskany Battlefield State Historic Site", placeType: "BATTLEFIELD", description: "The site of the Battle of Oriskany on August 6, 1777, one of the bloodiest engagements of the Revolution. Tryon County militia under Brigadier General Nicholas Herkimer were ambushed by a Loyalist and Iroquois force in a ravine near Oriskany Creek. Herkimer was mortally wounded early in the battle but continued to command from beneath a tree, smoking his pipe. The battle relieved pressure on Fort Stanwix. A monument and interpretive center mark the site.", lat: 43.1476, lng: -75.3496, address: "7801 State Route 69, Oriskany, NY 13424", hours: "May–Oct, Mon–Sat 9am–5pm, Sun 1–5pm", admission: "Free (state historic site)", town: { connect: { id } } });
  await upsertPlace({ id: "place-oriskany-fort-stanwix", name: "Fort Stanwix National Monument", placeType: "BATTLEFIELD", description: "A fully reconstructed Revolutionary War fort in Rome, New York — the destination Herkimer's relief column was marching toward when ambushed at Oriskany. Fort Stanwix was besieged by British forces under General Barry St. Leger for three weeks in August 1777. The garrison held, and the combined pressure of Oriskany and a feint by Benedict Arnold caused St. Leger to retreat. The fort is maintained by the National Park Service.", lat: 43.2104, lng: -75.4559, address: "112 E Park St, Rome, NY 13440", hours: "Daily 9am–5pm (seasonal)", admission: "Free (NPS)", website: "https://www.nps.gov/fost", town: { connect: { id } } });
  await upsertPlace({ id: "place-oriskany-herkimer-monument", name: "Herkimer Monument, Oriskany Battlefield", placeType: "MONUMENT", description: "An obelisk monument at the Oriskany Battlefield site commemorating the fallen, including General Nicholas Herkimer, who died of his wounds nine days after the battle. Herkimer, a German-American farmer and militia general, embodied the divided loyalties of the Mohawk Valley: his own brother was a Loyalist officer in the force that ambushed him. The monument is the focal point of annual commemorations.", lat: 43.1476, lng: -75.3496, address: "7801 State Route 69, Oriskany, NY 13424", hours: "Same as battlefield", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-oriskany-herkimer-home", name: "Herkimer Home State Historic Site", placeType: "HISTORIC_HOUSE", description: "The Georgian mansion where General Nicholas Herkimer lived and where he died of his wounds on August 16, 1777, ten days after the Battle of Oriskany. The house reflects the prosperity of the German-American farming community that settled the Mohawk Valley. Herkimer's home was the gathering point for the Tryon County militia before the relief march; it became the site of his death shortly after.", lat: 43.0167, lng: -74.9842, address: "200 State Route 169, Little Falls, NY 13365", hours: "May–Oct, Tue–Sat 10am–5pm", admission: "Free (state historic site)", town: { connect: { id } } });
  await upsertPlace({ id: "place-oriskany-creek", name: "Oriskany Creek Ravine", placeType: "LANDMARK", description: "The ravine where the Battle of Oriskany took place, near where Oriskany Creek crosses State Route 69. The Loyalist and Iroquois ambush was positioned at a causeway over the creek bottom; the militia column was caught crossing a log bridge in the ravine. The terrain has changed somewhat but the creek and the general topography that determined the battle's character are still present.", lat: 43.1490, lng: -75.3505, address: "State Route 69, Oriskany, NY 13424", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-oriskany-battle", name: "Battle of Oriskany — The Bloodiest Engagement of the Revolution", startDate: new Date("1777-08-06"), datePrecision: "DAY", summary: "Oriskany was the bloodiest battle of the Revolution per capita — nearly half the American force was killed or wounded. It was also one of the most consequential, because the combination of Oriskany and Fort Stanwix's resistance stopped the British from capturing the Mohawk Valley and completing their plan to split the colonies.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-oriskany-st-leger-retreat", name: "St. Leger's British Force Retreats After Oriskany and Fort Stanwix", startDate: new Date("1777-08-22"), datePrecision: "DAY", summary: "The British retreat from Fort Stanwix ended their plan to control the Mohawk Valley as part of a three-pronged invasion — a failure that contributed directly to Burgoyne's isolation at Saratoga.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-oriskany-iroquois-confederacy-split", name: "Oriskany Splits the Iroquois Confederacy", startDate: new Date("1777-08-06"), datePrecision: "DAY", summary: "The Iroquois Confederacy had maintained neutrality for two years before the Revolution finally forced a choice; Oriskany was the moment when the Confederacy broke, with Oneida fighting alongside Americans and Mohawk alongside the British.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-oriskany-herkimer-tree", slug: "story-oriskany-herkimer-tree", title: "The General Under the Tree", storyType: "HISTORICAL_VOICE", textVersion: "Nicholas Herkimer was shot in the leg in the first minutes of the Battle of Oriskany. His horse was killed beneath him. His men carried him to a beech tree at the edge of the ravine, propped him against the trunk, and placed a saddle behind him. He lit his pipe and continued to command. The battle lasted six hours. When it was over, the Americans held the field but had lost perhaps half their force. Herkimer was carried home to his mansion on the Mohawk River. Surgeons amputated his leg. He survived the operation but died of complications nine days after the battle, on August 16, 1777. He was 49 years old. His brother fought on the other side.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── PA: Chadds Ford ───────────────────────────────────────────────────────────

async function seedChadds() {
  const id = "us-pa-chadds-ford";
  await upsertPlace({ id: "place-chadds-brandywine-battlefield", name: "Brandywine Battlefield State Historic Site", placeType: "BATTLEFIELD", description: "The site of the Battle of Brandywine on September 11, 1777 — the largest battle of the Revolution by number of troops engaged. Washington positioned his army along Brandywine Creek with Chadds Ford as the main crossing point. Howe feinted at the ford while sending nearly half his army on a twelve-mile flanking march. The flanking column crossed at an unguarded ford to the north and hit Washington's exposed right. The Americans were defeated; Philadelphia fell two weeks later.", lat: 39.8651, lng: -75.5913, address: "1491 Baltimore Pike, Chadds Ford, PA 19317", hours: "Tue–Sat 9am–5pm, Sun noon–5pm", admission: "Fee", website: "https://www.pa.gov/agencies/dcnr/state-parks/brandywine-battlefield", town: { connect: { id } } });
  await upsertPlace({ id: "place-chadds-washington-headquarters", name: "Benjamin Ring House (Washington's Headquarters)", placeType: "HISTORIC_HOUSE", description: "The farmhouse used as Washington's headquarters on September 11, 1777, during the Battle of Brandywine. Washington spent the morning here receiving intelligence about the British approach, much of which proved confusing and contradictory. The house is preserved within the Brandywine Battlefield State Historic Site. It is one of the few surviving structures directly associated with Washington's use as a command post.", lat: 39.8644, lng: -75.5925, address: "1491 Baltimore Pike, Chadds Ford, PA 19317", hours: "With battlefield admission", admission: "Fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-chadds-lafayette-headquarters", name: "Gilpin House (Lafayette's Headquarters)", placeType: "HISTORIC_HOUSE", description: "The farmhouse used as headquarters by the Marquis de Lafayette during the Battle of Brandywine. Lafayette, 19 years old, was shot in the leg during the fighting and organized a fighting retreat that helped cover the American withdrawal. His wound was treated at a field hospital nearby. The house is preserved within the battlefield site.", lat: 39.8657, lng: -75.5899, address: "1491 Baltimore Pike, Chadds Ford, PA 19317", hours: "With battlefield admission", admission: "Fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-chadds-brandywine-river-museum", name: "Brandywine River Museum of Art", placeType: "MUSEUM", description: "The museum, housed in a 19th-century grist mill near Chadds Ford, includes the Howard Pyle School collection and significant holdings of American illustration and landscape art. The museum's setting on the Brandywine Creek evokes the terrain of the 1777 battle — the creek, its banks, and the rolling hills of Chester County are essentially unchanged in character. N.C. Wyeth's paintings of the Brandywine region provide a visual vocabulary for understanding the landscape.", lat: 39.8592, lng: -75.5918, address: "1 Hoffmans Mill Rd, Chadds Ford, PA 19317", hours: "Daily 9:30am–4:30pm", admission: "Fee", website: "https://www.brandywine.org", town: { connect: { id } } });
  await upsertPlace({ id: "place-chadds-brandywine-creek", name: "Brandywine Creek at Chadds Ford", placeType: "LANDMARK", description: "The Brandywine Creek at Chadds Ford — the main British crossing point Washington expected, and the ford the British successfully feinted at while flanking to the north. The creek is relatively shallow at Chadds Ford; in September 1777 it was crossable on foot in most places. The ford is no longer a primary crossing; a bridge serves the road. The creek and its banks retain the general character they had in 1777.", lat: 39.8654, lng: -75.5910, address: "Chadds Ford, PA 19317", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-chadds-battle-brandywine", name: "Battle of Brandywine — Washington's Largest Defeat", startDate: new Date("1777-09-11"), datePrecision: "DAY", summary: "Brandywine was Washington's largest single defeat — 11,000 Americans against 12,500 British — and opened the road to Philadelphia. Despite the defeat, the Continental Army survived intact, which was itself a kind of victory.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-chadds-lafayette-wounded", name: "Lafayette Wounded at Brandywine", startDate: new Date("1777-09-11"), datePrecision: "DAY", summary: "Lafayette's conduct at Brandywine — volunteering to help organize the retreat despite being wounded — cemented his reputation with Washington and with Congress, securing the role he would play at Yorktown four years later.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-chadds-spy-knyphausen", name: "Knyphausen Pins Washington at Chadds Ford", startDate: new Date("1777-09-11"), datePrecision: "DAY", summary: "The British deception at Chadds Ford was one of the most effective tactical feints of the Revolution — convincing Washington that the main attack was coming from the south while the decisive force circled to the north.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-chadds-second-ford", slug: "story-chadds-second-ford", title: "The Ford Nobody Told Him About", storyType: "HISTORICAL_VOICE", textVersion: "Washington had his maps wrong. His scouts told him there was no ford to the north that Howe could use to cross the Brandywine. A local farmer named Thomas Cheney rode into Washington's headquarters during the battle, shouting that he could see British troops crossing to the north. Washington's aides didn't believe him — the maps said no ford. By the time Washington accepted the intelligence and began repositioning, Cornwallis's 8,000 men were already across and moving south. Cheney was right. The ford existed. It was on no American map. Washington lost the battle because he didn't know the ground well enough. He would spend the rest of the war learning from that mistake.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── RI: Portsmouth ────────────────────────────────────────────────────────────

async function seedPortsmouth() {
  const id = "us-ri-portsmouth";
  await upsertPlace({ id: "place-portsmouth-butts-hill-fort", name: "Butts Hill Fort", placeType: "BATTLEFIELD", description: "The earthwork fortification at the northern end of Aquidneck Island, which served as the main American defensive position during the Battle of Rhode Island on August 29, 1778. Colonel Christopher Greene's First Rhode Island Regiment — recruited from free Black men and formerly enslaved men who were promised freedom for service — held the Butts Hill position and repeatedly repulsed Hessian attacks, the most celebrated action of the engagement.", lat: 41.6037, lng: -71.2568, address: "Butts Hill Rd, Portsmouth, RI 02871", hours: "Open daily (earthworks visible from road)", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-portsmouth-battle-monument", name: "Battle of Rhode Island Monument", placeType: "MONUMENT", description: "A granite monument near the Butts Hill Fort site commemorating the Battle of Rhode Island and specifically the service of the First Rhode Island Regiment. The monument acknowledges the regiment's majority-Black composition — unprecedented in the Continental Army — and the soldiers' conduct under repeated assault by Hessian troops. The monument was dedicated in 1878, 100 years after the battle.", lat: 41.6032, lng: -71.2571, address: "Butts Hill Rd, Portsmouth, RI 02871", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-portsmouth-quaker-hill", name: "Quaker Hill Battlefield", placeType: "BATTLEFIELD", description: "The hill in Portsmouth where the heaviest fighting of the Battle of Rhode Island took place on August 29, 1778. The engagement was a fighting retreat: American forces under General John Sullivan withdrew north under British pressure after the French fleet under d'Estaing failed to materialize as planned. Quaker Hill preserves the terrain of the battle, with stone walls and agricultural fields essentially unchanged.", lat: 41.6071, lng: -71.2535, address: "Quaker Hill Rd, Portsmouth, RI 02871", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-portsmouth-portsmouth-historical-society", name: "Portsmouth Historical Society", placeType: "MUSEUM", description: "The Portsmouth Historical Society maintains collections related to the town's role in the Revolution, including records of the Battle of Rhode Island and the First Rhode Island Regiment. The museum occupies the Christian Union Church (1865) in the center of Portsmouth. The society's collections include artifacts from the battle and documentation of the enslaved men from Rhode Island who fought for their freedom.", lat: 41.5974, lng: -71.2569, address: "870 E Main Rd, Portsmouth, RI 02871", hours: "Tue–Sun 1–5pm (summer)", admission: "Small fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-portsmouth-prescott-farm", name: "Prescott Farm (General Prescott Capture Site)", placeType: "HISTORIC_HOUSE", description: "The area associated with the capture of British General Richard Prescott on July 9–10, 1777, by Lieutenant Colonel William Barton and 40 volunteers. Prescott was captured from his headquarters in a farmhouse by a small boat party that came ashore in the night. The capture was used to negotiate the release of American General Charles Lee. Prescott Farm is now a preservation property of the Aquidneck Land Trust.", lat: 41.6100, lng: -71.2600, address: "2009 W Main Rd, Middletown, RI 02842", hours: "Open for tours seasonally", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-portsmouth-battle-rhode-island", name: "Battle of Rhode Island — First Rhode Island Regiment Holds", startDate: new Date("1778-08-29"), datePrecision: "DAY", summary: "The First Rhode Island Regiment's defense at Butts Hill was the most celebrated action of the battle and became emblematic of the Black soldiers' contribution to American independence — men who fought for a freedom the Declaration promised but their society had not yet granted.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-portsmouth-first-ri-recruited", name: "Rhode Island Recruits First Rhode Island Regiment", startDate: new Date("1778-02-14"), datePrecision: "DAY", summary: "Rhode Island's manumission act for military service was the most sweeping legal emancipation of the Revolutionary era — hundreds of enslaved men became legally free in exchange for Continental Army service.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-portsmouth-prescott-capture", name: "William Barton Captures British General Prescott", startDate: new Date("1777-07-10"), datePrecision: "DAY", summary: "The Prescott capture demonstrated American raiding capability behind British lines and provided a prisoner valuable enough to exchange for General Charles Lee.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-portsmouth-freedom-for-service", slug: "story-portsmouth-freedom-for-service", title: "Freedom for Service", storyType: "HISTORICAL_VOICE", textVersion: "The men of the First Rhode Island Regiment were promised freedom in exchange for their lives. Rhode Island would compensate their owners; they would get their liberty — if they survived. Hundreds enlisted. At Butts Hill on August 29, 1778, they faced two Hessian regiments that charged their position three times. They held three times. The Hessians didn't break them. After the war, some of these men found that their legal freedom was harder to maintain than they had been promised. The records of the regiment are incomplete. Many of the men are known only by first names. They held the line at Butts Hill for a country that did not yet fully recognize them as people.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── RI: Warwick ───────────────────────────────────────────────────────────────

async function seedWarwick() {
  const id = "us-ri-warwick";
  await upsertPlace({ id: "place-warwick-gaspee-point", name: "Gaspee Point", placeType: "LANDMARK", description: "The point on Narragansett Bay where HMS Gaspee, a British revenue schooner, ran aground on June 9, 1772, while chasing the colonial packet boat Hannah. That night, Abraham Whipple led eight boatloads of Providence men to the stranded vessel, wounded its captain William Dudingston, put the crew ashore, and burned the ship to the waterline. The Gaspee Affair was the first violent act of colonial resistance and led directly to the formation of the Committees of Correspondence.", lat: 41.7019, lng: -71.4171, address: "Gaspee Point, Warwick, RI 02886", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-warwick-gaspee-monument", name: "Gaspee Affair Monument", placeType: "MONUMENT", description: "A monument near Gaspee Point commemorating the June 9, 1772 burning of HMS Gaspee. The event is celebrated annually in Warwick with the Gaspee Days festival, including a parade and reenactment. The monument marks one of the most significant acts of colonial resistance before the better-known events of 1773–1775.", lat: 41.7010, lng: -71.4165, address: "Gaspee Point, Warwick, RI 02886", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-warwick-pawtuxent-village", name: "Pawtuxet Village Historic District", placeType: "LANDMARK", description: "One of the oldest continuously settled communities in Rhode Island, Pawtuxet Village sits at the point where the Pawtuxet River meets Narragansett Bay. The village was home to several participants in the Gaspee Affair. Its 18th-century streetscape — compact houses close to the water — reflects the maritime commercial culture that produced both the men who resisted HMS Gaspee and the Whipple family who led the attack.", lat: 41.7064, lng: -71.4198, address: "Pawtuxet Village, Warwick, RI 02886", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-warwick-kent-county-courthouse", name: "Warwick City Hall (Old Courthouse Site)", placeType: "GOVERNMENT", description: "The area where colonial Kent County's governmental functions were conducted. Warwick's colonial government was one of the first to formally resist British trade enforcement, reflecting the broader pattern of Rhode Island commercial resistance to the Navigation Acts. The Gaspee Affair grew directly from this resistance culture.", lat: 41.7001, lng: -71.4162, address: "3275 Post Rd, Warwick, RI 02886", hours: "Mon–Fri 8:30am–4:30pm", admission: "Free (exterior)", town: { connect: { id } } });
  await upsertPlace({ id: "place-warwick-narragansett-bay", name: "Narragansett Bay at Warwick", placeType: "LANDMARK", description: "The waters of Narragansett Bay off Warwick were the scene of the Gaspee Affair and the broader struggle over British customs enforcement that preceded the Revolution. Rhode Island's colonial economy depended on trade that sometimes violated British regulations; the revenue schooners like Gaspee enforced those regulations aggressively. The bay's geography — numerous coves, islands, and inlets — made it ideal for smuggling and for the kind of night raid that destroyed the Gaspee.", lat: 41.6900, lng: -71.4000, address: "Narragansett Bay, Warwick, RI", hours: "Open daily", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-warwick-gaspee-burned", name: "HMS Gaspee Burned at Gaspee Point", startDate: new Date("1772-06-09"), datePrecision: "DAY", summary: "The Gaspee Affair was the first violent act of colonial rebellion against British authority — three years before Lexington. It led directly to the establishment of the Committees of Correspondence and demonstrated that colonial resistance could be organized, effective, and go unpunished.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-warwick-gaspee-commission-fails", name: "Royal Commission Fails to Prosecute Gaspee Raiders", startDate: new Date("1773-01-01"), datePrecision: "YEAR", summary: "The commission's failure — and the threat that accused colonists would be taken to England for trial — prompted colonial assemblies to establish Committees of Correspondence, the organizational infrastructure for coordinated resistance.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });
  await upsertEvent({ id: "event-warwick-whipple-continental-navy", name: "Abraham Whipple Commands Continental Navy Vessels", startDate: new Date("1775-06-15"), datePrecision: "MONTH", summary: "Whipple's career illustrated how the Gaspee organizers transitioned from colonial resistance to organized Continental military service — the same men, the same networks, now operating under a revolutionary government.", verificationStatus: "VERIFIED", significanceWeight: 70, town: { connect: { id } } });

  await upsertStory({ id: "story-warwick-before-boston", slug: "story-warwick-before-boston", title: "Before the Tea Party", storyType: "HISTORICAL_VOICE", textVersion: "Everyone knows the Boston Tea Party. Fewer people know that eighteen months before Bostonians dumped tea into the harbor, sixty men from Providence and Warwick rowed out into Narragansett Bay, boarded a British naval vessel, shot its captain, and burned it to the waterline. The royal commission that investigated found nothing. No witnesses. No perpetrators. Rhode Island had just shown the other colonies that it was possible to resist British enforcement directly, violently, and get away with it. Boston was paying attention.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── VT: Hubbardton ────────────────────────────────────────────────────────────

async function seedHubbardton() {
  const id = "us-vt-hubbardton";
  await upsertPlace({ id: "place-hubbardton-battlefield", name: "Hubbardton Battlefield State Historic Site", placeType: "BATTLEFIELD", description: "The site of the Battle of Hubbardton on July 7, 1777 — the only Revolutionary War battle fought entirely on Vermont soil. American rear-guard forces under Colonel Seth Warner and Colonel Ebenezer Francis checked the British pursuit after Burgoyne captured Fort Ticonderoga. The battlefield is preserved largely as it was in 1777, with views of the hills across which the British advanced. A small museum and interpretive markers explain the engagement.", lat: 43.6748, lng: -73.1701, address: "5696 Monument Rd, Hubbardton, VT 05743", hours: "Tue–Sun 9am–5pm (late May–mid-Oct)", admission: "Small fee (state historic site)", town: { connect: { id } } });
  await upsertPlace({ id: "place-hubbardton-warner-monument", name: "Seth Warner Monument", placeType: "MONUMENT", description: "A monument at the Hubbardton Battlefield commemorating Colonel Seth Warner and the men of the Green Mountain Boys who fought the rear-guard action on July 7, 1777. Warner was one of Vermont's most important Revolutionary military figures — he had been among the Green Mountain Boys who captured Fort Ticonderoga with Ethan Allen in 1775 and now commanded the rear guard as Ticonderoga was evacuated two years later.", lat: 43.6746, lng: -73.1699, address: "5696 Monument Rd, Hubbardton, VT 05743", hours: "Same as battlefield", admission: "Small fee", town: { connect: { id } } });
  await upsertPlace({ id: "place-hubbardton-visitor-center", name: "Hubbardton Battlefield Visitor Center", placeType: "MUSEUM", description: "The small museum at the Hubbardton Battlefield interprets the battle and its role in Burgoyne's campaign. The collection includes maps, weapons, and artifacts recovered from the site. The center explains why a tactical defeat here — the Americans eventually withdrew — was strategically significant: Warner's stand delayed Burgoyne's pursuit long enough for the American army to regroup.", lat: 43.6748, lng: -73.1701, address: "5696 Monument Rd, Hubbardton, VT 05743", hours: "Same as battlefield", admission: "With battlefield admission", town: { connect: { id } } });
  await upsertPlace({ id: "place-hubbardton-east-creek-road", name: "East Creek Road (American Retreat Route)", placeType: "TRAIL", description: "The historic road through the Hubbardton area along which the retreating American army passed after the fall of Ticonderoga and along which Warner's rear guard made its stand. The road today passes through the same hill country the soldiers crossed in the summer of 1777 — a landscape of rounded Vermont hills, stone walls, and forest that has changed relatively little in character.", lat: 43.6748, lng: -73.1650, address: "East Creek Rd, Hubbardton, VT", hours: "Open daily", admission: "Free", town: { connect: { id } } });
  await upsertPlace({ id: "place-hubbardton-memorial-museum", name: "Hubbardton Township Historical Museum", placeType: "MUSEUM", description: "Hubbardton is one of the least populated and most rural towns in Vermont, and its small historical museum reflects the community that occupied this landscape before, during, and after the Revolution. The exhibits cover the township's settlement, the battle, and the farming culture that sustained the community for two centuries. The museum provides context for why men settled this remote corner of Vermont and why they fought to defend it.", lat: 43.6720, lng: -73.1680, address: "Hubbardton, VT 05743", hours: "Seasonal; call ahead", admission: "Free", town: { connect: { id } } });

  await upsertEvent({ id: "event-hubbardton-battle", name: "Battle of Hubbardton — Vermont's Only Revolutionary Battle", startDate: new Date("1777-07-07"), datePrecision: "DAY", summary: "Hubbardton was the only Revolutionary War battle fought entirely on Vermont soil. Tactically a British victory, it delayed Burgoyne's pursuit long enough for the retreating American army to reach safety — a strategic contribution to the eventual American victory at Saratoga.", verificationStatus: "VERIFIED", significanceWeight: 100, town: { connect: { id } } });
  await upsertEvent({ id: "event-hubbardton-ticonderoga-evacuation", name: "American Army Evacuates Fort Ticonderoga", startDate: new Date("1777-07-05"), datePrecision: "DAY", summary: "The loss of Ticonderoga was a shock to the American cause — the fort had seemed impregnable. It fell without a major battle because Burgoyne put artillery on a mountain the Americans had left undefended.", verificationStatus: "VERIFIED", significanceWeight: 80, town: { connect: { id } } });
  await upsertEvent({ id: "event-hubbardton-saratoga-connection", name: "Burgoyne's Delayed Campaign Ends at Saratoga", startDate: new Date("1777-10-17"), datePrecision: "DAY", summary: "Burgoyne's surrender at Saratoga — significantly delayed by the fighting at Hubbardton and other engagements — brought France into the war as an American ally, transforming the Revolution from a colonial revolt into a global war.", verificationStatus: "VERIFIED", significanceWeight: 90, town: { connect: { id } } });

  await upsertStory({ id: "story-hubbardton-last-stand", slug: "story-hubbardton-last-stand", title: "The Rear Guard", storyType: "HISTORICAL_VOICE", textVersion: "The rear guard's job is to die slowly so that others may live. Seth Warner's men knew this. They had been retreating for two days from Fort Ticonderoga, watching the army they were covering move south as fast as it could. On the morning of July 7, 1777, the British caught up. Warner's men held a hill above Hubbardton and fought for two hours. Colonel Ebenezer Francis was killed leading a counterattack. When Warner finally gave the order to scatter and regroup at Manchester, the rear guard had bought enough time. Burgoyne's pursuit stopped. The main army survived. Warner brought his men back together. Three months later, at Saratoga, they helped finish what had been started in the hills above Hubbardton.", verificationStatus: "ORAL_TRADITION", town: { connect: { id } } });
}

// ── CT: Lebanon (already done above) ──────────────────────────────────────────

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`Mode: ${DRY ? "DRY RUN" : "LIVE"}\n`);

  const seeders: Array<[string, () => Promise<void>]> = [
    ["CT Lebanon", seedLebanon],
    ["IN Vincennes", seedVincennes],
    ["MA Quincy", seedQuincy],
    ["MA Acton", seedActon],
    ["MA Lincoln", seedLincoln],
    ["MA Bedford", seedBedford],
    ["ME Machias", seedMachias],
    ["NC Edenton", seedEdenton],
    ["NC Halifax", seedHalifax],
    ["NH New Castle", seedNewCastle],
    ["NY Oriskany", seedOriskany],
    ["PA Chadds Ford", seedChadds],
    ["RI Portsmouth", seedPortsmouth],
    ["RI Warwick", seedWarwick],
    ["VT Hubbardton", seedHubbardton],
  ];

  for (const [name, seeder] of seeders) {
    console.log(`\n── ${name} ──`);
    try {
      await seeder();
      console.log(`  ✓ done`);
    } catch (e) {
      console.error(`  ✗ error: ${String(e).slice(0, 120)}`);
    }
  }

  console.log("\n✅ Stub towns seeded.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
